### ISSUE TITLE
cmd+k overrides Slack

### ISSUE THREAD

**Issue by Juleship** [leits/MeetingBar#1]
**Describe the bug**
When I press cmd+K I expect to jump to a user or a channel in Slack. Instead MeetingBar opens a Chrome tab. This makes the extension unusable for me. I'd love to have the choice to deactivate it or override the shortcut.

**To Reproduce**
1. cmd+K inside Slack
2. I expect to get the fast menu to choose a conversation/person's name
3. I open a Chrome tab with Google Meet

**Comment by leits** [comment]
Added temporary option to disable global shortcuts in the fresh release:
https://github.com/leits/MeetingBar/releases/tag/v1.0b10

Next steps:
* Make join next meeting shortcut customizable
https://github.com/leits/MeetingBar/projects/1#card-39268281
* Make create event shortcut customizable
https://github.com/leits/MeetingBar/projects/1#card-39268261

Thanks, @Juleship!

**Comment by billinghamj** [comment]
Would it be possible to disable just one of the shortcuts? Cmd+J is pretty much always fine, not super common, and very handy to have as an option. Cmd+K is very common though

**Comment by leits** [comment]
@billinghamj Added this to the latest release: https://github.com/leits/MeetingBar/releases/tag/v1.0b14
Check it, pls.)
