### ISSUE TITLE
Bug: Menu bar icons shows all done even tho there are a lot of events.

### ISSUE THREAD

**Issue by labtocat** [leits/MeetingBar#101]
**App version**
  2.0.2 (started to notice from 2.0.0)
**Describe the bug**
This can be noticed in a span of 2 days, once the calendar events are caught up for day one Icon changes to all done (as expected) and on the next day Icon still stays like done even tho events are fetched for next day. 

**To Reproduce**
1. Go to 'MeetingBar'
2. Click on 'preferences -> show event for 'today''
3. Click on 'Appearance -> statuts bar -> event title'
4. Observer the error on day 2

**Expected behavior**
Once a new day is fetched the meetingbar all done icon should be changed and event should be shown

**Screenshots**
<img width="390" alt="Screenshot 2020-12-01 at 9 29 32 AM" src="https://user-images.githubusercontent.com/2720972/100696248-235a0300-33b9-11eb-83a6-750074fc6ff3.png">

**Desktop (please complete the following information):**
 - macOS version: Big Sur 11.0.1

**Comment by leits** [comment]
@labtocat ,  fixed in the latest version. Check it out!
