### ISSUE TITLE
Feature Request: (Option to) Hide meetings with no other participants

### ISSUE THREAD

**Issue by 0bmxa** [leits/MeetingBar#103]
**Is your feature request related to a problem? Please describe.**
I have a bunch of meetings in my calendar, that are just blockers or tasks for myself, which are not "real meetings". They all show up in the list, and are a bit distracting from the actual meetings I have with others.

**Describe the solution you'd like**
Hide meetings that have no other participants from the list.

Ideally not by default, but with an option in Preferences to turn this on/off.
(Probably in the `General` under `Show events for [today/tomorrow]`.)

**Describe alternatives you've considered**
Alternative display:
* Instead of hiding them, they could also be grayed out.

Alternative decision which to display:
* Hide meetings with no video call
* Hide meetings with a certain prefix in the title
* (Hide meetings with no other guests)

**Additional context**
N/A, sorry

**Comment by 0bmxa** [comment]
I'm also happy to implement this feature myself, but I first wanted to check if there's any interest in this by anyone else, or if anything could be done differently!

**Comment by jgoldhammer** [comment]
This is merged now 🎉

**Comment by 0bmxa** [comment]
I'll close this as its merged now!
