### ISSUE TITLE
Bug: App Icon is too big compared to other Big Sur Icons

### ISSUE THREAD

**Issue by melgu** [leits/MeetingBar#104]
**App version**
2.0.5

**Describe the bug**
The Icon is much bigger than the standard Big Sur icon size and therefore seems a bit out-of-place.

**To Reproduce**
1. Download the app

**Expected behavior**
The icon has the same size as other icons on Big Sur

**Screenshots**
<img width="568" alt="Bildschirmfoto 2020-12-07 um 09 36 27" src="https://user-images.githubusercontent.com/9601403/101328356-2ef17200-3870-11eb-91fa-1cbc53a8b960.png">

**Desktop (please complete the following information):**
 - macOS version: 11.0.1

**Comment by jgoldhammer** [comment]
What do you think @leits? Do you have the possibility to check that? I am still on Catalina on both macbooks...

**Comment by leits** [comment]
Me too, @jgoldhammer. But I have an icon with margins from the author. As soon as I have a chance, I'll try to fix it.

**Comment by leits** [comment]
@melgu, released! Check it out!

**Comment by melgu** [comment]
Looks good! Love the other 3.0 changes as well 😃
