### ISSUE TITLE
Allow account selection for new Google Meet meetings

### ISSUE THREAD

**Issue by xeroxoid** [leits/MeetingBar#105]
**Is your feature request related to a problem? Please describe.**
When creating a new meeting with Google meet it always selects the default Google account that is signed in in the browser.
This happens even if only one Google account is active in the Calendar preferences.

**Describe the solution you'd like**
Adding an option to select which account to use for new Google Meet meetings (code needs to append `authuser=ACCOUNT_ADDRESS` i.e. `meet.google.com/new?authuser=notdefaultbrowseraccount@gmail.com`)

**Describe alternatives you've considered**
A simpler option might be to add an input to allow for custom urls for new meetings to allow the user to customise it.

Excellent OSS by the way! Thanks so much for putting in the effort. One cool tool in our WFH toolbox :)

**Comment by jgoldhammer** [comment]
Nice idea to have a custom url input field. I guess this is the most flexible solution for this, instead of building solutions for each meeting service.
