### ISSUE TITLE
Feature request: Add pref to hide all-day meetings

### ISSUE THREAD

**Issue by SanderGit** [leits/MeetingBar#114]
**Is your feature request related to a problem? Please describe.**
I don't have to be reminded that I have a holiday for the next 4 hours and 46 minutes.

**Describe the solution you'd like**
Add a preference to hide all-day events.

**Describe alternatives you've considered**
I cannot really think of an alternative.

**Comment by jgoldhammer** [comment]
Hi SanderGit,

this is possible with the changes in HEAD.

![image](https://user-images.githubusercontent.com/3872101/103647830-3170e580-4f5c-11eb-9994-593b42230387.png)

Just wait for the next release :-)

**Comment by Rabattkarte** [comment]
Maybe this relates to my feature request #146?

**Comment by leits** [comment]
@SanderGit, @Rabattkarte, released! Check it out!
