### ISSUE TITLE
Feature: Do not display events without meeting details

### ISSUE THREAD

**Issue by Rabattkarte** [leits/MeetingBar#146]
**Is your feature request related to a problem? Please describe.**

I'm wondering what the main goal of this app should be. I like the idea of a meeting aggregator! Right now I see appointments of which I am the only member as well. This is mostly not needed and also there is no meeting information added to those appointments. E. g. a half-day off blocker in my calendar.

**Describe the solution you'd like**

I'd love to have a setting to only display events which are associated with meeting details for Zoom, Meet, Teams, (whatever).

**Describe alternatives you've considered**

I do not see an alternative other than not changing the current behavior.

**Additional context**

You can reproduce this by creating a new event without content and you as the only member.

**Comment by jgoldhammer** [comment]
There is also #103 - it will be part of next release. Will that help you? If yes, we can close this Ticket...

**Comment by Rabattkarte** [comment]
Perfectly, yes, I did not see that closed issue. Sorry for the inconvenience.
