### ISSUE TITLE
Bug: Unable to join Zoom meeting with password

### ISSUE THREAD

**Issue by afds** [leits/MeetingBar#149]
**App version**
2.0.5

**Describe the bug**
Unable to join Zoom meeting with password.

**To Reproduce**
Create a meeting in Google Calendar with Chrome Zoom plugin.
This is what inside when I open that event in Calendar app:
```
...
<br><br>──────────<br><br>XXX is inviting you to a scheduled Zoom meeting.<br><br>Join Zoom Meeting<br><a href="https://xxx.zoom.us/j/12345667890?pwd=MU5pUUNtR0paEZtZmlqK3lnSHRpdz09">https://xxx.zoom.us/j/12345667890?pwd=MU5pUUNtR0paEZtZmlqK3lnSHRpdz09</a><br><br>Meeting ID: 123 4566 7890<br>Passcode: xxx<br><br>Join by SIP<br>
...
```

**Expected behavior**
Joined the meeting.

**Desktop (please complete the following information):**
 - macOS version: 10.15.7

**Additional context**
The problem seems to be with zoom regex that is [defined here](https://github.com/leits/MeetingBar/blob/master/MeetingBar/Constants.swift#L25).
When I add custom regex `https:\/\/(?:[a-z0-9-.]+)?zoom.(?:us|com.cn)\/j\/[0-9a-zA-Z?=]*` in Advanced Preferences then I can join meeting successfully.

**Comment by jgoldhammer** [comment]
I think we could use the provided regex from @afds. What do you think @leits ?

**Comment by leits** [comment]
Yeah, I'll update our regex.
Thanks, @afds!

**Comment by leits** [comment]
@afds, released! Check it out!
