### ISSUE TITLE
Feature: option to only notify on mtgs I've accepted

### ISSUE THREAD

**Issue by hunleyd** [leits/MeetingBar#150]
It would be nice if there was a toggle in the UI to notify about meetings that have not been accepted. It could default to on, to preserve the existing behavior, but those of us who do not want to be reminded of a meeting we haven't accepted can toggle it off. It's probably a corner case, but sometimes I don't want to commit to accepting/declining a mtg so I leave it unanswered ;)

**Comment by jgoldhammer** [comment]
Hi @hunleyd - I understand your request. I will check the code if this is possible easily...

**Comment by jgoldhammer** [comment]
What do you think @hunleyd - should these pending events be displayed in the status bar and menu, but no notifications should be send?

**Comment by hunleyd** [comment]
I would think if you choose to not be notified you wouldn't want to see it either

**Comment by jgoldhammer** [comment]
Ok, I have developed a first version of this feature.

I have introduced a new setting "Pending events":
- all show options will display the event and trigger the notification
- hide option will hide pending events completely from the statusbar, menu and does not trigger a notification

![image](https://user-images.githubusercontent.com/3872101/104823402-164e8180-584a-11eb-89bd-5b6be7ba2e08.png)

Will that help?

**Comment by hunleyd** [comment]
That sounds great!
