### ISSUE TITLE
Feature (advanced): Custom template for menu item

### ISSUE THREAD

**Issue by leits** [leits/MeetingBar#160]
Allow advanced users to generate menu item in their own format from event details:

as example:
`{startTime} ({startTime - endTime}) - {title} ({attendess.count})`

⭐  feature request from @dentalala

**Comment by jgoldhammer** [comment]
Really nice idea. 

But I have thought more about it- I am still not sure if it is worth to develop it. What are additional elements a user want to see? 

- Location and URL are mostly too long (when these are urls)
- the attendee count is nice, but adds no real value

If you offer this, users should also be able to trim the elements, e.g. the title with a special syntax.
One advantage would be really to configure the order of the elements.

**Comment by dentalala** [comment]
📹 • 14:30

**Comment by leits** [comment]
Looks like overhead now, I'll close it.
