### ISSUE TITLE
Feature: support for additional browsers

### ISSUE THREAD

**Issue by eripa** [leits/MeetingBar#161]
**Is your feature request related to a problem? Please describe.**

I use Brave only for Google Meets (Safari for everything else), and I was hoping to use MeetingBar to launch Brave for meetings. Unfortunately it doesn't seem to support anything other than Chrome. I would love to see additional browser support.

**Describe the solution you'd like**

Add additional browser support for launching into, ideas:

- Brave
- Firefox
- Vivaldi

**Describe alternatives you've considered**

I can see that there's unreleased support for Chromium, which I will use in the meantime.

**Additional context**

Awesome app! Thanks 🙏

**Comment by jgoldhammer** [comment]
Thanks for your feature request. Do you want to help us and contribute via pull request?
If not, we will schedule it for a later time after release 3.0
