### ISSUE TITLE
Feature: Allow specifying the authuser when creating Google Meet meeting

### ISSUE THREAD

**Issue by blixt** [leits/MeetingBar#162]
**Is your feature request related to a problem? Please describe.**
I don't use the "Create Meeting" keyboard shortcut because it uses the wrong Google account and it takes more time to switch account than it does to just create a bookmark.

**Describe the solution you'd like**
Allow me to somehow specify the `authuser` parameter (my email) somehow when opening the "Create Meeting" link.

**Describe alternatives you've considered**
Using a bookmark instead of the MeetingBar shortcut.

**Comment by jgoldhammer** [comment]
Hi, 

this will be part of 3.0 release and is implemented in https://github.com/leits/MeetingBar/issues/105 .
With the new feature you can use your own custom url which will be opened.

I will close this ticket now. If you think this will not fix it, please open it.

Thanks
Jens
