### ISSUE TITLE
Bug: Can't open specific zoom url

### ISSUE THREAD

**Issue by nevadascout** [leits/MeetingBar#164]
Often, my company puts the meeting location as a physical Room and then puts a zoom or teams meeting link in the event description. MeetingBar seems to be unable to detect these meeting links.

Can MeetingBar search in the event description for meeting links?

(We am using Exchange-based email)

**Comment by hisaac** [comment]
Seconded, this would be great.

**Comment by leits** [comment]
Hi, @nevadascout, @nevadascout!
MeetingBar is already searching for a meeting link in this event description.
But search regexes may not be perfect.
Can you give an example of a description so I can check what's going wrong with parsing link?

**Comment by nevadascout** [comment]
Interesting... So I've created a meeting in outlook and set the location to be the text "zoom" then in the event description I've added `https://example.zoom.us/my/nevada.scout` and when I click the meeting link in MeetingBar I get a notification that it can't find the link.

This link seems to fail on the regex `https:\/\/(?:[a-z0-9-.]+)?zoom.(?:us|com.cn)\/j\/[0-9a-zA-Z?=]*` that you have in your Constants file.

It looks like the regex is expecting there to be `/j/` after `zoom.us` which is causing this problem.

If I click this link (`https://example.zoom.us/my/nevada.scout`) my browser correctly opens up Zoom, so I think this format should be supported. I suggest changing the regex to this:

```
https:\/\/(?:[a-z0-9-.]+)?zoom.(?:us|com.cn)\/(?:j|my)\/[0-9a-zA-Z?=.]*
```

I have:
* Added an or for `j` or `my` after `zoom.us`
* Added `.` to the last capture group to allow the suffix `nevada.scout` to match

Hope this helps, thanks!

**Comment by nevadascout** [comment]
Also interestingly, if I add this regex to MeetingBar it still says that it can't find the link... ¯\\_(ツ)_/¯

**Comment by leits** [comment]
Thanks for your research, @nevadascout!
I'll try to debug the app with this case and write back the results.

**Comment by nevadascout** [comment]
In v3.0.0 of MeetingBar when I click a meeting with one of these links it no longer gives a warning that the link isn't supported; it now opens the zoom app, but doesn't join the meeting

**Comment by jgoldhammer** [comment]
Thanks for reporting back.

I think we have to test this stuff more.
This link will not open in the zoom macos app because we are not prepared of these kind of links.

Our code looks like:

```
if Defaults[.useAppForZoomLinks] {
            let urlString = url.absoluteString.replacingOccurrences(of: "?", with: "&").replacingOccurrences(of: "/j/", with: "/join?confno=")
            var zoomAppUrl = URLComponents(url: URL(string: urlString)!, resolvingAgainstBaseURL: false)!
            zoomAppUrl.scheme = "zoommtg"
            let result = openLinkInDefaultBrowser(zoomAppUrl.url!)
            if !result {
                sendNotification(title: "Oops! Unable to open the link in Zoom app", text: "Make sure you have Zoom app installed, or change the app in the preferences.")
                _ = openLinkInDefaultBrowser(url)
            }
        } else {
            _ = openLinkInDefaultBrowser(url)
        }
```

We are only replacing the /j/, not my...
Unfortunately the zoom app does not report back an error so there is no notification...

Can you please share a real zoom url in your case, so that we are able to fix the code?

**Comment by jgoldhammer** [comment]
@nevadascout - can you help us with a real zoom url example? Thx.

**Comment by nevadascout** [comment]
Hey, an example link is in this format: `https://example.zoom.us/my/nevada.scout`

These are custom personal links so I'm reluctant to share my real one publicly. This guide shows you how to create one for your own zoom profile.

https://support.zoom.us/hc/en-us/articles/201362843-Personal-meeting-ID-PMI-and-personal-link#h_08f381ef-1e88-417c-b014-a2b9ad4abbda

You need to be a paid user to have a custom link. If you're not able to create one, I can probably share mine with you privately for testing purposes.

**Comment by jgoldhammer** [comment]
Sorry for the long delay. To verify it completely please send me a zoom link via mail, so that I can test it. Thanks!

**Comment by nevadascout** [comment]
Hi @jgoldhammer which email should I send it to?

**Comment by nevadascout** [comment]
@jgoldhammer Hey, I'd really like to get this in if we can :D 

Which email should I send the zoom link to?

**Comment by jgoldhammer** [comment]
Please use Jens.goldhammeratgooglemaildotcom

nevada_scout ***@***.***> schrieb am Mi. 5. Mai 2021 um 12:20:

**Comment by leits** [comment]
Hi, @jgoldhammer, @nevadascout!
Did you have a chance to find out what the problem was?

**Comment by nevadascout** [comment]
@leits I spoke with Jens, but I'm not sure if he was able to reproduce this or not. @jgoldhammer can you tell us any more? :)

**Comment by leits** [comment]
@jgoldhammer, please share some info ^

I also made changes to the regex, it could help. So I close this issue until there is no new information.
