### ISSUE TITLE
Feature: Support additional browsers using a custom app path

### ISSUE THREAD

**Issue by jgoldhammer** [leits/MeetingBar#167]
**Is your feature request related to a problem? Please describe.**

Advanced users will use special versions of browsers (like the dev or beta version) or browser which are not very common. The current browser selection only enables to use predefined browsers - the user cannot determine custom browsers like ms edge dev or chrome canary version.

Out of scope are arguments because arguments for apps are not supported in sandbox mode.

**Describe the solution you'd like**
I guess it would help to let users define custom browser with a path to the app.

**Describe alternatives you've considered**
Use the available predfined browers

**Comment by jgoldhammer** [comment]
What do you think, @leits ?

**Comment by leits** [comment]
I think it's a good idea!

**Comment by joshuarudd** [comment]
💯
