### ISSUE TITLE
Bug: remove "cask" from brew install cmd

### ISSUE THREAD

**Issue by iwan-uschka** [leits/MeetingBar#168]
Check out the readme. It tells us to execute `brew cask install meetingbar` but at least my machine running `brew@2.7.7` it should be `brew install meetingbar`.

Just mentioning. Don't have time to make a PR ;)

**Comment by jgoldhammer** [comment]
Hi Iwan,

we have following in the readme:

![image](https://user-images.githubusercontent.com/3872101/106431510-a8bb6b80-646d-11eb-9b71-7fcba6ddd4d1.png)

This syntax is also correct, altthough brew install meetingbar is also working.
I will close the ticket for now.

Thanks

**Comment by iwan-uschka** [comment]
You're absolutely right. I read what i "wanted" to read and missed `--` somehow. Didn't know the option `--cask` before. Thanks for teaching me that :)

**Comment by iwan-uschka** [comment]
Great app btw 👍
