### ISSUE TITLE
Feature: select notification sound from system alert sounds (default to system alert sound)

### ISSUE THREAD

**Issue by sathran** [leits/MeetingBar#170]
**Is your feature request related to a problem? Please describe.**
The current notification sound is not driven by the OS settings, and is not alterable.

**Describe the solution you'd like**
An ideal scenario, in my perspective:
When that I am in General settings
Then I have a way to change the sound used for notifications, from the system sound effect list
And the default setting should be "system alert sound"

**Describe alternatives you've considered**
A barebones approach:
Given that "send notification" is on
When the notification appears
Then the notification sound should be whichever is set as the system alert sound

**Additional context**
This app has MASSIVELY improved my quality of life!
Great job :)

**Comment by jgoldhammer** [comment]
Hi @sathran - thanks for your feature request.
Maybe you can give us more details about the problem that the current notifications do not play the system sound?

AFAIK we already use the standard notification sound in our code base, so our notification for events should play the default sound driven by macos.

Reference:
![image](https://user-images.githubusercontent.com/3872101/107606077-49abe280-6c35-11eb-8d74-997de534d537.png)

https://www.hackingwithswift.com/read/21/2/scheduling-notifications-unusernotificationcenter-and-unnotificationrequest

**Comment by sathran** [comment]
Hey! Thanks for getting back to me.

Here's the default alert sound I have set on my system:
![image](https://user-images.githubusercontent.com/1090355/108524688-33ea8d00-72c7-11eb-9988-d4245f8d15c1.png)

But when MeetingBar displays a notification, the [generic default notification sound](https://www.youtube.com/watch?v=AiMbf0ovXT4) is played.
So maybe the code you show there is 100% correct and my description left a bit to be desired - let me know if I can help further.

**Comment by sathran** [comment]
Hey, hey! Just though I' add a bit of steam to this - this would likely be the way to play the users configured setting: https://developer.apple.com/documentation/audiotoolbox/1405202-audioservicesplayalertsound?language=objc

**Comment by leits** [comment]
Sorry, I'll close this.
I don't think it's worth complicating the settings.
