### ISSUE TITLE
Bug: Issues with service icons (Big Sur issue?)

### ISSUE THREAD

**Issue by nevadascout** [leits/MeetingBar#171]
App version 3.0.0.
macOS version: Big Sur 11.1

When I go to the dropdown menu in the app settings to change the icon this is what happens:

(Interestingly, all of the icons display correctly in the menu bar)

https://user-images.githubusercontent.com/377089/107212668-95794480-6a07-11eb-87fc-6cd898414c73.mov

**Comment by leits** [comment]
Thanks for the report, @nevadascout!
I'll fix this soon!
@jgoldhammer, jfyi

**Comment by jgoldhammer** [comment]
Maybe only the size for the icon is missing?

```
...
Image(nsImage: getImage(EventTitleIconFormat.eventtype.rawValue)).resizable()
                                .frame(width: 16.0, height: 16.0)
...
    func getImage(iconName){
        let icon = NSImage(named: iconName)
        icon!.size = NSSize(width: 16, height: 16);
        return icon
    }

```

Maybe the frame with width and height is not enough. WDYT?

**Comment by leits** [comment]
Fix checked by @yarsanich on Big Sure:
![зображення](https://user-images.githubusercontent.com/12017826/107423491-095d3f00-6b25-11eb-9556-754a278a1e3e.png)
Works perfectly!
