### ISSUE TITLE
Bug: Text alignment issue in menu while in 12 hr time

### ISSUE THREAD

**Issue by Techneaux** [leits/MeetingBar#172]
In meetingbar 3.0.0, there is an issue with text alignment in the menu for one of my meetings today.

![image](https://user-images.githubusercontent.com/8344081/107229255-31dd2000-69e3-11eb-8fc3-2b48a95d1332.png)

As shown in the image, most of the meetings look great but that 11 AM - 12 PM workout meeting has incorrect alignment for the 12PM end date.

If I turn off in settings the end time and icon, the misalignment stays:
![image](https://user-images.githubusercontent.com/8344081/107229432-710b7100-69e3-11eb-954b-941c58034ec4.png)

Note however if I switch to 24 hour time, the alignment is fixed:
![image](https://user-images.githubusercontent.com/8344081/107229492-841e4100-69e3-11eb-93b5-21b8aaf6d610.png)

**Comment by leits** [comment]
Thanks for the report, @Techneaux!

**Comment by leits** [comment]
Can't reproduce locally. @jgoldhammer, do you have any ideas?

**Comment by jgoldhammer** [comment]
I think it is an issue with the used font in Big Sur. Maybe the font is a little bit smaller, so that the tab character will not jump to the next position... 

I am also not able to reproduce locally with MacOS Catalina...
<img width="220" alt="Screenshot 2021-02-08 at 19 00 22" src="https://user-images.githubusercontent.com/3872101/107261816-0f2d2480-6a40-11eb-994a-afc0d31e6581.png">

**Comment by Techneaux** [comment]
Thanks all for investigating (and for this fantastic project). It does appear that this only happens to the shortest of text (pixel-wise: i.e.size of 11 vs other times) The alignment was working well until again today with another 11 AM meeting (pic below). Just wanted to share in case it helps later dev.

![image](https://user-images.githubusercontent.com/8344081/107640943-993fdd80-6c38-11eb-9316-44a2ab265d02.png)

**Comment by leits** [comment]
Found a solution, different indentations in the string strangely rendered on Big Sur.
![зображення](https://user-images.githubusercontent.com/12017826/108332092-1a1e4c80-71d8-11eb-83a7-39e9b53d8293.png)
