### ISSUE TITLE
Bug: Showing time under title results in wrong position

### ISSUE THREAD

**Issue by igorkulman** [leits/MeetingBar#175]
**App version**
3.0.0 from Homebrew

**Describe the bug**
When I set the meeting time to show under title the result in menu bar is misaligned to the top instead of centered and part of the meeting title is cropped.

**To Reproduce**
1. Go to Preferences
2. Select Appearance
3. Select "Show under title" for the Time option
4. Observe the menu bar

**Expected behavior**
Meeting name fully visible without crop.

**Screenshots**
<img width="360" alt="Screen Shot 2021-02-09 at 8 54 29" src="https://user-images.githubusercontent.com/4746070/107332556-9b792f00-6ab4-11eb-9815-c1377cbfec40.png">

**Desktop (please complete the following information):**
 - macOS version: 11.2

**Comment by jgoldhammer** [comment]
Thanks for the bug report. So Big Sur again behaves differently to Catalina regarding statusbar items and NSAttributedString. To have it centered in Catalina, I had to play with the baselineoffset and the multiple line height. Maybe it works in Big Sur without these adaptions. 

Code:
![image](https://user-images.githubusercontent.com/3872101/107333860-4dfdc180-6ab6-11eb-9827-9520e105edee.png)

https://stackoverflow.com/questions/45249666/set-top-alignment-for-labels-with-different-font-sizes-swift-3/48661251

What do you think @leits how to proceed with these big sur issues?

**Comment by leits** [comment]
@jgoldhammer, let's try to fix this under if-big-sure condition and make a test build to validate the fix.

@igorkulman, could you install the test build and check this bug when we prepare it?

**Comment by igorkulman** [comment]
> 
> @igorkulman, could you install the test build and check this bug when we prepare it?

Sure, I can even clone the project and run it from Xcode directly, just let me know which branch or what changes to make.

I tried adjusting `styles[NSAttributedString.Key.baselineOffset] = -3` and I do not think it will be enough, It moves the text a bit down but no matter what big value I put there it is still a bit cropped.

**Comment by jgoldhammer** [comment]
Maybe you can play around with lineHeightMultiple? Set it to 1 and see if this will work?

https://github.com/leits/MeetingBar/blob/365219bbc402796ad25486f69460cf8e9cee0580/MeetingBar/StatusBarItemControler.swift#L168

**Comment by igorkulman** [comment]
I tried tweaking line height and baseline offset but have not found a combination of values that would look ok yet.

**Comment by jgoldhammer** [comment]
Oh no! thanks @igorkulman for your effort!!

It seems that others have also the problem with Big Sur...
https://stackoverflow.com/questions/65167179/misaligned-nsattributedstring-in-macos-nsstatusitems-button

**Comment by leits** [comment]
Looks like we need to hide this option for big sure :(

**Comment by leits** [comment]
Temporary hide this option for Big Sure.
@jgoldhammer We will wait for the fix from apple team or there are other options?
