### ISSUE TITLE
Feature: Option to only show events from the near future

### ISSUE THREAD

**Issue by igorkulman** [leits/MeetingBar#176]
**Is your feature request related to a problem? Please describe.**
If I have a say sync call at 4pm I do not need to see it in the morning, it only becomes relevant for me to see it at about 3pm. In the morning it just makes me nervous seeing it :)

**Describe the solution you'd like**
Currently there is an option in the app to show events for "Today" or "Today and tomorrow". I would like an additional option of "Next X hours", ideally with customizable X

**Comment by jgoldhammer** [comment]
I think that would be a nice feature... @leits WDYT?

**Comment by KaiOelfke** [comment]
For me it would be even x minutes perhaps in 5 or 15 min intervals, but definitely below 1h.

**Comment by igorkulman** [comment]
Which version is this feature available in? I am running the latest 3.2.1 released after the related PR has been merge but I do not see the option in the app.

**Comment by leits** [comment]
Try this option in preferences:
<img width="812" alt="зображення" src="https://user-images.githubusercontent.com/12017826/113553546-9e018c00-9600-11eb-9ee2-1603f4256b13.png">

**Comment by igorkulman** [comment]
Got it thanks, I was looking in the wrong place remembering the PR screenshot.
