### ISSUE TITLE
Feature: Decode Service url from Outlook Safe Link url

### ISSUE THREAD

**Issue by hanssep** [leits/MeetingBar#183]
**Is your feature request related to a problem? Please describe.**
MeetingBar does not show meeting service details when url is a Outlook Safe Link url. Day view shows meeting times but does not show service used. When selecting a meeting, MeetingBar shows "Link not found" error.

**Describe the solution you'd like**
I would like MeetingBar to decode the service url from the Outlook Safe Link url so it shows the correct service and allow joining that meeting from MeetingBar.

**Describe alternatives you've considered**
Tried to a find a regex to solve this issue to no avail. Service url is between /?url= and &data parts of Outlook Safe Link. Service url needs to be URL decoded. 

**Additional context**
Example of Outlook Safe Link (parts of the url ):
`https://nam12.safelinks.protection.outlook.com/ap/t-59584e83/?url=https%3A%2F%2Fteams.microsoft.com%2Fl%2Fmeetup-join%2F19%253ameeting_[obfuscated]&data=[obfuscated]`

Correct service link:
`https://teams.microsoft.com/l/meetup-join/19%3ameeting_[obfuscated]`

**Comment by jgoldhammer** [comment]
More details to safe links can be found here:
https://www.askvg.com/why-outlook-adding-safelinks-protection-outlook-com-to-all-urls-in-your-emails-and-how-to-disable-it/

**Comment by leits** [comment]
Got a few more feedback for this.
It looks like we need to prioritize this because for users it's more of a bug than a feature.

Jens, I see you have a branch with changes, are you working on it?
Or can I start it myself?

**Comment by jgoldhammer** [comment]
I have started working on it. I had not the time to finish it yet. Should I push my not working code as a start?

**Comment by leits** [comment]
If it makes sense.
Would you have time to continue the development in the near future?

**Comment by jgoldhammer** [comment]
I am working on it right now :-)

**Comment by leits** [comment]
Cool! Thanks!

**Comment by jgoldhammer** [comment]
I have developed a first version. Please give your feedback @leits.
