### ISSUE TITLE
Feature: integration of other calendar apps, e.g. Fantastical

### ISSUE THREAD

**Issue by jetztgradnet** [leits/MeetingBar#185]
MeetingBar offers to open Calendar.app for any event. I use the great Fantastical calendar app, so I would appreciate an option to open the event in (this) other calendar app(s) as well, similar like it is done for the various video conferencing tools and browsers.

See here for the relevant URL scheme:
https://flexibits.com/fantastical/help/integration-with-other-apps

**Comment by jgoldhammer** [comment]
Hi, thanks for the suggestion. I have scanned through the documentation. It seems that it is not possible to show a specific event in Fantastical. So what is your expection when clicking on "Open in Fantastical"?

**Comment by jetztgradnet** [comment]
Thanks for considering this!

ONe option would be to open Fantastical at the specific day (which I think is possible). 

Maybe contacting them also opens more possibilities, but I'm not sure if you want to make that effort. So I will try to reach out to them and send a suggestion referring to this issue.

**Comment by jetztgradnet** [comment]
I contacted them, let's see if they are interested in expanding their integration capabilities.

**Comment by leits** [comment]
@jetztgradnet, thank you for the Idea and for contacting fantastical team!

**Comment by jetztgradnet** [comment]
Response from Flexibits (Fantastical):

> This should already be possible — we support to show an item by looking up a date and a title:
> 
>     fantastical://show?date=
>     Opens Fantastical and shows the specified date
>     Parameters:
>     Required: "date" ; the date to show.
>     Optional: "title" ; title of the item to show

So with this information it should be possible to at least open Fantastical on the appropriate date and with the title seelcting the right entry. The latter might be a bit flaky (e.g. if there are multiple entries with the same title), but should be close to what would be needed to open that in MeetingBar.

**Comment by leits** [comment]
Thanks, @jetztgradnet!

**Comment by jgoldhammer** [comment]
I have added a first version for this functionality in #200

**Comment by jgoldhammer** [comment]
@jetztgradnet - this feature will be released in the next version.

**Comment by jetztgradnet** [comment]
@jgoldhammer cool, looking forward to trying this. Thanks for taking the time to implement that!
