### ISSUE TITLE
Bug: Icon is sometimes blurry in General Preferences menu

### ISSUE THREAD

**Issue by jasonhan-vassar** [leits/MeetingBar#189]
**App version**
3.1.0 (App Store version)

**Describe the bug**
The MeetingBar icon in the Preferences General menu is sometimes blurry. This does not happen on the first opening of the app.

**To Reproduce**
1. If MeetingBar is open, quit it.
2. Launch MeetingBar.
3. Go to the MeetingBar Preferences and observe the icon in General. It should appear as normal.
4. Close the Preferences window and reopen it.
5. The icon should now appear blurry.

**Screenshots**

**Normal**
<img width="700" alt="Screen Shot 2021-02-15 at 6 18 46 PM" src="https://user-images.githubusercontent.com/34594853/108001403-5a07e880-6fba-11eb-937b-cb500f894564.png">

**Blurry**
<img width="700" alt="Screen Shot 2021-02-15 at 6 18 55 PM" src="https://user-images.githubusercontent.com/34594853/108001418-655b1400-6fba-11eb-88a2-4b1ab9280dfd.png">

**Desktop (please complete the following information):**
 - macOS version: 11.1

**Comment by leits** [comment]
Thanks for reporting, @jasonhan-vassar!

**Comment by jgoldhammer** [comment]
I will close this in favor of #192 - thanks for reporting. We will fix this issue.
