### ISSUE TITLE
Crash when joining event without a video link

### ISSUE THREAD

**Issue by brandenbyers** [leits/MeetingBar#19]
**Describe the bug**
When attempting to join a meeting without a video link, the app crashes consistently.

**To Reproduce**
1. Create a calendar event with no video link nor location.
2. Try to join the meeting via the menu bar app or keyboard shortcut.

**Expected behavior**
Do nothing, don't crash, and/or notify the user that the meeting cannot be joined.
**Desktop (please complete the following information):**
 - macOS version: 10.15.5

**Comment by leits** [comment]
Thanks!
I managed to reproduce it, the fix will be in the next release 👍

**Comment by leits** [comment]
@Niels-NTG Check the new release with bugfix:
https://github.com/leits/MeetingBar/releases/tag/v1.1
+
The app is available on homebrew now:
`brew cask install meetingbar`
