### ISSUE TITLE
Bug: Low-res icon and trimmed texts in About

### ISSUE THREAD

**Issue by igorkulman** [leits/MeetingBar#192]
**App version**
3.1.1

**Describe the bug**
I updated Meetingbar via homebrew and I wanted to check what version I got, so I went to the Preferences and could not see the version because of trimmed texts.

**To Reproduce**
1. Go to 'Preferences'
2. See the problem in the General section

**Expected behavior**
Name and version labels not trimmed so I can see the app version, high-res icon.

**Screenshots**
<img width="812" alt="Screen Shot 2021-02-19 at 10 08 51" src="https://user-images.githubusercontent.com/4746070/108483276-ccb6e380-729a-11eb-8282-7ae28c20679f.png">

**Desktop (please complete the following information):**
 - macOS version: 11.2

**Comment by leits** [comment]
Development on Catalina for Big Sur makes me crazy.

Thanks for the report, @igorkulman.
I'll fix it today.

**Comment by jgoldhammer** [comment]
I also have the low-res icon on Catalina...

![image](https://user-images.githubusercontent.com/3872101/108565234-9f9f1b00-7304-11eb-9ea8-bb88cdf308cd.png)

**Comment by leits** [comment]
Thanks to @yarsanich for validating the bugfix
![2021-02-20 00 46 09](https://user-images.githubusercontent.com/12017826/108573508-76d74f80-731d-11eb-9fbd-6c20d6d74d37.jpg)
