### ISSUE TITLE
Bug: MeetingBar does not sync with changes to Google Calendar timings or cancelled events 

### ISSUE THREAD

**Issue by jacklsmith** [leits/MeetingBar#195]
**App version**

3.1.2

**Describe the bug**

MeetingBar thinks an event is active or upcoming, despite it being moved to a totally different day or time in Google Calendar.

**To Reproduce**
1. Create a Google Meet event for a morning in 5 days time
2. 3 days later, change the timing to the afternoon
3. On the event day, it will show you the upcoming event in the morning, not afternoon

**Expected behavior**
MeetingBar updates the event timings soon after any changes, if not straight away

**Desktop (please complete the following information):**
 - macOS Big Sur 11.2.1

**Additional context**
Calendar is within a company g-suite.

**Comment by jgoldhammer** [comment]
Does restarting meetingbar helps here? How is the event displayed in macOS calendar? Under normal conditions meetingbar gets notified about event changes from eventkit and will update appointments.

**Comment by jgoldhammer** [comment]
Can you tell us more Jack? @jacklsmith

**Comment by jgoldhammer** [comment]
We will close the issue  due to inactivity - feel free to reopen with more details @jacklsmith

**Comment by JordanTranchina** [comment]
I'm seeing this error again where calendar events are still appearing on MeetingBar despite them being cancelled on MacOS Calendar for 5+mins and pressing refresh on both calendar and MeetingBar a few times. @jgoldhammer @leits 
![Screen Shot 2022-04-12 at 4 05 20 PM](https://user-images.githubusercontent.com/41443492/163054432-5ca0a127-4e89-4a23-a522-2d4028bb1590.png)

**Comment by JordanTranchina** [comment]
UPDATE: Restarting MeetingBar seems to have fixed this!
