### ISSUE TITLE
Don't show full day events as notification, only in dropdown is sufficient

### ISSUE THREAD

**Issue by durdevic** [leits/MeetingBar#2]
**Describe the solution you'd like**
Show the upcoming event that is at a certain time, not the full-day events. You can put a setting in preferences as "don't show full-day events from notification"

Feel free to contact me if I need to explain it better 👌

**Comment by leits** [comment]
@durdevic , good point 👍 
Check the latest release: https://github.com/leits/MeetingBar/releases/tag/v1.0b13

**Comment by durdevic** [comment]
Woah, that was fast! Nice 👌 

This was you probably xD
https://gph.is/2Qv5ZMJ

**Comment by leits** [comment]
Thanks! Is it work as expected?)

**Comment by durdevic** [comment]
Yep, it works pretty solid. 👌  You can close the ticket.

Random thing though, the app somehow disappeared from the notification bar once my computer went to sleep. I needed to start it again from the app menu.

I'll report it if it happens again

**Comment by leits** [comment]
Hmm. 
LaunchAtLogin feature currently in backlog, but I didn't think that the system stops the app when went to sleep.

**Comment by durdevic** [comment]
Okay, I've figured it out. I'll put in the new ticket
