### ISSUE TITLE
Feature: Report when the menuitem is not visible , e.g. macos decides to not show it #5

### ISSUE THREAD

**Issue by jgoldhammer** [leits/MeetingBar#203]
**App version**
current version
**Describe the bug**
When the macos systembar is full, the application is not shown. The user is confused and thinks that the application is not working.

**To Reproduce**

**Expected behavior**
the user should be informed when the status item disappears 

**Screenshots**

**Desktop (please complete the following information):**
 - macOS version: [e.g. 10.15.4]

**Additional context**
https://github.com/feedback-assistant/reports/issues/37

**Comment by jivimberg** [comment]
This happened to me and I was totally confused. Macs with notch might make this issue more noticeable.
I ended up shortening the meeting title to 30 characters, and that worked. 
The problem is that the only way to get to that configuration is by removing other icons until the Meeting Bar icon appears again.

**Comment by leits** [comment]
from @leits https://github.com/leits/MeetingBar/pull/435#issuecomment-1099623989:
> @jgoldhammer, the notification is also sent when you open any application in full screen. I spent a lot of time finding a way to check if the status bar is visible, but couldn't find any.
> 
> Do you also have this problem?

from @jgoldhammer https://github.com/leits/MeetingBar/pull/435#issuecomment-1101719542:
> I am now having a solution to detect if there is any app in fullscreen mode and do not trigger the notification when an app enters fullscreen. The downside is that meetingbar needs the screen recording permission under macos. I am little bit frustrated about this situation because macOS does not allow to get the information if there is any app in fullscreen without that permission.
> 
> ![image](https://user-images.githubusercontent.com/3872101/163868466-6333a13e-6691-4ddd-a050-755f90892318.png)
> 
> You can read more here: https://stackoverflow.com/a/66403010
> 
> What do you think, @leits, how to proceed here?

from @leits https://github.com/leits/MeetingBar/pull/435#issuecomment-1101772904:
> This is definitely not the permission that we want to ask the user.
> 
> Thank you for your research Jens! But let's suspend this feature and keep an eye on macOS updates.

**Comment by TipsByPullak** [comment]
As more people will start adopting Macbooks with notches soon, this issue can become more prevalent. Hope we are able to find some solution. 🤞🏻

**Comment by leits** [comment]
Sorry, there is no way to do it without permission for screen recording.
