### ISSUE TITLE
Bug: tooltip not updated when there are no upcoming meetings

### ISSUE THREAD

**Issue by luckman212** [leits/MeetingBar#204]
**App version** 3.1.2

**Describe the bug**
After a meeting has occurred, if there are no more upcoming meetings, the tooltip still displays the "ghost" of the last meeting.

**To Reproduce**
1. Have a meeting
2. Have no more meetings
3. Hover the mouse over the menubar icon

**Screenshots**
tooltip
![image](https://user-images.githubusercontent.com/1992842/110017461-3b149080-7cf4-11eb-8feb-d222fc0cf0ef.png)

menu- (that meeting does not exist...)
![image](https://user-images.githubusercontent.com/1992842/110017587-5ed7d680-7cf4-11eb-8c6b-4b7c379316c9.png)

**Desktop (please complete the following information):**
 - macOS version: 11.2.2

**Comment by jgoldhammer** [comment]
Thanks @luckman212 ! We will try to fix it in the next release.
