### ISSUE TITLE
Bug: Can't join zoom meetings from app directly

### ISSUE THREAD

**Issue by rfein-hearst** [leits/MeetingBar#208]
**App version**
3.1.2

**Describe the bug**
Can't join zoom meetings when "Open Zoom Links in Zoom App" is chosen.  If I have zoom open, nothing happens. If i don't have zoom open, it opens, but I'm signed out (and nothing happens)
**To Reproduce**
1. Set zoom meetings to open in the zoom app in Services preference tab.
2. Click on a zoom meeting.
3. Observe behaviors described above, meeting is not joined.   This happens whether the zoom link is password protected or not, whether it's in my iCloud calendar or my Outlook calendar. 

**Expected behavior**
meeting opens in zoom client. 

**Desktop (please complete the following information):**
 - macOS version:  11.2.2

**Comment by glenjamin** [comment]
I've been seeing this too, but inconsistently - it does seem to at least focus the Zoom application, but doesn't join the meeting.

Is there anything I can do to debug this?

**Comment by glenjamin** [comment]
I had a poke around in the code, this is the block which launches in the zoom app:
https://github.com/leits/MeetingBar/blob/4f869a4df80ee4d1700c40cfadcac099548cb699/MeetingBar/StatusBarItemControler.swift#L922-L930

Is there a good way to get the app to tell me / log what zoom URL it's parsed out and decided to try opening? Then when I see it fail to open I can inspect the URL it launched and see if I can tell what's up

**Comment by glenjamin** [comment]
Oh, I think I know what this might be - one of the meetings i'm joining is using an alias like `/my/alias-name`

**Comment by jgoldhammer** [comment]
It seems that zoom has deprecated client url schemes now.

![image](https://user-images.githubusercontent.com/3872101/116824450-a1018500-ab8a-11eb-978a-2dc6165cd355.png)
https://marketplace.zoom.us/docs/client-url-schemes

I am thinking about removing direct support as it seems that the app does not report back that it could not start the application successfully. WDYT @leits ?

**Comment by jgoldhammer** [comment]
Hi @glenjamin , 

can you provide me an example url of the my-urls? I can test locally if replacing `/my/` with` /join?confno=` will work as replacing ` /j/`. If this will work, I can enhance the logic. If not, we have to think about removing the feature completely when it does not work reliable...

Thanks
Jens

**Comment by leits** [comment]
@ubhaller, maybe you can help here ^?

**Comment by ubhaller** [comment]
@leits unfortunately i don't have a personal `/my` link and am hesitant to share one not belonging to me. judging by the conversation in https://github.com/leits/MeetingBar/issues/164 didn't @nevadascout share one with you?

as far as i can tell `/my` links redirect you to a regular `/j` link. so i suppose all you'd need to do is add a custom handling for `/my` links that fires a request and reads out the `location` header. from there you can work with the `/j` link as per usual (conversion to deep link -> open)

```
curl -i https://***.zoom.us/my/***

HTTP/2 302
date: Sat, 14 Aug 2021 09:36:53 GMT
content-length: 0
location: https://***.zoom.us/j/***
```

**Comment by leits** [comment]
Thanks, @ubhaller!
I would not like to add an external request to the app. We have a focus on privacy.

So I see only two options now:
- Your #258 fix to open all /my links in the browser
- Try to replace `/my/` with `/join?confno=` (like for `/j`) as @jgoldhammer proposes and look if it will work

So the first one it's just a workaround to make it work at least with the browser and the second one it's just an idea and we need to check it with a real `/my` link.

**Comment by leits** [comment]
And I think we start with the first option then try to use the second one.
