### ISSUE TITLE
Feature: Set default browser for any/all meetings

### ISSUE THREAD

**Issue by sammachin** [leits/MeetingBar#209]
I mostly use Vonage Meetings, but I'm having issues with that in my preferred browser (Firefox) so I need to use Chrome. I'd like to be able to set that MeetingBar opens all meeting links in Chrome rather than just being able to overide it for Zoom, Meet, Teams etc. 
Or even better the ability to set a handler for each supported type of meeting.

**Comment by jgoldhammer** [comment]
Hi @sammachin , 

Thanks for your idea. I am currently rewrite the browser management in Meetingbar. This is indeed part of my current implementation to choose a default browser for all meetings. Would you think it would be necessary to be able to define the browser per meeting service?

**Comment by sammachin** [comment]
I think having a default browser for all meetings but then maybe some sort of advanced mode that lets you match a regex pattern to any applicaiton on the system as a handler would be good

**Comment by jgoldhammer** [comment]
From enduser perspective regexs will be hard to sell - I guess it would be nice to let users configure a browser for each meeting service. What do you think, @leits ?

**Comment by leits** [comment]
Agreed
