### ISSUE TITLE
Time to next meeting does not round

### ISSUE THREAD

**Issue by Thomas-Stewart** [leits/MeetingBar#21]
**Describe the bug**
If there is 1 hour and 59 minutes until my next meeting, the meeting bar will read "in 1 hour".

**Expected behavior**
The time will round to the nearest hour or show minutes

**Desktop (please complete the following information):**
 - macOS version: 10.15.3

**Additional context**
Maybe this is expected behavior? But it keeps fooling me into thinking my meetings are much sooner than they are.

**Comment by leits** [comment]
Hi, Thomas. Thanks for report!
Please, check the latest version, it changes the display to "1 hour and 59 minutes" instead of "1 hour".
