### ISSUE TITLE
Bug: MeetingBar does not appear in "System Preferences, Notifications"

### ISSUE THREAD

**Issue by PeterWhittaker** [leits/MeetingBar#210]
**App version**
3.1.2 (installed via `brew` as per instructions in README).

**Describe the bug**
MeetingBar tells me to enable its notifications in System Preferences, but it does not appear in the list of apps.

**To Reproduce**
1. Go to `System Preferences`
2. Click on `Notifications`
3. Scroll as much as you like
4. MeetingBar does not appear

**Expected behavior**
MeetingBar should appear, as per MeetingBar notice in MeetingBar Preferences

**Desktop (please complete the following information):**
 - macOS version: 11.2.2

**Comment by jgoldhammer** [comment]
Hi Peter,

thanks for your bug report. I guess that this problem does not relate to the app meetingbar, but to the notification center of MacOS. Please keep in mind that this list is generated by macos and we do not actively can register the app meetingbar here.
For example, as a macos user you are able to delete apps from the notification center by selecting an entry and click delete. Sometimes the list contains two entries for one app or even no entry for an app. 

To completely regenerate the list of apps in the notification center, please look for the database (it is sqllite database), make a backup and let macos regenerate it.

This bash command will help to find the database:

`lsof -p $(ps aux | grep -m1 usernoted | awk '{ print $2 }')| awk '{ print $9 }' | grep 'db2/db$' | xargs dirname`

For more help see this thread https://apple.stackexchange.com/a/142811 to regenerate the database.
So I will close the ticket for now as we cannot actively do something here.

**Comment by PeterWhittaker** [comment]
@jgoldhammer Thanks for the info. I'd recommend adding that to the README.

I was going to test this procedure, but, with a weekend away from the computer, Mac OS and MeetingBar caught up with each other - if I get a chance, I will install MeetingBar on my other Mac and see if that works.

FYI, `dirname $(lsof -p $(pgrep usernoted)|awk '/db2\/db$/ {print $9}')` is arguably a bit more efficient for finding the DB folder (one `pgrep` Vs one `ps` + one `grep` + one `awk`; one `awk` Vs `awk`+ `grep`; no real need for `xargs`, there should be but a single a argument as a result). Of course, TETO and YMMV! Thanks again.
