### ISSUE TITLE
Feature: Add "Create meeting in other app..." (renaming Create meeting to Create meeting in <default app>"

### ISSUE THREAD

**Issue by PeterWhittaker** [leits/MeetingBar#211]
**Is your feature request related to a problem? Please describe.**
`Create meeting` defaults to the default app (Teams in my case). Most of the time, this is correct, but not always. It would be good to be able to Create a meeting in another calendar.

**Describe the solution you'd like**
Rename "Create meeting" to "Creating meeting in <"default app>", replacing "default app" appropriately, and add "Create meeting in other app..." which would have a menu of enabled accounts/apps, e.g., Zoom, Google, etc.

*NOTE*: Google should allow me to pick the calendar in which the meeting is being created.

**Describe alternatives you've considered**
n/a, I don't think. Other than not using MeetingBar for this.

**Additional context**
n/a, I don't think.

**Comment by leits** [comment]
Thanks for the request.

It's interesting, but it's a very specific implicit case. Also, it hasn't found any support from other users since creation, so I'm going to close it. Sorry!

**Comment by PeterWhittaker** [comment]
No worries, no need to apologize. But I don't understand why it is a *specific implicit case*? Anyone with multiple scheduling applications is going to run into this. I've gotten used to working around the limitation, so not having it won't change anything, just trying to understand how it isn't a generally useful capability. Thanks!
