### ISSUE TITLE
Bug: Some calendars not appearing - RO issue?

### ISSUE THREAD

**Issue by PeterWhittaker** [leits/MeetingBar#212]
**App version**
3.1.2

**Describe the bug**
Not all of the calendars visible in Calendar appear in MeetingBar - it may be related to the permissions I have on those calendars (in Calendar, Preferences, Delegation, all of the excluded calendars are read-only).

**To Reproduce**
1. Go to 'Calendar, Preferences, Account Information', enable a specific account
2. Go to 'Calendar, Preferences, Delegation', select a variety of calendars
3. In MeetingBar, only the RW calendars appear 

**Expected behavior**
RO calendars should appear as well: There are valid reasons why I cannot edit these. For example, they may be my calendar, but owned by another organization. I still need to be able to see them.

**Desktop (please complete the following information):**
 - macOS version: 11.2.2

**Comment by leits** [comment]
Thanks for the report, @PeterWhittaker.

I found that the EKEventStore API we use doesn't return the calendars from delegated sources by default, but there is a way to change it.
ref: https://developer.apple.com/documentation/eventkit/ekeventstore/1507419-delegatesources

**Comment by jgoldhammer** [comment]
Do you think we can extend that in the codebase? 
How to test that with a free googlemail account?

**Comment by jgoldhammer** [comment]
I have implemented a first version. We have to further test this. All calendars are now displayed in the preferences dialog.
