### ISSUE TITLE
Not all the events for the day are shown in meeting bar

### ISSUE THREAD

**Issue by lorenzonucaro** [leits/MeetingBar#213]
**App version**
3.1.2

**Describe the bug**
Not all of the events visible in my Calendar appear in MeetingBar. This issue started with the last update of meetingbar

**Desktop (please complete the following information):**
macOS version: 11.2.3

**Comment by leits** [comment]
Hi, @lorenzonucaro. Thanks for the report!

Could you please check the event section in the Appearance tab in Preferences?
If everything selected for show then please check the macOS Calendar app, if there are the events are you looking for?

**Comment by jgoldhammer** [comment]
Hi @lorenzonucaro ,

sorry, but I will close the ticket for now due to a missing response. Feel free to reopen the ticket with more information, steps to reproduce and maybe some screenshots.

Thanks
Jens
