### ISSUE TITLE
Bug: The preferences has a “⚠️ Your macOS notification settings..” even though notifications for MeetingBar are enabled.

### ISSUE THREAD

**Issue by leits** [leits/MeetingBar#219]
*from email*

Maybe it's because we only check for an Authorized state without taking Provisional or Ephemeral into account. 
https://github.com/leits/MeetingBar/blob/fd58e69906447d6724b3edeef7eb26c63a7814c7/MeetingBar/Views/Shared.swift#L27

**Comment by AlexanderWillner** [comment]
I think the check doesn't work on macOS 12.5 (21G72) and also isn't presented well:

<img width="812" alt="image" src="https://user-images.githubusercontent.com/307605/183850745-d720b419-230e-4051-b72f-13d8459d6190.png">

**Comment by jgoldhammer** [comment]
Hi, this is no real issue. You have only enabled "banners". The hint in the app says to enable "alerts" to not miss any meeting.
