### ISSUE TITLE
Duplicate calendars selected if name conflict exists

### ISSUE THREAD

**Issue by patmigliaccio** [leits/MeetingBar#22]
**Describe the bug**
Selection of a calendar that has a calendar with the same name in the listing is selecting both and displaying duplicate events in the meeting bar listing.

Related to #4 

**To Reproduce**
1. Go to 'Preferences'
2. Click on 'Calendars'
3. Select a calendar that has the same name as another calendar
4. See issue
5. Observe duplicate events in "Today events" listing

**Expected behavior**
On selection, it should be unique to the email account and not select multiple of the same calendar.

**Screenshots**
![Duplicate "Contacts" calendar](https://i.ibb.co/dbWL3C0/Screen-Shot-2020-06-16-at-8-43-43-AM.png)

**Desktop:**
 - macOS version: 10.15.4

**Comment by leits** [comment]
@patmigliaccio check the new 1.3 version!

**Comment by patmigliaccio** [comment]
Excellent. Works great!
