### ISSUE TITLE
Feature: Add other browsers as options for Zoom and Teams meetings

### ISSUE THREAD

**Issue by leits** [leits/MeetingBar#220]
*from email*

> I don’t use the Zoom app due to privacy/security concerns. I would love to set a custom browser in addition to the "Default Browser" just like how you are able to with Meet links.

I think it makes sense and for Teams meetings too.

**Comment by dcyoung-dev** [comment]
This would be a good addition to Teams meeting too. Firefox and Teams have issues and it would be nice to open Teams links in Chrome even though default browser is Firefox 👌
