### ISSUE TITLE
Feature: Limit width of submenu items

### ISSUE THREAD

**Issue by mdbraber** [leits/MeetingBar#221]
**Is your feature request related to a problem? Please describe.**
It seems that newlines are non-existent or ignored in notes field which therefore become extremely wide as submenu items. It would be great if there would be a max width to the submenu items.

**Describe the solution you'd like**
Max width for submenu items (either configurable or hardcoded)

**Describe alternatives you've considered**
Turning of the submenu items works, but does not allow access to relevant information

**Comment by 2Grey** [comment]
Check out PR [#266](https://github.com/leits/MeetingBar/pull/226)

**Comment by jgoldhammer** [comment]
Thanks @2Grey !
