### ISSUE TITLE
Bug: Stops progressing time after running for a bit

### ISSUE THREAD

**Issue by defrex** [leits/MeetingBar#225]
**App version**
3.2.1

**Describe the bug**
When I launch MeetingBar, it seems to work fine. However, usually after an hour or two, it stops moving forward in time.

You can see in the screenshot below: MeetingBar thinks it's ~10:45a when it's actually 4:31p.

**To Reproduce**
1. Start MeetingBar
2. Wait...
3. ???
4. MeetingBar stops working

**Expected behavior**
Keep telling me about new meetings.

**Screenshots**
<img width="701" alt="Screen Shot 2021-03-24 at 4 31 49 PM" src="https://user-images.githubusercontent.com/57580/112379779-f363a200-8cbe-11eb-876c-42892319e142.png">

**Desktop (please complete the following information):**
macOS Big Sur 11.2.1

**Comment by leits** [comment]
Thanks for the report, @defrex!
It actually duplicates #181, please follow the last one.
