### ISSUE TITLE
Bug: Preferences UI sometimes incorrectly displays over itself when switching away from "Calendar" tab

### ISSUE THREAD

**Issue by ccarterlandis** [leits/MeetingBar#227]
**App version**
3.1.2

**Describe the bug**
When clicking between the various sections of the preferences menu, sometimes when a user has "Calendar" selected and then selects another section, the Calendar section will not disappear/be erased before the new is drawn, so they end up rendering on top of each other making both unreadable. I recommend watching the attached video and then reading the rest of this section; you can see the bug start about 3 seconds in, and stops at about 19 seconds in.

So far, I have not found a consistent set up of sections to switch to in order to cause this to occur; however, it does seem to always be the Calendar section that is stuck "underneath" the new one. It also seems to be triggering at random - I haven't figured out if there are certain sequences of other actions that trigger this bug (other than just clicking around until it happens), and equally odd is the fact that the bug seems to stop happening at random also; that is, there's not a certain sequence or action I have found that will return the UI to normal, other than just continuing to click wildly. 

I have noticed it happening after spending varying lengths of time on a section before switching, i.e. it doesn't matter how fast you're switching between them. 

**To Reproduce**
1. Go to Preferences
2. Click on any section
3. Start clicking between the sections
4. See error (occasionally)

**Expected behavior**
I would expect to only see the UI for the tab I've selected.

**Screenshots**
Hopefully this video helps explain the issue - it's a bit difficult to put into words.
https://user-images.githubusercontent.com/31522931/112699416-c26ba480-8e59-11eb-9652-6b9e5b6c0385.mov

**Desktop (please complete the following information):**
 - macOS version: 10.15.7

**Additional context**
Sorry I can't provide a more reproducible set of steps, it really does seem random to me. If I do notice a pattern I'll be sure to update this issue, and while I'd love to help fix this, I don't know any Swift. Please let me know if there is more info you need, overall I really like this app and I've found it really useful. Thanks!

EDIT: I forgot to add that this is currently happening on my work laptop. I strongly doubt that there it's something to do with that that's causing this issue, but it's probably worth mentioning anyways. I have not installed this on my personal laptop, so I'm not sure if it also happens there.

**Comment by jgoldhammer** [comment]
Thanks for the report. I have seen that too while running in debug mode. I always thought it was related to the non productive mode.

**Comment by ccarterlandis** [comment]
@jgoldhammer maybe I'm also running in debug mode? I don't think I am, as I don't remember ever setting anything like that, and I don't see anything in the UI that would indicate I'm in debug mode - but maybe I just missed it. Glad to hear it's not just me though.

**Comment by leits** [comment]
Thanks for the report, @ccarterlandis. Yes, I saw it too.
It's a bug in swift UI, and it looks like it has already been fixed with updates.
