### ISSUE TITLE
Meeting says "in 1 hour" when it's actually 1 hour + 55 minutes away

### ISSUE THREAD

**Issue by maxanstey** [leits/MeetingBar#23]
**Describe the bug**

It's 08:05am and I have a meeting at 10am. The bar says "<meeting name> in 1 hour"

**To Reproduce**

1. Create a meeting entry
Observe that when it is closer to 2 hours away, the bar says 1 hour away

**Expected behavior**

If rounding down, it should say something like "in less than 2 hours" rather than just "in 1 hour"

**Screenshots**

![Screenshot 2020-06-17 at 08 07 30](https://user-images.githubusercontent.com/26803203/84866418-996be700-b071-11ea-841b-0142bec2daf4.png)

**Desktop (please complete the following information):**
 - macOS version: 10.15.3

**Additional context**

Thanks for your help.

**Comment by leits** [comment]
Hi, @maxanstey. Thanks for the report.
What version are you using? I fixed this in 1.1 release.
Check it out!

**Comment by maxanstey** [comment]
Sorry @leits , I was on 1.0b14 -- I've upgraded now and will presume it's fixed. I won't know until tomorrow, but I trust you! Sorry again for not updating first. Thanks

**Comment by leits** [comment]
All right, I'm happy to help!
