### ISSUE TITLE
Feature: Zoom Webinars links support

### ISSUE THREAD

**Issue by leits** [leits/MeetingBar#232]
Zoom Webinars links usually look like this:
`https://<custom-domain>.zoom.us/webinar/register/<webinar-id>`

ref: https://github.com/leits/MeetingBar/discussions/108#discussioncomment-577092

**Comment by 2Grey** [comment]
Is that regex correct?
`https?:\/\/(?:[a-z0-9\-\.]+)?zoom.(?:us|com.cn)\/webinar\/register\/.[0-9a-zA-Z?=\-\.]*`

**Comment by jgoldhammer** [comment]
@leits - I am not really sure that this link is the correct JOIN link - it looks like a registration link which is important to register for the webinar, but I think not for joining directly...

**Comment by r2a1** [comment]
Hi, I've been having this problem. Here's the template:

https://<custom-domain>.zoom.us/w/<webinar-id>

Here's an actual link that has expired:

https://us04web.zoom.us/w/93122439654?tk=Dod7vSSUVfFaSd3ushA4v7QSjeDktMOmClh2bTMYALo.DQIAAAAVroep5hZxLS1CMTNJMlJFV045N2pWNGNDLXlnAAAAAAAAAAAAAAAAAAAAAAAAAAAA&pwd=RHBtRXZCWmNENDRZdEdKdjA3WDhlQT09&uuid=WN_cJ_6hP8qSoKhKIjwsj05_Q

**Comment by dserodio** [comment]
This is not working for me with URLs like https://us06web.zoom.us/webinar/register/REDACTED_ID

**Comment by r2a1** [comment]
That is a registration link and would not work. You need the link after you have registered.

**Comment by dserodio** [comment]
@2Grey besides letters, numbers and dashes, it also contains an underline.

**Comment by dserodio** [comment]
> That is a registration link and would not work. You need the link after you have registered.

The Google Meet invites to our company's webinars always contain the registration link, and when I click in this link I have to confirm my participation in a web page, and then the webinar automatically opens in Zoom. Would it be possible to parse the registration URLs to support this workflow?
