### ISSUE TITLE
Feature: Allow configuration of Mouse Clicks

### ISSUE THREAD

**Issue by petems** [leits/MeetingBar#235]
**Is your feature request related to a problem? Please describe.**
I'm super used to Right Click for config, left click to open, but those are flipped for MeetingBar.

**Describe the solution you'd like**
Allow setting click behavior for upcoming meetings.

**Describe alternatives you've considered**
None for now, it's just a personal preference. 

**Additional context**
Thanks for the great app! I've loved it 😄

**Comment by leits** [comment]
Hi, @petems.
Thanks for your request. I think about this a lot.

I don't think other users really need them. 
The app should be simple and clear in the settings for everyone, not just for fans of fine-tuning.
Opening the menu by left-clicking is common to all macOS status bar apps and this additional setting is redundant.

Sorry.
