### ISSUE TITLE
Feature: Compose email to all attendees (quick action)

### ISSUE THREAD

**Issue by leits** [leits/MeetingBar#239]
Add quick action to compose an email with all participants from current/next event to let them know that you're running late.

ref: https://twitter.com/ahiggz/status/1382042505575759874?s=20

**Comment by jgoldhammer** [comment]
I really like this feature. Should we add this for each calendar entry in the submenu for this entry besides "Open in calendar"? WDYT?

**Comment by leits** [comment]
I see two more opportunities for this feature.
The first is to add an option to the notification.
Second - to add this to the "quick action" we are planning.

**Comment by jgoldhammer** [comment]
How do you think to design quick actions? the menubar is very limited. Should we add a seperate statusbar icon to click on which brings up a complete new view or how do you want to integrate it? Ideas so far?

**Comment by leits** [comment]
Added as event action:
https://github.com/leits/MeetingBar/commit/857053b0d02d6574a317dabee9e053a7a8345486
