### ISSUE TITLE
Increase the artificial limit on "show only next event starting within XX" option?

### ISSUE THREAD

**Issue by luckman212** [leits/MeetingBar#245]
This stepper only goes up to 120m
![image](https://user-images.githubusercontent.com/1992842/115151838-a57f5700-a03c-11eb-921e-1907ebdd9281.png)

For me 2hrs is not enough, I would like to look ahead 4h... some people might want 6, 8 etc...

I suggest changing upper bounds of `showEventMaxTimeUntilEventThreshold` to **720** (12 hours):

https://github.com/leits/MeetingBar/blob/8a86c8047e18b576f1f1ced2da8318ca9f9699f5/MeetingBar/Views/Preferences/AppearanceTab.swift#L92

eg
```swift
Stepper("preferences_appearance_status_bar_next_event".loco(showEventMaxTimeUntilEventThreshold), value: $showEventMaxTimeUntilEventThreshold, in: 5...720, step: 5)
```

🙏

**Comment by leits** [comment]
Thanks, @luckman212!
You did almost everything yourself with this detailed description! 😄
