### ISSUE TITLE
Bug:  meetingbar sometimes exiting from toolbar

### ISSUE THREAD

**Issue by maxout123** [leits/MeetingBar#247]
**App version**
3.2.1

**Describe the bug**
Meetingbar exiting from toolbar from time to time
This happens 1-2 times a day.
If teams meeting is going on, it will happen more probably.
When Teams meeting is going, I even can not launch Meetingbar, as it's exiting immediately every time I launching it with ~80% probability.

**To Reproduce**
Just launch and wait

**Expected behavior**
Stay running in the toolbar

**Desktop (please complete the following information):**
 - macOS version: 10.15.7

**Additional context**
Console crash reports are attached
[MeetingBar_2021-04-12-124547_mow-mbp-20-3828.crash.txt](https://github.com/leits/MeetingBar/files/6335075/MeetingBar_2021-04-12-124547_mow-mbp-20-3828.crash.txt)
[MeetingBar_2021-04-19-164234_mow-mbp-20-3828.crash.txt](https://github.com/leits/MeetingBar/files/6335076/MeetingBar_2021-04-19-164234_mow-mbp-20-3828.crash.txt)
[MeetingBar_2021-04-12-155159_mow-mbp-20-3828.crash.txt](https://github.com/leits/MeetingBar/files/6335077/MeetingBar_2021-04-12-155159_mow-mbp-20-3828.crash.txt)
[MeetingBar_2021-04-12-155433_mow-mbp-20-3828.crash.txt](https://github.com/leits/MeetingBar/files/6335078/MeetingBar_2021-04-12-155433_mow-mbp-20-3828.crash.txt)
[MeetingBar_2021-04-12-163045_mow-mbp-20-3828.crash.txt](https://github.com/leits/MeetingBar/files/6335080/MeetingBar_2021-04-12-163045_mow-mbp-20-3828.crash.txt)
[MeetingBar_2021-04-19-163539_mow-mbp-20-3828.crash.txt](https://github.com/leits/MeetingBar/files/6335081/MeetingBar_2021-04-19-163539_mow-mbp-20-3828.crash.txt)
[MeetingBar_2021-04-19-161741_mow-mbp-20-3828.crash.txt](https://github.com/leits/MeetingBar/files/6335082/MeetingBar_2021-04-19-161741_mow-mbp-20-3828.crash.txt)
[MeetingBar_2021-04-19-135031-1_mow-mbp-20-3828.crash.txt](https://github.com/leits/MeetingBar/files/6335083/MeetingBar_2021-04-19-135031-1_mow-mbp-20-3828.crash.txt)
[MeetingBar_2021-04-19-135031_mow-mbp-20-3828.crash.txt](https://github.com/leits/MeetingBar/files/6335085/MeetingBar_2021-04-19-135031_mow-mbp-20-3828.crash.txt)
[MeetingBar_2021-04-18-022313_mow-mbp-20-3828.crash.txt](https://github.com/leits/MeetingBar/files/6335086/MeetingBar_2021-04-18-022313_mow-mbp-20-3828.crash.txt)
[MeetingBar_2021-04-19-163539-1_mow-mbp-20-3828.crash.txt](https://github.com/leits/MeetingBar/files/6335088/MeetingBar_2021-04-19-163539-1_mow-mbp-20-3828.crash.txt)
[MeetingBar_2021-04-19-163539-2_mow-mbp-20-3828.crash.txt](https://github.com/leits/MeetingBar/files/6335090/MeetingBar_2021-04-19-163539-2_mow-mbp-20-3828.crash.txt)
[MeetingBar_2021-04-19-163539-3_mow-mbp-20-3828.crash.txt](https://github.com/leits/MeetingBar/files/6335091/MeetingBar_2021-04-19-163539-3_mow-mbp-20-3828.crash.txt)

**Comment by maxout123** [comment]
One addition: it has started after update to 3.2.1 or one of the nearest previous versions.
Meetingbar worked like a charm before that.

**Comment by leits** [comment]
Thanks for the report, @maxout123!

**Comment by leits** [comment]
@maxout123, please, check the latest version.
It fixed a similar issue: #251

**Comment by maxout123** [comment]
@leits thank you so much, it works smooth and stable now!
