### ISSUE TITLE
Feature: Focus on next event when open menu with shortcut

### ISSUE THREAD

**Issue by leits** [leits/MeetingBar#248]
When opening via shortcut, users often select the desired meeting and join via enter.
Set a focus on the next meeting to make this process faster and more convenient.

**Comment by jgoldhammer** [comment]
Hmm, I am not completely coninved.

We have a direct shortcut for opening the next event? 
Additionally you can right click on the status bar and you can join the event with a simple click.
Do you think this would be enough?

From a technical perspective- how to focus the menu entry? If you have the mouse in a specific area, you would hover over a specific meeting, right?

**Comment by lilyball** [comment]
A solution this could be to assign the "Join next event meeting" menu item a keyboard shortcut. That way I can open the menu and then press the shortcut.

The problem with the direct shortcut is it means reserving yet another global shortcut.

We could even go a step further and assign ⌘1/2/3/…/0 to the next 10 meetings, so I can select any of them without leaving the keyboard.

**Comment by leits** [comment]
Valid remark, @jgoldhammer. And thanks for the idea, @lilyball.

I think it's too complicated for such a minor feature.
