### ISSUE TITLE
Meetings are always created in Google Meet

### ISSUE THREAD

**Issue by rubenamorim** [leits/MeetingBar#25]
**Describe the bug**
Whenever I tried to create a meeting, it's always created in Google Meet, even changing the preferences for Zoom.

**To Reproduce**
1. Go to 'Preferences'
2. Select create meetings in 'Zoom'
3. Close preferences
4. Click on 'Create meeting'
5. The app creates a meeting in Google Meet.

**Expected behavior**
The app creates a meeting in Zoom.

**Desktop:**
 - macOS version: 10.15.5

Also, thanks for this amazing utility 🙏

**Comment by leits** [comment]
@rubenamorim Thanks for the bug report! I'm going to fix this in the next release!

**Comment by leits** [comment]
@rubenamorim check the new 1.3 version!

**Comment by rubenamorim** [comment]
It seems to be fixed, so I will close this issue 🚀
Thank you 🙏
