### ISSUE TITLE
Bug: MeetingBar stops updating schedule

### ISSUE THREAD

**Issue by ndharani** [leits/MeetingBar#250]
**App version 3.2.1**

**Describe the bug**
MeetingBar stops updating the Google Calendar schedule. This might be related to when there is an upstream change in the calendar (moving an upcoming or current meeting to the future). For the rest of the day, MeetingBar shows "MeetingThatWasMoved in 12 minutes". (12 minutes represents the amount of time left before the start of the meeting at the time that MeetingBar stopped updating)

**To Reproduce**
1. Sync Google calendar
2. Move a meeting that is starting soon
3. Note that the schedule no longer updates

**Expected behavior**
After a meeting is moved, MeetingBar should know that the schedule was updated and reflect those changes in the MeetingBar

**Desktop (please complete the following information):**
 - macOS version: 11.1

**Comment by leits** [comment]
Hi, @ndharani. Thanks for the report!
There is already the same, so I will close this one.
https://github.com/leits/MeetingBar/issues/181
Will be fixed in the next release!

**Comment by ndharani** [comment]
Thanks!
