### ISSUE TITLE
Feature: Handle events that last more then 23 hours also all day events

### ISSUE THREAD

**Issue by dennis-bell** [leits/MeetingBar#253]
**Is your feature request related to a problem? Please describe.**
Although MeetingBar support filtering all day events, there are managers that dont fully understand how all day events work and still book from 0 to 23.59 :(
And its not being filtered as an all day event.

**Describe the solution you'd like**
Could there be added events longer then 23 hours also to handle as all day events.
Or even make the duration configurable?

**Describe alternatives you've considered**
Have been chasing managers to change the events! ;-)

**Comment by jgoldhammer** [comment]
Hi Dennis,

we will release feature #241 soon. I hope, this will help you to get these events filtered. 
If not, please describe more why these events should get filtered. Please reopen the issue then.

Thanks
Jens
