### ISSUE TITLE
Bug: Join next meeting, for a 15 minute meeting

### ISSUE THREAD

**Issue by AdeelK93** [leits/MeetingBar#257]
**App version** 3.2.2

**Describe the bug**
Love this app, very helpful, use it all the time.

I have meetings, on some days, every 15 mins. If I try to join this meeting using the `Join next event meeting` shortcut even a few seconds after it starts, I join my next next meeting (joining the 10:00 meeting at 9:45, when I want to join the 9:45 meeting).

I *think* the problem comes from here: https://github.com/leits/MeetingBar/blob/master/MeetingBar/Extensions/EventStore.swift#L116

The comment defines soon as `in the next 10 minutes`, but instead the code uses 900 seconds, or 15 minutes. Any chance we could change to code to 600 seconds? To support people like me with meetings every 15 mins.

Thanks!

**Desktop (please complete the following information):**
 - macOS version: 10.15.7

**Comment by leits** [comment]
Thanks for the issue, @AdeelK93!

Some time ago we up the visibility threshold to 15 min from 10 min.
But it makes sense to change it to maybe 13 minutes, WDYT?

**Comment by AdeelK93** [comment]
13 minutes would be great, thank you!
