### ISSUE TITLE
Crash on the start of the app in case when try to parse the name of the attendee

### ISSUE THREAD

**Issue by hamsternik** [leits/MeetingBar#26]
**Describe the bug**
The journey started from the moment when I have tried to run the app (previously downloaded from via the Brew) multiple times but didn't see any response reaction on the basic action. That leaded me to download the app from the repo and figure out the issue manually. 

So, when I have cloned the repo and run the app, I saw that it crashed at the StatusBarItemControler.swift, line 249 with the next error

> Fatal error: Unexpectedly found nil while unwrapping an Optional value: file: /Users/hamsternik/Developer/MeetingBar/MeetingBar/StatusBarItemControler.swift, line 249

More details you can see at the screenshot which I've attached below as well.

**To Reproduce**
1. Download the latest source code from the `master` branch. I have tested on the 7942088
2. Open the app in the latest stable Xcode version. I have used Xcode 11.5 stable.
3. Run the app as a developer.
4. The app crashed down when trying to unwrap the optional value `attendee.name`. More details with my specific context I provide at the _describe the bug_ section above.

**Expected behavior**
The app should run and works as expected, i.e. without any crashes.
**Screenshots**
<img width="2032" alt="Screenshot 2020-06-26 at 19 54 48" src="https://user-images.githubusercontent.com/4441804/85881812-e88ae800-b7e6-11ea-8337-28455cf26bac.png">

**Desktop (please complete the following information):**
 - macOS version: 10.15.5 (19F101)

**Comment by leits** [comment]
@hamsternik Thanks for so detailed bug report! I going to fix it tomorrow and publish a new release!

**Comment by leits** [comment]
@hamsternik sorry for delay. Check the new 1.3 version!

**Comment by hamsternik** [comment]
> @hamsternik sorry for delay. Check the new 1.3 version!

Thanks for you response, will check it!
