### ISSUE TITLE
Feature: "Join next event meeting" should say "Join current …" during a meeting

### ISSUE THREAD

**Issue by lilyball** [leits/MeetingBar#261]
**Is your feature request related to a problem? Please describe.**
When I open the menu, "Join next event meeting" is sitting there, tempting me to select it, but if I'm in the middle of a meeting, it's not clear if it's going to join my current one, or join the one right after.

**Describe the solution you'd like**
During a meeting, the menu title should say "Join current event meeting" instead to signal that it will join the current one.

Even nicer would be to add an alternate item (e.g. by holding Option) that switches it back to "Join next event meeting" and have it actually join the one after the current one. This way if my current one ended early I can get in the next one now.

**Describe alternatives you've considered**
Instead of this wording, it could just be explicit, e.g. 'Join "Live Code Review"'. This would also help disambiguate in the case where I have two overlapping video calls (I have no idea what happens today in that scenario, thankfully I haven't run into this case yet).

**Comment by jgoldhammer** [comment]
Thanks. Nice idea. @leits - wdyt?

**Comment by leits** [comment]
Yes, I think it makes sence.
