### ISSUE TITLE
Bug: Open Meeting from Clipboard ignores browser preferences

### ISSUE THREAD

**Issue by roger-o3h** [leits/MeetingBar#262]
**App version**
3.3.0

**Describe the bug**
When opening a meeting link from the clipboard, it opens in my system default browser instead of the one I have configured in MeetingBar.

**To Reproduce**
If your default browser is A:
Set your "All meetings links in" browser to B; set your "Open Meet meetings in" browser to B.
Copy a Meet invite to the clipboard.
Click "Open Meeting from Clipboard".
Meeting opens in default browser A.

**Expected behavior**
Meeting opens in configured browser B.

**Screenshots**
<img width="812" alt="Screen Shot 2021-05-05 at 10 04 42 AM" src="https://user-images.githubusercontent.com/68865657/117180723-56019080-ad89-11eb-8732-1204c003401d.png">
In this case, Meet meetings are opened in Safari not Chrome.

**Desktop (please complete the following information):**
 - macOS version: 10.15.7

Happy to provide any debugging or additional info. Thank you!

**Comment by leits** [comment]
Thanks, @roger-o3h!
Added fix to the next release!
