### ISSUE TITLE
Raw value in drop-down on Appearance tab of Preferences

### ISSUE THREAD

**Issue by hughlilly** [leits/MeetingBar#264]
Hi,

I believe I've discovered a bug that displays a raw value instead of a label in a drop-down on the Appearance tab of Preferences on v. 3.3.0:
<img width="1008" alt="Screen Shot 2021-05-07 at 1 49 31 PM" src="https://user-images.githubusercontent.com/12046008/117387201-7a519e80-af3c-11eb-8dfb-617b8ed0adc3.png">

~~I'm not a Swift developer so I'm not sure, but [line 165 of AppearanceTab.swift](https://github.com/leits/MeetingBar/blob/a48ee0c59eef6f626a05927bd9f9321a8af5446e/MeetingBar/Views/Preferences/AppearanceTab.swift#L165) may be the culprit.~~

Edit: perhaps the problem is at [L76 of /Resources /Localization /en.lproj/Localizable.strings](https://github.com/leits/MeetingBar/blob/a48ee0c59eef6f626a05927bd9f9321a8af5446e/MeetingBar/Resources%20/Localization%20/en.lproj/Localizable.strings#L76)? This is currently:
`"preferences_appearance_events_value_hide_without_link" = "hide all without any link";`
but perhaps it should be:
`"preferences_appearance_events_value_hide_without_meeting_link" = "hide all without any link";
`
Thanks
Hugh

**Comment by leits** [comment]
Thanks, fixed!
