### ISSUE TITLE
Feature: Dismiss "event starting soon" notification after event ends

### ISSUE THREAD

**Issue by lilyball** [leits/MeetingBar#266]
**Is your feature request related to a problem? Please describe.**
I just woke up my computer to find a "Meeting about to start" notification for an event that ended half an hour ago.

**Describe the solution you'd like**
I would like MeetingBar to dismiss these notifications after the event ends. This should probably be a preference.

**Comment by lilyball** [comment]
Actually I filed this as a feature, but really, it should probably be a bug.

**Comment by lilyball** [comment]
I don't know if there's any way to schedule an automatic dismissal, I don't see anything obvious when looking at the `UNNotificationRequest` API, but it would be nice if there is a way (what happens if you schedule a notification with the same identifier but leave all properties blank?)

**Comment by leits** [comment]
Thanks for the request, @lilyball!
It's a good point!

**Comment by jgoldhammer** [comment]
Hi @leits ,

would that change close all notifications? I guess if you have several events in the same timeframe it would hide all of these notifications, right?

**Comment by leits** [comment]
@jgoldhammer 
Yes, all notifications. But only when there is no current or next event.
