### ISSUE TITLE
Feature: Dismiss notification on all computers when I dismiss it on one

### ISSUE THREAD

**Issue by lilyball** [leits/MeetingBar#267]
**Is your feature request related to a problem? Please describe.**
I have multiple computers that run MeetingBar. When I handle a notification on one of them, it would be nice if the other stopped displaying it.

**Describe the solution you'd like**
MeetingBar instances on different machines should communicate with each other somehow. They could register Bonjour services in order to find each other, perhaps using the TXT record to identify the `EKSource` accounts the user has enabled calendars for (assuming the source identifier is stable across machines; if so, use that, or probably hash that + source type just to be sure it's unique and not leaking info). Maybe you can figure out some reliable way to identify what's been dismissed in the TXT record value so they don't actually have to talk directly to each other, or maybe it could just have a "generation count" that's incremented any time an event from that `EKSource` is dismissed and MeetingBar can watch for that and ping the instance for details any time it changes. Or the key could even identify the last-dismissed event, though I worry about cases where there's multiple overlapping events and so the last-dismissed event may not sufficiently determine if anything's still visible.

The big consideration here is security. Anyone who doesn't already have access to the `EKStore` should not be able to figure out anything about its contents, beyond the fact that MeetingBar is running on a machine and is configured for one or more stores. Heck, the TXT record should probably include a small salt that is included in any hash, such that two machines running MeetingBar with the same accounts use different identifiers in the TXT record, but two instances with the same `EKStore` can determine that they're the same (by re-hashing their local store identifier+type with the advertised salt and comparing it to the advertised identifier).

Granted, including any kind of change count or event identifier in the TXT record allows observers to determine that the user has dismissed events, but I think that's probably okay.

**Describe alternatives you've considered**
I wish MeetingBar could just stick a custom `X-MeetingBar-Dismissed` key into the .ics for the event, but unfortunately `EKEvent` does not expose that level of access.

MeetingBar could also just advertise that it's running, and then establish and maintain communication with all other MeetingBar instances (and verifying, in a privacy-conscious manner, what `EKStore`s they have in common). This requires maintaining long-lived connections, including dealing with what happens when a connection terminates, when to re-establish communication, etc.

**Additional context*
This is a lot of work, and especially a lot of careful consideration of design from a security and privacy perspective, for what is admittedly a fairly minor bit of UX polish, but on the other hand, dismissing an event on one computer and having it automatically dismiss everywhere *feels really nice*. It's something I'm really annoyed Fantastical doesn't do.

**Comment by leits** [comment]
Thanks for the request! This is an interesting idea.

But:
- MeetingBar is not currently requesting access to iCloud.
- The app cares about the security of the user, does not store his data, and works only on his device. It's in the privacy policy.
- Technical implementation looks like a lot of work.

Sorry, these arguments are strong enough to reject this proposal.
