### ISSUE TITLE
Bug: Notification body doesn't tell me if the meeting has started

### ISSUE THREAD

**Issue by lilyball** [leits/MeetingBar#268]
**App version**
3.3.0

**Describe the bug**
When I get a notification for an event, the body just says "The event starts soon". It doesn't tell me when it actually starts, and once the event has started, this body is misleading. In my case I have MeetingBar set to notify me 1 minute in advance, but looking at the source it appears that it uses this same phrase no matter how I've configured it.

https://github.com/leits/MeetingBar/blob/d9b0293b7c6e9bc4cd0fa8ec722db98b5250532d/MeetingBar/Notifications.swift#L145

**To Reproduce**
1. Enable notifications in MeetingBar for upcoming events.
2. Receive a notification.

**Expected behavior**
The notification should tell me how long until the event starts, and should update itself automatically.

I also noticed that it's using a time interval trigger:

https://github.com/leits/MeetingBar/blob/d9b0293b7c6e9bc4cd0fa8ec722db98b5250532d/MeetingBar/Notifications.swift#L151

I'd have expected a `UNCalendarNotificationTrigger` instead, which would insulate MeetingBar from local time adjustments.

In any case, what I think MeetingBar should do is instead of scheduling a single notification, it can schedule a series of them with the same identifier. It can use this to update the body as time passes. So in my case the first one would be scheduled one minute before and say "The event starts in 1 minute", then a second scheduled on the start time that says "The event starts now", and then a third scheduled a bit in the future that says "The event started at 1:00 PM" (or it could say "The event started 1 minute ago" / "2 minutes ago" / etc, though this would mean scheduling a lot of notifications; with this approach it could just pick, say, 5 minutes worth of post-start notifications, and then go to "The event started at 1:00 PM").

Having said that, I don't know offhand what happens if the user dismisses the notification and MeetingBar either isn't running, or doesn't dismiss pending notifications in response for some reason. I hope that actioning or dismissing a notification will proactively dismiss all pending notifications with the same identifier, but this needs to be tested.

**Alternatives considered**
Ditch the notification trigger entirely and trigger the notifications on the fly from MeetingBar. This approach may be better overall anyway, as if I quit MeetingBar, I'll probably be surprised when I get a MeetingBar notification later that day. And this allows you to do things like dynamically update the "The event started N minutes ago" event for as long as you want, without having to schedule dozens of notifications simultaneously.

**Comment by lilyball** [comment]
Of course, having written all that up, it occurs to me now that the notification does show its age in the upper-right corner, so we could actually just make this super simple and change the body to "Today at 1:00 PM" or something like that. Having said that, given that MeetingBar is focused on "the event is starting now" as opposed to just generic alarms like Calendar has, I'm still a fan of "The event starts in 1 minute" / "The event starts now" / "The event started N minutes ago" as that's a much bigger call to action and makes it a lot easier to tell at a glance whether the meeting has started yet. Scheduling 3 notifications instead of 1 does not seem at all unreasonable (this is "The event started at 1:00 PM" as the third), though supporting "The event started N minutes ago" would be a nice enhancement (as it provides increasing urgency for joining).

**Comment by leits** [comment]
Thanks, @lilyball for the report/request!

Added changes with time delta in notifications to the next release
https://github.com/leits/MeetingBar/commit/0c158f789e869b972651f76024e119e9d6a6be52
