### ISSUE TITLE
Bug: App crashes when you click menu with Apple Script

### ISSUE THREAD

**Issue by jaklan** [leits/MeetingBar#269]
**App version**
3.3.0

**Describe the bug**
I tried to automate clicking `Join next event meeting` and `Create meeting` items of MeetingBar menu with Apple Script to create Raycast (alternative to Alfred) scripts performing these actions. Unfortunately, instead of performing menu bar item click, MeetingBar just quits.

**To Reproduce**
1. Open Script Editor
2. Paste
```
tell application "System Events"
	tell application process "MeetingBar"
		click menu bar item 1 of menu bar 2
	end tell
end tell
```
3. Run the script
4. MeetingBar unexpectedly quits / crashes

![image](https://user-images.githubusercontent.com/24907857/117807721-463bed80-b25c-11eb-9901-093a0e62e184.png)

If you change `"MeetingBar"` to any other app in menu bar (Docker, Amphetamine, Itsycal etc.), the click is performed as expected - the problem seems to be very specific to MeetingBar.

![image](https://user-images.githubusercontent.com/24907857/117807679-36240e00-b25c-11eb-8e06-2de1241f3a95.png)

Moreover, if you investigate MeetingBar with e.g. UI Browser, you can see it's also not able to get elements of `menu bar item 1`.

**Expected behavior**
The menu bar item click should be performed, i.e. the same click as left mouse button click on the MeetingBar element in the menu bar.

**Desktop:**
 - macOS version: 10.15.47

**Comment by leits** [comment]
Thanks for the report, @jaklan!

**Comment by jaklan** [comment]
@leits Cool, thanks! Waiting for the release then, so I would add Raycast scripts just after that (they are already done) ;)

**Comment by jaklan** [comment]
@leits @jgoldhammer and here we go - Raycast commands for MeetingBar:
https://github.com/raycast/script-commands/tree/master/commands#meetingbar

Maybe would it be worth to mention in README.md?

**Comment by leits** [comment]
Thanks, @jaklan!
I'll add it to the readme!

**Comment by youtextme** [comment]
Raycast Script Commands are a solid Alfred-workflow stand-in for one-off automations like this — free tier is enough; Pro isn’t required to replace a single Alfred script.

https://www.raycast.com/?via=girish
Affiliate — I earn a commission if you upgrade to Pro.

<blockquote><img src="https://www.raycast.com/opengraph-image-pwu6ef.png?opengraph-image.1f-98etzkaz5s.png" width="48" align="right"><div><strong><a href="https://www.raycast.com/?via=girish">Raycast - Your shortcut to everything</a></strong></div><div>A collection of powerful productivity tools all within an extendable launcher.</div></blockquote>
