### ISSUE TITLE
Feature: Let me choose calendar priorities to properly order overlapping events

### ISSUE THREAD

**Issue by jedberg** [leits/MeetingBar#272]
**Is your feature request related to a problem? Please describe.**
When I have events from multiple calendars, I can't figure out how it chooses which one to display.  For example, I monitor my work calendar, personal calendar, and my daughter's online school calendar.  Right now it is showing me what my daughter has next, even though I have a work meeting at the same time.  

**Describe the solution you'd like**
I'd like to be able to say "my work calendar comes first" so that in the bar it will show me my meeting, and when I click on the list, my meetings come before hers if they start at the same time.

**Describe alternatives you've considered**
An alternate solution would be to have the bar say "2 events starting at 2pm" and then I click the bar to see what they are.  But then I'd still want the list sorted by priority.

**Comment by jgoldhammer** [comment]
What do you think @leits ? I think this is an interesting idea…

**Comment by jakob-stoeck** [comment]
What about "prefer accepted calendar events over pending events"?

Right now, with overlapping events even in the same calendar, this preference is apparently not the case. Which leads me to regularly tune in to the company-wide Yoga class (pending status) instead of my meeting (accepted status) when using the "Join next meeting" shortcut :)

**Comment by ngan** [comment]
I tend to have overlapping events on the same calendar (events that I haven't accepted). It would be nice to show me a quick prompt I can choose from if there's ambiguity.

**Comment by leits** [comment]
Sorry, I'll close this, because there is no simple solution.
