### ISSUE TITLE
Bug: the counter is rounded down, not rounded up

### ISSUE THREAD

**Issue by jaklan** [leits/MeetingBar#273]
**App version**
3.4.0

**Describe the bug**
When some minute starts, e.g. 13:52, the counter would show that the meeting scheduled for 14:00 starts in 7 min, not 8 min. It's somehow correct, because it's actually 7 min XX sec, but rounding down is less intuitive than rounding up and in result the banner changes to `some_meeting now (XX m left)` one minute before the actual start of the meeting.

**Expected behavior**
Round up, not down.

**Screenshots**
![image](https://user-images.githubusercontent.com/24907857/118121415-c0ea4180-b3f1-11eb-935a-566f531298d9.png)

**Desktop (please complete the following information):**
 - macOS version: 10.15.7

**Comment by leits** [comment]
Hi, @jaklan.

Added fix to the upcoming release!
https://github.com/leits/MeetingBar/commit/8a99e8aa074af27c47c745a8d9c3499257c6a268

**Comment by jaklan** [comment]
@leits great to hear! I just wonder about this line:
https://github.com/leits/MeetingBar/blob/8a99e8aa074af27c47c745a8d9c3499257c6a268/MeetingBar/StatusBarItemControler.swift#L988
and specifically `(event.endDate)! > prevMinute` - let's say the event ends at 15:00:00 and the current time is 15:00:48 - as I understand, the current implementation would should the meeting as still active (15:00:00 > 14:59:48), however it should be already finished, is that not the case?

**Comment by leits** [comment]
Yes, you're right. Thanks!

**Comment by jaklan** [comment]
@leits I have noticed that in the newest release menu bar updates are delayed for around 3 sec against clock. Tbh I have no idea if that was the case before as well, but now, when the counter is fixed, it's just easily visible 😉 

I'm not sure if these lines are the crucial part here:
https://github.com/leits/MeetingBar/blob/a874bcd6aa1b299a87033b43d50b9ce0613e81fb/MeetingBar/AppDelegate.swift#L432-L435
but if yes - maybe some idea would be to also set up a start time for the timer to always be the first second of the next minute (`14:59:00` (or `:01`), `15:00:00` (or `:01`) etc.). Also the interval probably could be then 1 minute instead of 10 seconds.

**Comment by jaklan** [comment]
@leits Today I've noticed that delay can be longer - it actually depends on what time MeetingBar app was launched. And that makes sense looking how updater works (no fix starting time), but imho that's also a sign that it should be fixed 😉

**Comment by leits** [comment]
Thanks, @jaklan!
I'll take a look 😉
