### ISSUE TITLE
Feature: Automatically join meetings that are starting

### ISSUE THREAD

**Issue by jasiek** [leits/MeetingBar#274]
**Is your feature request related to a problem? Please describe.**
I miss notifications when my editor is in full screen.

**Describe the solution you'd like**
* An option to auto-join next meeting.
* A popup (in the center of the screen), to ask whether I'd like to join a meeting which is just starting.

**Describe alternatives you've considered**
I'm not sure how to accomplish the desired effect via other means.

**Additional context**
Using Google Meet - which, unlike zoom, doesn't come with its own prompter to join a meeting.

**Comment by leits** [comment]
Thanks for the request, @jasiek.

Please, follow the #30, it's already in the backlog.
