### ISSUE TITLE
Feature: Option to hide Status bar icon when there are no scheduled meetings

### ISSUE THREAD

**Issue by adjurk** [leits/MeetingBar#280]
**Is your feature request related to a problem? Please describe.**
I feel like my status bar gets cluttered and the icon displaying no upcoming meetings is useless to me. I'd only want to show the upcoming meeting when there is one.

**Describe the solution you'd like**
There should be a checkbox option to hide the MeetingBar status bar icon if there are no meetings for the next `x` minutes.

**Describe alternatives you've considered**
I could use an other app I use, Hidden Bar, to hide MeetingBar when I don't need it, but I'd prefer for it to be automatic.

**Comment by mlcampbe** [comment]
I would love to see this feature.

**Comment by leits** [comment]
Hi, @adjurk, @mlcampbe. 
Thanks for the request!

I'm sorry, but I'll reject this suggestion.
The status bar is the only interface to the application, so if you hide it, the user will not be able to use it.
There is also a bad scenario, when the user has enabled this option and selected the wrong calendar, then the app will disappear forever.

You can use Bartender, which has the ability to show the icon only if it changes. Or another application with similar functionality.

**Comment by coelho** [comment]
@leits Would love to see this.
Settings could be accessible by opening the app with Spotlight. A few other apps do it this way as well.

With your blessing I can submit a PR in my free time if you'd like? :)
