### ISSUE TITLE
Feature: convert mails into meeting invites

### ISSUE THREAD

**Issue by shivanimall** [leits/MeetingBar#282]
curious if you (currently/will) support converting mails into meeting invites? 

For example: I am signed up for mail lists that have regular meetings relevant to me. 
Those mails contain meeting_name/date/time/zoom invite link, but currently either I'd have to set up a manual meeting invite or reminder for these.

**Comment by leits** [comment]
Thanks for the request.
Sorry, the application works with the calendar and there are no plans to integrate it with the email inbox.
