### ISSUE TITLE
Bug: MeetingBar time is not in sync with macOS

### ISSUE THREAD

**Issue by voska** [leits/MeetingBar#284]
**App version**
3.4.0

**Describe the bug**
The time service in use by MeetingBar doesn't seem to be in sync with my Mac clock. Meetings will show that they have started before my Mac time shows that the meeting should start.

**To Reproduce**
1. Set a 1hr meeting at 12:00
2. Watch the "starts in x min" around 11:57
3. At 11:59, it will say "59m left"

**Expected behavior**
I expect the meeting to start at exactly the same time as my Mac shows

**Screenshots**
I will take some next time I notice it and upload here. It's been happening consistently since I installed.

**Desktop (please complete the following information):**
 - macOS version: 11.4

**Additional context**
N/a

**Comment by leits** [comment]
Thanks for the report, @voska.
Did you see this bug after the report?
I didn't manage to reproduce it.

**Comment by edavidaja** [comment]
I also have the same issue, here's a screenshot of the countdown, which is consistently off by about a minute. Also running macos 11.4

![image](https://user-images.githubusercontent.com/12927842/125308571-039b9d80-e2ff-11eb-8e00-86a3799272c4.png)

**Comment by voska** [comment]
It's still happening all the time for me. Here's a screenshot I took recently
<img width="464" alt="Screen Shot 2021-08-04 at 16 13 21" src="https://user-images.githubusercontent.com/3444419/128641578-f2923eff-6f6d-4a3a-bdc5-0d4b42cc0ecc.png">

**Comment by jaklan** [comment]
@voska it should be solved with the newest release, the issue was related to the time being rounded down instead of up.

**Comment by voska** [comment]
Yes! Working well now. Thank you!

**Comment by leits** [comment]
🎉
