### ISSUE TITLE
Support earlier versions of macOS

### ISSUE THREAD

**Issue by petethepig** [leits/MeetingBar#29]
**Is your feature request related to a problem? Please describe.**
MeetingBar doesn't work on macOS Mohave (I'm on 10.14.5)

**Describe the solution you'd like**
It'd be great if it worked on earlier versions of macOS, such as macOS Mohave.

**Describe alternatives you've considered**
I considered upgrading to Catalina, but I'm not going to do that in the near future.

**Additional context**
I don't know the details, but I'm hoping it's just a matter of compiling it for the earlier version of macOS. I think that would be easy to implement.

Thanks in advance!

**Comment by mobiliodevelopment** [comment]
I'm working on 10.13 due issues with new macOS versions, but this is long story.

I also would like to see support for earlier versions.

**Comment by ronakjain90** [comment]
Hi - Wanted to try this app, but got the following error.

```
==> Downloading https://github.com/leits/MeetingBar/releases/download/v1.3/MeetingBar.dmg
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws.com/262013713/08d05900-bfd6-11ea-8e12-00ca3461c9e9?X-Amz-Algorithm=AWS4-HMAC-
######################################################################## 100.0%
==> Verifying SHA-256 checksum for Cask 'meetingbar'.
Error: macOS Catalina or newer is required.
```

Would be nice older OS is supported too. Commenting here so that I could be notified if this is fixed.

**Comment by dataf3l** [comment]
"Error: macOS Catalina or newer is required." I was heartbroken :(
I guess I'll have to upgrade...

**Comment by madhur** [comment]
I would also love the Mojave version. Long time to go before I upgrade to Catalina

**Comment by jgoldhammer** [comment]
I am sorry- we have to close this issue. The effort supporting older versions is too high because SwiftUI will not be ported to older versions from Apple. Very sorry!

**Comment by dataf3l** [comment]
It's OK, we forgive you
