### ISSUE TITLE
Feature: Allow hiding of meetings marked as "tenative"

### ISSUE THREAD

**Issue by mmccoy37** [leits/MeetingBar#297]
**Is your feature request related to a problem? Please describe.**
Many teams send recurring meetings for things like office hours. I don't want this to show up as "upcoming" but I also dont want to remove it from my calendar. So I mark my attendance as tenative. I would like support for tenative meetings to be hidden on MeetingBar.

**Describe the solution you'd like**
 I would like support for tenative meetings to be hidden on MeetingBar.

**Describe alternatives you've considered**
If I decline the meeting I will not know it is happening. 

**Additional context**
N/A

**Comment by jgoldhammer** [comment]
Hi @mmccoy37 - 
this is already possible.
![image](https://user-images.githubusercontent.com/3872101/130290340-f3922fd9-25ff-4594-bb28-0e73a6ea03bd.png)

"Showing as inactive" does not show pending events  in the statusbar, but still in the menu...
Please reopen the ticket if this does not help.

Thx
Jens
