### ISSUE TITLE
Automatically Join Meeting

### ISSUE THREAD

**Issue by bberenberg** [leits/MeetingBar#30]
I don't want to remember to click to join. I want it to automatically join when it's the right time. Likely best to default this to disabled and let users like myself opt into it

**Comment by bberenberg** [comment]
I think that would make the most sense.

**Comment by jgoldhammer** [comment]
@leits - what do you think? How to track wich event was started already to avoid multiple starts? List of event ids in user defaults?

 When exactly should the event be launched? Two or one minute before or exactly the start of the event? Some meeting services load 20 or more seconds...

**Comment by bberenberg** [comment]
Those are great questions @jgoldhammer 

They made me think that maybe the question is less 

> will you be 30 seconds late if we launch at 12:00

but rather 

> If you're on a call that ends at 12:00 and another meeting starts at 12:00 in the same application (Zoom), will launching the new meeting end the other meeting abruptly, and if so, does the user get a chance to stop that

Depending on the outcome of this across supported meeting applications, you can then decide whether you want to do it a bit earlier, or exactly at the cutover time.

**Comment by jgoldhammer** [comment]
Very good answer! 
Some meeting applications will ask to end the other meeting, especially teams popups the meeting and the user has to manually click to end the other meeting. I guess this is not true for the whole list.

We could add a second statusbar item with a countdown to launch the next meeting which could be stopped or delayed by the user :-)

**Comment by bberenberg** [comment]
I am not very good with UI design and won't try and suggest the visual solution to this challenge. However I think the practical first step may be to document the interrupt behavior of each supported conferencing solution.

**Comment by bberenberg** [comment]
I noticed that more meeting apps were added in 3.0. As more services are added, features like this one become more and more complex to design and implement. 

Is there a planned architecture / approach of how the project will deal with features / changes that have per meeting app consideration?

**Comment by leits** [comment]
Will be released as part of MeetingBar 4.0.
