### ISSUE TITLE
Bug: Zoom links are not recognized in some events after 3.5.0 release

### ISSUE THREAD

**Issue by qetzal** [leits/MeetingBar#301]
**App version**
3.5.0

**Describe the bug**
Zoom links are not recognized in some events after 3.5.0 release. It looks like the problem is related to HTML in the event descriptions. 

**To Reproduce**
1. Create a new event in Google Calendar. Add link to a Zoom call in the event description: https://www.dropbox.com/s/1ypbvwg8xg9cuut/Screen%20Shot%202021-07-14%20at%2009.55.07.png?dl=0 
2. Google Calendar's description field has a WYSIWYG editor now. So sometimes it generates a HTML code around the link. Most calendar apps can render HTML in event description. Some don't. If I view this event in Apple Calendar, then I see this: https://www.dropbox.com/s/q23gyfaukdebmfb/Screen%20Shot%202021-07-14%20at%2009.55.22.png?dl=0

I see the following codes in past events: 

`<a href="https://us02web.zoom.us/j/999999999?pwd=xxxxxxxxxxxxxxxxxxx">https://us02web.zoom.us/j/999999999?pwd=xxxxxxxxxxxxxxxxxxx</a>`

`<p>https://us02web.zoom.us/j/999999999?pwd=xxxxxxxxxxxxxxxxxxx&nbsp;</p><label><br></label>`

3. MeetingBar cannot recognize Zoom links in such events. 

This behaviour started in 3.5.0 so I suspect the issue is related to this commit: https://github.com/leits/MeetingBar/commit/9bbb9f46b177bdaecd7a1265de79667d83f745ea 

**Expected behavior**
Zoom links are recognized even if HTML code is used in event descriptions. 

**Desktop (please complete the following information):**
 - macOS version: 11.4

**Comment by leits** [comment]
Thanks for the report, @qetzal!
