### ISSUE TITLE
Feature: Open arbitrary application or shell script when joining a meeting

### ISSUE THREAD

**Issue by marcschumacher** [leits/MeetingBar#304]
I usually have a Chrome open all the time for calendar and all kinds of "applications". Now I would like to have meetings separate, e.g. in order to be able to browse through documentation during meetings. Currently MeetingBar opens in a new tab when I join a meeting.

I would like to have more control on what is happening when I start a meeting (using MeetingBar). Ideal for me would be to be able to call a script with a preconfigured template, similar to the functionality of choosing an application to open (like currently implemented), I would like to be able to open a script with the URL to the meeting. That way I could even do more, like changing lights, turning off music (like in the example Apple Script section in preferences) and more.

Alternatively it would be fine to be able to run the script in the browser configuration section. But I was unable to run a script here for whatever reason. Probably the code does not distinguish between selecting an application and just an executable file like a script. If this would be fixed, I would also be fine. I would assume that there would be just one parameter with the URL supplied.
Maybe it would already be sufficient to be able to add options to the application, like `--new-window` in Chrome in order to always open in a new window. Or anything like described [here](https://apple.stackexchange.com/questions/305901/open-a-new-browser-window-from-terminal).

**Comment by jgoldhammer** [comment]
Hi @marcschumacher ,

thanks for the feature request. Unfortunately due to the apple sandbox we cannot run application with arguments. I have tried that some months ago while implementing the browser stuff.

I guess combining #166 with the script running on joining a meeting would be fine, so that we handover arguments to the running script. What do you think?

**Comment by leits** [comment]
As there was no feedback, I will close the issue now.
