### ISSUE TITLE
Add support for opening Google Meet meetings in new Progressive Web App (PWA)

### ISSUE THREAD

**Issue by daubman** [leits/MeetingBar#313]
Google has released and is promoting its [newer Google Meet progressive web app](https://workspaceupdates.googleblog.com/2021/07/use-new-google-meet-web-app-for-better.html). One feature that has been challenging for me with MeetingBar is that it opens the meeting in whatever last-active browser window you were using, which may or may not be the right google account window, let alone the window I would want it in (would love a new window option).

Anyway, with this new PWA specifically for Meet, it would be great to add this as a browser and have MeetingBar open meet meetings in it.

I tried just adding it as a new browser, which worked fine (MacOS Big Sur 11.4), however, it seems the PWA is not registered to handle URLs the way MeetingBar specifies them...

First I get a MacOS pupup saying:
"The application “Google Meet” cannot open the specified document or URL."

And then I get the MEETINGBAR toast that
"Oops! Unable to open the link in Google Meet
Make sure you have Google Meet installed, or change the browser in preferences."

In services I added the PWA for meet as:
/Users/adaubman/Applications/Chrome Apps.localized/Google Meet.app

**Comment by leits** [comment]
Hi, @daubman!
Thanks for your request!

MeetingBar opens something in other apps using a URL scheme.
For browsers, it's https:// and some native macOS app supports they own scheme (like zoomtg:// for Zoom app).

But Google Meet PWA doesn't support https:// (otherwise your links would open) and doesn't have its own scheme.
 
So, for now there is no way to add such support on MeetingBar side. Sorry!

**Comment by worawees** [comment]
With my limited knowledge, I wonder that we can do smth like let open the meet URL in chrome first, and then on meet.google.com we detect whether its PWA app has already been installed then close the newly open tab and then launch PWA with the given meeting url?

**Comment by leits** [comment]
Sorry, @worawees, the app cannot determine if the link opens in the PWA.

**Comment by vodrazka** [comment]
Hey, any updates on this one?

**Comment by rexfm** [comment]
I made this Chrome Extension as a workaround to open Meet links in the PWA: https://github.com/rexfm/SpeedyMeet
