### ISSUE TITLE
Feature: Add option for showing "No more meetings" text instead of checkmark icon

### ISSUE THREAD

**Issue by starcraft66** [leits/MeetingBar#317]
**Is your feature request related to a problem? Please describe.**
MeetingBar usually displays long strings of text all day as meetings come and go, but at the end of the day it suddenly transforms into a small icon. I'd love to see an option to show text indicating there are no meetings at the end of the day instead of an icon. It would look more consistent to me.

**Describe the solution you'd like**
I'd love to see an option added to show customizable text like "No more meetings" or "No more meetings today" instead of the calendar icon with a check mark in it in the menu bar when there are no remaining meetings for the day.

**Comment by leits** [comment]
https://github.com/leits/MeetingBar/pull/318#issuecomment-1193155033
