### ISSUE TITLE
Bug: Unable to click on "Show only next event starting within %d minutes" text to toggle tick box

### ISSUE THREAD

**Issue by hughlilly** [leits/MeetingBar#329]
MeetingBar **v3.7.0**

**Describe the bug**
Can't click the text "Show only next event starting within %d minutes" to toggle that tick box

**To Reproduce**
1. Open Preferences
2. Go to Appearance section
3. Click "Show only next event starting within %d minutes" text (_not_ its tick box)
4. Tickbox does not toggle off/on

**Expected behavior**
The tick box ought to toggle (i.e., turn off or on, depending on current state)

**Desktop (please complete the following information):**
macOS 11.5.2 (20G95) on a MacBook Pro (Retina, 13-inch, Early 2015)

**Comment by leits** [comment]
Thanks for the report, @hughlilly!
This is because the text is not part of the toggle, it's part of the tick box.
Added the fix to the future 3.8 release!
