### ISSUE TITLE
Allow Apple to check for malicious software

### ISSUE THREAD

**Issue by crstauf** [leits/MeetingBar#33]
**Is your feature request related to a problem? Please describe.**
While I know it's not necessary, I receive a lot of peace of mind when I don't see the warning:
<img width="532" alt="Screen Shot 2020-07-29 at 7 21 24 PM" src="https://user-images.githubusercontent.com/4573033/88863466-f0b4b980-d1d0-11ea-9225-c21636153d94.png">

**Describe the solution you'd like**
Allow Apple to check for malicious software.

**Additional context**
Article: https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution

**Comment by leits** [comment]
The app in latest release (1.6) is notarized!
@crstauf @RubenSandwich @bitmanic @ChillyBwoy @cromulus @crstauf @zneak @nathanrobb @malps13 @hubie check it out!

**Comment by crstauf** [comment]
@crstauf Thank you! Will install today!

**Comment by crstauf** [comment]
@leits Thank you! Will install today!
