### ISSUE TITLE
No spacing between icon and title?

### ISSUE THREAD

**Issue by hughlilly** [leits/MeetingBar#330]
The spacing between the icon and title is either very small or nonexistent:
<img width="170" alt="image" src="https://user-images.githubusercontent.com/12046008/131598311-7dbe8669-3623-478d-8ab1-bcb28e0c6540.png">

I would suggest adding some spacing, if possible.

Thanks
Hugh

**Comment by leits** [comment]
Sorry, didn't find any option.
