### ISSUE TITLE
Add authuser to url

### ISSUE THREAD

**Issue by sirupsen** [leits/MeetingBar#34]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I am logged into multiple Google Accounts for Meet. Ideally, it'd figure out which one owns an event, and then add `?authuser=$email` to the URL to avoid users having to switch manually. 

**Describe alternatives you've considered**
This seems like the simplest solution.

**Additional context**

**Comment by dansiemens** [comment]
Duplicate of #24

**Comment by BrandonSmith** [comment]
Seems this is available in latest release. Right?

**Comment by Itaybre** [comment]
@BrandonSmith you are right, it was merged for 1.5

@leits please close this issue

**Comment by leits** [comment]
Thanks, @BrandonSmith, @Itaybre. Closed.
