### ISSUE TITLE
Syncing

### ISSUE THREAD

**Issue by vi-cat** [leits/MeetingBar#340]
My meetings change often, sometimes even in the same day. MeetingBar tends to not update when I need it most. Would it possible to:

- Add a manual sync button
- Add automated sync options (every x minutes, hours)

Thank you.

**Comment by leits** [comment]
Hi, @vi-cat!

Thanks for the request. MeetingBar uses macOS Calendar as the source of calendars' data. So there is no way to make manual sync or change Calendar preferences from MeetingBar.

By default, the Calendar app update subscribed calendars only every 15 minutes, and MeetingBar updates on every update in the Calendar app.
You can reduce Calendar app pull interval manually: https://support.apple.com/en-gb/guide/calendar/icl1024/mac

To manual sync in the Calendar app:
- use the "Refresh Calendars" button from the View tab in the status bar of the Calendar app 
- use the `cmd+r` shortcut when you are in the Calendar app.
