### ISSUE TITLE
Bug: Build current master branch failed

### ISSUE THREAD

**Issue by metrue** [leits/MeetingBar#342]
**App version**
master branch

**Describe the bug**
I could not build project on Mac

**To Reproduce**

1. Clone repo
```
git clone https://github.com/leits/MeetingBar 
```
2. Build with XCode

**Expected behavior**
Should build it successfully.

**Screenshots**
<img width="1419" alt="Screen Shot 2021-09-17 at 4 39 06 PM" src="https://user-images.githubusercontent.com/1001246/133752493-78c2b359-7606-4ce2-b3c3-aeb14b07299c.png">

**Desktop (please complete the following information):**
macOS Big Sur 11.5.1
```
$ uname -a
Darwin C02ZT0FHLVDN 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64
```
```
$ xcodebuild -version
Xcode 12.5.1
Build version 12E507
```

**Additional context**

**Comment by leits** [comment]
Thanks, @metrue!
Fixed: https://github.com/leits/MeetingBar/commit/b14588f88c1746d8df1470edf18915106fd41500
