### ISSUE TITLE
Add Lark/Feishu detection

### ISSUE THREAD

**Issue by qetzal** [leits/MeetingBar#349]
There is a company that provides services similar to Slack/Zoom/Google Docs. 
The Chinese version is called Feishu (https://www.feishu.cn/). In US it is launched as Lark (https://www.larksuite.com/)

They use the following links to join video cals:
— https://vc.feishu.cn/j/*
— https://vc.larksuite.com/j/*

\* — bunch of numbers.

**Comment by leits** [comment]
Thank you for the request, @qetzal!
I'll add it to the next release scope.
