### ISSUE TITLE
Add an option the shorten the ETA counter

### ISSUE THREAD

**Issue by dutzi** [leits/MeetingBar#35]
Hey, great app!

Would it be possible to add an option to shorten the ETA counter, meaning the "in 1 hour 45 min", to something like "1h 45m" (avoiding colons as it may be mistaken with the clock)?

**Comment by sn0wyfall** [comment]
At the moment it only shows hours. So 1h 45m would be shown as 1h. I prefer it this way because I actually don't really care how many hours _and minutes_ I have left, until there is less than 1 hour remaining. So I think the current behavior would work well with this.
