### ISSUE TITLE
Feature: Add Regex to filter out events by title

### ISSUE THREAD

**Issue by fkrauthan** [leits/MeetingBar#355]
**Is your feature request related to a problem? Please describe.**
At work I am using Clockwise to manage my calendar events. Clockwise automatically create a meeting called `Lunch` during lunch time and `Focus time` if there is a huge free block of time to discourage people for scheduling meetings. Currently this meetings also show up in MeetingBar even thought they are not really real meetings.

**Describe the solution you'd like**
A simple list of regex rules that I can define would be great. And any meeting title that matches one of the regex rules would be ignored by MeetingBar.

**Comment by fkrauthan** [comment]
This is now merged

**Comment by fkrauthan** [comment]
Any idea when you might push a new release out @leits?

**Comment by leits** [comment]
Released 😉
