### ISSUE TITLE
Feature: "Join current event meeting" should join the event with meeting URL

### ISSUE THREAD

**Issue by darthwalsh** [leits/MeetingBar#356]
**Is your feature request related to a problem? Please describe.**
I often have two events on my calendars at a similar time, e.g. "1:1 with my boss" that has a Zoom URL, and on my family calendar "Walk the Dog" with no meeting URL.
When I use the menu action "Join current event meeting" I'm hoping to start the 1:1 with my boss, but sometimes the Walk the Dog meeting takes priority, and I get the message "Ouch! Can't join..." for No Meeting URL.

*I want to join the event with the Zoom URL, and not calendar events without meeting URLs.*

**Describe the solution you'd like**
The algorithm for deciding the "current event" meeting to be joined should only consider events with meeting URLs.
Any event that would cause the Ouch! message should be ignored when deciding the "current event" meeting to be joined.

(After considering all events with Meeting URL, I don't think there is a need to consider events without Meeting URL as they aren't joinable, so some error message like Ouch! No meetings with URL would still be accurate.)

**Describe alternatives you've considered**
Part of this problem could be addressed with #272 but that doesn't address this problem of having two events at similar times that are both on my work calendar.

(I set up a recurring calendar event at 10:55 to prep for 11:00 work standup. But today the standup was moved to 10:45. At  10:45 (plus or minus a minute) I pressed my global hotkey to "Join current event meeting" but it failed because the "current event" was my 10:55 prep event, and not the standup event that was currently occurring.) Having a calendar preference would work some of the time, but not for occurance like this.

**Additional context**

Here's a screenshot showing how to reproduce this, +50 minutes from the above

- Test Standup:  11:35-12:05
- Test reminder: 11:45-11:50
- Screenshot taken at 11:35, showing that the "Test reminder" is the current meeting: ![image](https://user-images.githubusercontent.com/2829438/136082631-ddcf115c-6e63-4466-996b-3df57b22bcab.png)

I didn't add a zoom URL for the above screenshot, but I get the same behavior when the *current meeting* has a zoom URL, and menubar shows the future meeting: 
![image](https://user-images.githubusercontent.com/2829438/136083259-df60813f-e110-4b6c-8d34-ada7a6755087.png)

(BTW Your app is awesome! It's the number one productivity app I recommend to friends using macbooks!)

**Comment by jakob-stoeck** [comment]
Setting "show as inactive" for meetings without meeting URL should solve this.

![image](https://user-images.githubusercontent.com/62809/171892337-ceeca992-354a-4bfe-b043-a0d3ee92a2f8.png)

**Comment by darthwalsh** [comment]
@jakob-stoeck  thanks! that preference nearly solves my problem, except for some of my meetings have a video URL and no attendees.

**Comment by jakob-stoeck** [comment]
@darthwalsh it sounds like the option "Events without guests: show as inactive" would solve this one, too? Left column, third from top.

**Comment by darthwalsh** [comment]
@jakob-stoeck i wasn't clear. When I set "Events without guests" = "show as inactive" that hides some events that I want MeetingBar to show.

For example, I have a 9PM recurring event i put onto my calendar with a zoom link, with no guests, that I want to show up on the menubar. It shows like:

![9PM meeting does now show up](https://user-images.githubusercontent.com/2829438/175185347-259b493e-0117-41da-8f09-03d857d00e65.png)

If I change the "Events without guests" setting back to "show", now that event shows like I want it to:

![image](https://user-images.githubusercontent.com/2829438/175185415-1504e149-9f5d-4d87-8bd1-be6d95d88a1b.png)

**Comment by leits** [comment]
@darthwalsh, as understood from your last reply, you found the right combination of settings, so I'm closing this ticket.

**Comment by darthwalsh** [comment]
Sorry, I think I'm having trouble saying my preferences because I want the app to work differently in different contexts?

Thanks for considering this!

**Comment by garfolino** [comment]
I have been looking for that option for a long time, even tried with Regex. 

The Hide all without meeting links, should be a separated options. It's hidden under Other events.
