### ISSUE TITLE
Feature: User-selectable option to use teams.microsoft.com instead of Teams app (through `msteams://` protocol link)

### ISSUE THREAD

**Issue by hughlilly** [leits/MeetingBar#359]
**Is your feature request related to a problem? Please describe.**
I use the web-based version of Microsoft Teams; I don't have (and don't want to get) the Mac client. My primary browser is Safari.

**Describe the solution you'd like**
Some meeting invites will contain `msteams://` protocol links, but I would like to somehow have MeetingBar convert these to `teams.microsoft.com` links. This new way of opening Teams meetings could be activated by a tick box in the preferences that says something like “Use browser interface for Teams meetings”.

While opening an `msteams://` link will open a web page with a "Use web app" button, I am still prompted by macOS to select an application to handle the `msteams://` link—see the screenshot below.

**Describe alternatives you've considered**
I'm not sure how this could be implemented or if it's even feasible for MeetingBar to transform an `msteams://` link—or if there is some other way of achieving what I desire.

**Screenshot**
<img width="372" alt="image" src="https://user-images.githubusercontent.com/12046008/136297328-b0311812-9e2b-4461-a15b-65ade8ab70ec.png">

**Comment by jgoldhammer** [comment]
Hi @hughlilly - thanks for your request.

So you want us to convert the ms teams app link to the weblink, so that it can be opened with your favorite browser.

It looks reasonable. Are you interested in contributing a merge request?
Thx
Jens

**Comment by hughlilly** [comment]
Hi @jgoldhammer, thanks for the reply. I’d love to contribute but I don’t really know what I’d be doing with the code—would you be able to give me some pointers? Many thanks.

**Comment by leits** [comment]
Hi @hughlilly!
Is this request still relevant to you?

**Comment by hughlilly** [comment]
Since it’s now possible to choose “Open Teams links in… the Teams app” on the Services tab, setting that option solves the problem I tried to outline here. (I don’t how long this has been the case; apologies if it was already there when I submitted this issue.)
