### ISSUE TITLE
Feature: Warn if calendar can not sync

### ISSUE THREAD

**Issue by exoego** [leits/MeetingBar#365]
**# Is your feature request related to a problem? Please describe.**
I found MeetingBar does not show latest changes in calendar.
It was because Mac's Calendar app is unsynced with Google Calendar due to authorization error.
After re-authorization, error is gone and MB syncs finely.
Since I mainly use MB and rarely use Calendar app, I could not notice authorization error.

**Describe the solution you'd like**
It would be helpful if MB shows warning messages, something like `⚠️ Calendar "Foo" needs authentification ` when calendars are unsynced.
So that one can notice unsync on MB instead of Calendar app.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by leits** [comment]
Thanks for the request, @exoego.

MeetingBar uses Calendar app as a source of the data but there is no public API to get information about data freshness.
I know it would be very useful, but so far it is impossible. Sorry!
