### ISSUE TITLE
Feature: Bookmarks should honour 'Open in' preferences

### ISSUE THREAD

**Issue by marcroberts** [leits/MeetingBar#367]
**Is your feature request related to a problem? Please describe.**
I use Firefox as my main browser but prefer to open Google Meet meetings in Chrome. MeetingBar is great at doing this for scheduled events, but not for bookmarks

**Describe the solution you'd like**
If I add a Google Meet link to bookmarks I'd like for that to open in the browser thta I have chosen for google meet meetings to open in

**Describe alternatives you've considered**
Not sure there are any alternatives here

**Additional context**
None

**Comment by jgoldhammer** [comment]
Hi Marc,

thanks for the request. I think, it should honor it.
Can you please post your settings for the services and bookmarks here, so that we can have a look?

Thanks
Jens

**Comment by marcroberts** [comment]
Sure, here they are:

<img width="812" alt="Screenshot 2021-11-08 at 19 11 32" src="https://user-images.githubusercontent.com/43874/140803972-14111f32-92c4-4642-a19b-53a3cf1ede1d.png">


<img width="812" alt="Screenshot 2021-11-08 at 19 17 35" src="https://user-images.githubusercontent.com/43874/140803960-da949d31-1b29-417a-9342-98b129215d5b.png">

The 'Instant Meet' bookmark currently opens in my default browser (Firefox), Meet events from my calendar do correctly open in Chrome
