### ISSUE TITLE
Add support for custom scripts

### ISSUE THREAD

**Issue by AndreasBackx** [leits/MeetingBar#37]
**Is your feature request related to a problem? Please describe.**

At work we have internal tools for meetings. It'd be neat to make this trigger a custom script for joining a meeting.

**Describe the solution you'd like**

I write my own script to join a meeting. This script would get as much information as possible from the app so it can figure out what meeting/calendar instance it is and link it to an internal meeting. Then I would make it call me.

**Describe alternatives you've considered**

Cannot think of anything.

**Additional context**

None?

**Comment by axelson** [comment]
In a very similar vein it would be nice to add a script that would be run right before joining a meeting (I would use that to pause my music)

**Comment by leits** [comment]
Added possibility to run custom AppleScript in https://github.com/leits/MeetingBar/releases/tag/v2.0
@AndreasBackx @axelson @ivoleitao check it out!
