### ISSUE TITLE
Feature: Add option to customize meeting details submenu

### ISSUE THREAD

**Issue by hbarthels** [leits/MeetingBar#370]
**The Problem**
On small screens and for meetings with a large number of participants and/or a long note, the meeting details submenu can be longer than the height of the screen. If that happens, it gets difficult to use this submenu because it's necessary to scroll up and down.

**Idea for Solution**
What about making it possible to configure what is displayed in the submenu? A user could then reduce the size of that submenu by making it show only those items that are relevant for them. For example, I usually only care about the notes, so I would disable everything else. In some cases, this would reduce the size of that menu by more than 50%.

**Comment by leits** [comment]
Hi @hbarthels,
Thanks for the requests. 
I don't want to overcomplicate the app, so since no one else has raised this ticket for support, I'll close it. Sorry.
