### ISSUE TITLE
Add option to show only upcoming meetings intead of meetings for the current day

### ISSUE THREAD

**Issue by globau** [leits/MeetingBar#38]
**Is your feature request related to a problem? Please describe.**

I work weird hours that span midnight (working until 2am isn't unusual).
As a result MeetingBar isn't that useful as it only displays meetings up to midnight.

**Describe the solution you'd like**

I would like an option to show only upcoming meetings – for example looking forward for the next 8 or 12 hours – rather then midnight-to-midnight.

**Comment by vforge** [comment]
I used https://apps.apple.com/us/app/next-meeting/id1017470484 till today and I really miss showing meetings in the next 72h

**Comment by leits** [comment]
@globau , @vforge looks like an awesome feature for the next release!
What do you think about the options "today events"/"next n-hours events"?
Or "today events"/"next n-days events" options better?
(where "n" is customizable)

**Comment by globau** [comment]
I think N-hours would be clearer.
ie. if it were set to "1 day", it might be interpreted differently from the next 24 hours.
