### ISSUE TITLE
Feature: An option to display absolute time instead of a countdown in the menubar

### ISSUE THREAD

**Issue by taras-mukin** [leits/MeetingBar#383]
Countdown is pretty confusing to me if even is tomorrow, but I still want it to show up right now -- a line like "Event in 14h 35m" is not really intuitive. 

A simple checkbox for showing exact times would help a lot, or if you want to go a little further -- a checkbox to show countdown only if the timestamp is less than an hour from now, and a checkbox for should the end of an event also be absolute or a countdown.

**Comment by devnoname120** [comment]
@taras-mukin You can just click on the bar to see the time of your future meetings.

**Comment by leits** [comment]
Thank for the request, Taras.
Because we show absolute time in the dropdown, I don't think we need to add one more configuration parameter for this case.
