### ISSUE TITLE
Feature: URL Defense support

### ISSUE THREAD

**Issue by guyguy333** [leits/MeetingBar#384]
**Is your feature request related to a problem? Please describe.**

When an invitation includes an URL defense protected URL (https://www.proofpoint.com/us/resources/data-sheets/essentials-url-defense), Meeting Bar is unable to get the meeting link.

**Describe the solution you'd like**

MeetingBar to fetch URL Defense URL. Example:

https://urldefense.com/v3/__https://mongodb.zoom.com/j/xxxxxxxxxxxxxx

**Describe alternatives you've considered**

I need to open manually the link

**Additional context**

**Comment by leits** [comment]
Hi, @guyguy333!
Thank for the feature request!

Have you tried to use custom regex from Advanced Preferences to handle the Defense URL?
Looks like a good fit for this case!

**Comment by guyguy333** [comment]
> Hi, @guyguy333! Thank for the feature request!
> 
> Have you tried to use custom regex from Advanced Preferences to handle the Defense URL? Looks like a good fit for this case!

Thanks @leits, it worked !

Here is the regex: `https:\/\/urldefense\.com\/v3\/__https:\/\/(?:[a-z0-9-.]+)?zoom\.(?:us|com.cn|com)\/j\/[0-9a-zA-Z?=]*__;!![0-9a-zA-Z-_]*![0-9a-zA-Z!_-]*\$`

**Comment by leits** [comment]
Awesome!

**Comment by andrewmin** [comment]
Sorry to resurrect a closed issue, but any chance we might reconsider reopening it?

I'm having the same issue with an older version of Proofpoint (v2, vs. the v3 version above). For example, a link to [https://meet.google.com/jyx-ifea-jjn](https://meet.google.com/jyx-ifea-jjn) will wrap into [https://urldefense.proofpoint.com/v2/url?u=https-3A__meet.google.com_jyx-2Difea-2Djjn-3Fhs-3D224&d=DwMFaQ&c=rGIfYmk-1z7cfZPhPNJ2NJAhybwe4_LJFnxef54aLtE&r=mLNoUX_En2gO9geDTc5_aXaXNwQC36GV97jTrpAxXpM&m=kFBGgdOHVg5r5w1EG9xefdaB0FjkIky_N1iPUGkg1A0hjsdAQnWFfShNV8lkQLwl&s=hX9MGZGdvki7XoSbect74rQvY5DvQsUqiz9OGzGAttQ&e=](https://urldefense.proofpoint.com/v2/url?u=https-3A__meet.google.com_jyx-2Difea-2Djjn-3Fhs-3D224&d=DwMFaQ&c=rGIfYmk-1z7cfZPhPNJ2NJAhybwe4_LJFnxef54aLtE&r=mLNoUX_En2gO9geDTc5_aXaXNwQC36GV97jTrpAxXpM&m=kFBGgdOHVg5r5w1EG9xefdaB0FjkIky_N1iPUGkg1A0hjsdAQnWFfShNV8lkQLwl&s=hX9MGZGdvki7XoSbect74rQvY5DvQsUqiz9OGzGAttQ&e=)

I know that technically you can figure this out with a regex, but my guess is that a large % of the users who are on machines behind proofpoint will not know how to figure out a regex :). You could even pre-populate various known defense URLs into the custom regex fields.
