### ISSUE TITLE
Bug: Meeting times/titles not aligned correctly with single digit hour

### ISSUE THREAD

**Issue by ashbutcher** [leits/MeetingBar#385]
App Version 3.9.0

**Describe the bug**
Times are not aligned correctly before 10am due to the hour being only a single digit. 
Current events that are bolded fix this spacing issue (see screenshot)

**To Reproduce**
1. Click on the menu bar
2. See that the times/meetings are not aligned

**Expected behavior**
Times/meetings are aligned correctly

**Screenshots**
<img width="213" alt="Screen Shot 2021-11-23 at 9 08 35 AM" src="https://user-images.githubusercontent.com/49898396/142928037-f484bcf8-2e56-49dd-baa4-766408f8cfc3.png">

**Desktop (please complete the following information):**
 - macOS version: 11.6 Big Sur

**Comment by hughlilly** [comment]
Could the misalignment of this icon be related?
<img width="355" alt="image" src="https://user-images.githubusercontent.com/12046008/143970157-6260023a-2def-4619-b77e-51790e7bebf8.png">

This is on macOS Monterey 12.0.1 (21A559).

**Comment by Alexacobbthequeen0989** [comment]
we need to figure this out becuase my google meet is not working

**Comment by Alexacobbthequeen0989** [comment]
and yes it could

**Comment by DanielZTing** [comment]
> Could the misalignment of this icon be related? <img alt="image" width="355" src="https://user-images.githubusercontent.com/12046008/143970157-6260023a-2def-4619-b77e-51790e7bebf8.png">
> 
> This is on macOS Monterey 12.0.1 (21A559).

That sprinter icon is also misaligned for me. Does anyone know what it means, and can I turn it off?

**Comment by hughlilly** [comment]
> Does anyone know what it means, and can I turn it off?

I think it means the meeting is in progress. I don't see a way to turn it off.

> It's kind of weird how it looks completely different from the screenshot in the README.

I think it's the same icon; the screenshot — I think — was taken with Dark Mode on system-wide.

**Comment by DanielZTing** [comment]
I thought boldface meant the meeting is in progress?
