### ISSUE TITLE
Feature: 'Open Menu' shortcut toggles open/close of menu

### ISSUE THREAD

**Issue by patrickplaggenborg** [leits/MeetingBar#386]
**Is your feature request related to a problem? Please describe.**
I love the shortcut to open the MeetingBar dropdown menu showing me my meetings.

I would like to be able to quickly close that menu as well.

**Describe the solution you'd like**
It would be great if the 'Open Menu' shortcut would toggle/close the menu again when pressed when it is already open.

**Describe alternatives you've considered**
Alternative to close right now is pressing 'Escape' to close the mnu.
For some reason, pressing the 'Open Menu' shortcut twice needs me to press 'Escape' twice as well to close it. This looks like a bug.

**Additional context**
It would be super helpful to use the 'Open Menu' shortcut to toggle because it would allow me to quickly open and close the menu to have a look at my upcoming meetings without necessarily pressing any actions in it.

Using the same shortcut twice would be the most efficient way of doing it, so I don't have to move my hands to a different key/shortcut combination to close(Esc). Similar how clicking a menu bar icon twice will also toggle open/close the menu.

**Comment by leits** [comment]
Done!

**Comment by patrickplaggenborg** [comment]
Does not appear to work for me.

I'm on 4.1.0. Have cmd + shift + Y to Open Menu.

When pressing the shortcut once it opens the menu.
When pressing the shortcut while the menu is open nothing happens.

Expected behavior:
When pressing the shortcut while the menu is open it closes the menu.

**Comment by leits** [comment]
Here is a bug report for this: https://github.com/leits/MeetingBar/issues/407

**Comment by patrickplaggenborg** [comment]
Ahh oops. ESC makes a lot of sense yes, especially since it's the default macOS behavior by design. Thanks!
