### ISSUE TITLE
BlueJeans icon broken

### ISSUE THREAD

**Issue by xlbdev** [leits/MeetingBar#390]
BlueJeans is supported but doesn't show the correct icon. 

<img width="158" alt="Google Chrome-Save password? -20211216 - 14 23 47" src="https://user-images.githubusercontent.com/66292111/146457972-793e9c72-7abb-4cc8-bc61-a758223dd2a1.png">

**Comment by leits** [comment]
Thanks, @xlbdev!
Fixed!
