### ISSUE TITLE
Feature: Ability to hide / grey out meetings I haven't accepted

### ISSUE THREAD

**Issue by cheerfulstoic** [leits/MeetingBar#391]
**Is your feature request related to a problem? Please describe.**

There are a number of meetings on my work calendar that are repeating for my whole company (i.e. coffee break, playing games, and other social activities with other departments).  I could decline them, but I don't want to decline the meetings because I:

 * Would rather not send a notification to the organizer and have something for them to clean up (less important)
 * Have to decline repeated meeting individually, especially when I might join some of them.

**Describe the solution you'd like**

I'd like the ability to hide / grey out meetings that I have not yet accepted (like is possible with declined meetings).

**Describe alternatives you've considered**

🤔  Maybe there could be a state / icon displayed in the menu to show what is the status (accepted/declined/maybed/nothing done).

**Additional context**

None

**Comment by jgoldhammer** [comment]
Hi @cheerfulstoic ,

thanks for your suggestion. We have the "pending events" option - will this work for you or do you miss something?

<img width="690" alt="image" src="https://user-images.githubusercontent.com/3872101/146885825-d458ecf1-22e2-49c3-8001-ccb8517333b9.png">

Thx.

**Comment by cheerfulstoic** [comment]
Oh, duh, I didn't recognize that for what it was.  That works great, thanks!
