### ISSUE TITLE
Feature: only send notifications for events with online meetings

### ISSUE THREAD

**Issue by patrickrushton** [leits/MeetingBar#396]
**Is your feature request related to a problem? Please describe.**
Meeting Bar is sending notifications before regular events in my calendar that don't have an online meeting in the description.

**Describe the solution you'd like**
I would like to have a setting to only trigger a notification before events that have an online meeting in the description. I would still like to see all events in the menu bar and dropdown menu, just not receive notifications about them in MeetingBar..

**Additional context**
Also these Google Calendar non-meeting events are showing an icon of a "running stick-person". It's unclear what that icon signifies.

**Comment by jgoldhammer** [comment]
Hi @patrickrushton ,

thanks for your request. Maybe it is a little bit hidden in the settings dialog, but it should be possible with that setting.
![image](https://user-images.githubusercontent.com/3872101/149624368-7f1e4cc8-5c3b-45c2-b1a9-71478048c34a.png)

Can you try and see if it works for you?

**Comment by patrickrushton** [comment]
Thanks @jgoldhammer That would work, but I'd still like to have such events show in the menu bar and dropdown, just not have them trigger notifications (I updated the description above as such)

**Comment by jakob-stoeck** [comment]
If you choose "show those without meeting links as inactive" for the same dropdown, that should work

![image](https://user-images.githubusercontent.com/62809/171887753-da7822c8-9709-41ed-ac9d-e83a37516148.png)

**Comment by patrickrushton** [comment]
Seems that "show those without meeting links as inactive" doesn't just disable notifications, it also prevents the meeting title appearing in the menu bar.
