### ISSUE TITLE
Multiple calendars

### ISSUE THREAD

**Issue by durdevic** [leits/MeetingBar#4]
I guess you've been thinking about this one, it would definitely be quite neat to have 👌

**Comment by leits** [comment]
@durdevic Check the new release with this feature:
https://github.com/leits/MeetingBar/releases/tag/v1.1
+
The app is available on homebrew now:
brew cask install meetingbar

**Comment by durdevic** [comment]
Really nice update man, really nice update 💪 

Multiple calendars work and long title is quite handy!
