### ISSUE TITLE
Ability to join meeting that has already ended

### ISSUE THREAD

**Issue by sn0wyfall** [leits/MeetingBar#40]
I would like to be able to join meetings that are over. Currently there does not seem to be any way to do so. 

This is because perhaps I have another meeting in the same room (which is not in my calendar), or the meeting that should have been over is still going on and I want to rejoin it easily.

**Comment by Rucknar** [comment]
I think this works already, as long as the meeting is in the same day of course. If you click on the menu bar item, select the event from the list of a prior meeting (strikethrough font) then you it loads up that meeting. Just tested and works for me on meetings that have finished.

**Comment by sn0wyfall** [comment]
@Rucknar That’s weird. I tested and I can’t open any events from MeetingBar. Any thoughts? I’d like to move away from Meeter since it dropped functionality for free users.
