### ISSUE TITLE
Feature:  Add option to show upcoming meeting instead of the current meeting.

### ISSUE THREAD

**Issue by jedberg** [leits/MeetingBar#403]
**Is your feature request related to a problem? Please describe.**
Right now my menubar is showing my son's class that ends in 1 hour and 15 minutes.  However, I have a work meeting starting in 15 minutes that I'd like it to tell me about, instead of being surprised when I get the start notification.  There is also the related problem of overlapping meetings where I'm currently in a meeting that is scheduled to end after the start of the next one, and I'd like it to show when the next one starts so I can see it a glance.

**Describe the solution you'd like**
The first problem can be solved with feature #272 -- if I had calendar priorities, my work calendar would be ahead of his school calendar so it would show my upcoming meeting.  The second problem can be solved with a setting that says "show upcoming meeting after current meeting is X minutes old" or something similar.  After five or so minutes, I'm either attending the meeting or skipping it, but I don't really need to know about it anymore.  But with the setting off people who need to know about meeting end times will still have that information.

**Comment by leits** [comment]
Hi, @jedberg!
Thanks for your request.
We already have the same feature request in #278, so I'll close this as a duplicate.
Can you add this context to #278?
