### ISSUE TITLE
Bug: Latest version (3.10.0) isn't Apple Silicon native

### ISSUE THREAD

**Issue by qetzal** [leits/MeetingBar#410]
3.10.0

**Describe the bug**
Latest version (3.10.0) isn't Apple Silicon native. After I try to launch it, Mac OS suggest to install Rosetta first to run the app in the emulation mode. 

**To Reproduce**
1. Update to 3.10.0 from Mac App Store
2. Launch MeetingBar on M1 Mac.

**Expected behavior**
No Rosetta needed. App is Apple Silicon native as it was before.  I would assume it is somehow related to the latest update because previous versions worked on M1 just fine. 

**Screenshots**
<img width="525" alt="CleanShot 2022-01-31 at 16 27 10" src="https://user-images.githubusercontent.com/603859/151794450-42a740c0-d892-49cc-8f3e-72c6a334c164.png">

**Desktop (please complete the following information):**
 - macOS version: 12.1 (21C52)

**Comment by leits** [comment]
Thanks, @qetzal!
Have sent an updated version 3.10.1 on AppStore review.
