### ISSUE TITLE
Bug: Application running but not displaying UI

### ISSUE THREAD

**Issue by zartify** [leits/MeetingBar#411]
**App version**
3.10.0

**Describe the bug**
When I run MeetingBar I generally don't see it pop up at all in the toolbar. I have uninstalled and re-installed a few times. I do get notifications asking to give permissions for notifications, and I see the app running in the Activity Monitor, but for some reason nothing pops up in the toolbar.

One time it was running in the toolbar and it worked for a day until I had to perform a MacOS update. Then, when the computer restarted it was back to not showing up. I do have a relatively busy toolbar at this point, so I don't know if it's possible that the new macbooks have some sort of toolbar width limit because of the notch (I haven't looked into how they handle scaling up and down or anything, but just a thought).

**To Reproduce**
1. Open the app
2. Look at the toolbar and see nothing change

**Expected behavior**
A UI in the toolbar

**Screenshots**
Here's my toolbar in case that helps at all. Obviously the screenshot pretends the notch isn't there, but it is basically directly to the left of the `K` logo in the toolbar.

![image](https://user-images.githubusercontent.com/91997356/151821519-020795cd-33ca-404d-a15e-e3250ff35edd.png)

**Desktop (please complete the following information):**
 - macOS version: 12.2
 - MacBook with M1 pro

**Additional context**
Nothing more to add

**Comment by jgoldhammer** [comment]
Hi @zartify - please use something like Bartender (use the trial version) or opensource alternatives like hidden etc. to find out if meetingbar is running in the toolbar - it should when you got notifications. These tools can manage your menubar - the macos default behaviour is a little bit odd. 

Please open the ticket again if it is not working for you. I hope this is ok for you...

**Comment by zartify** [comment]
Thanks! I guess it was spacing after all, because I was able to get it to show up once I got a toolbar manager up and running. Odd that there isn't any indication in the UI that other apps are running in the toolbar. My only suggestion is to add something like this to the readme, because with the 14" macbook with the notch I guess you don't really get much toolbar space.

**Comment by avdotion** [comment]
@jgoldhammer, hi!

It is a real problem: if there are many icons in the toolbar and the length of MeetingBar message is longer than a threshold, it disappears. Like it is no meetings at all in that day.

It is critical bug! Imagine the app can randomly switches off and wakes back :(
