### ISSUE TITLE
Feature: Automatically open meeting link at start of meeting

### ISSUE THREAD

**Issue by ewolfe** [leits/MeetingBar#412]
**Is your feature request related to a problem? Please describe.**
Even with the menubar showing me my meeting is NOW I still don't see it when I'm really focusing on another task. This means I'm late to my meetings sometimes.

**Describe the solution you'd like**
I would like to have MeetingBar automatically open the meeting link at the start of the meeting (if a link exists).

**Describe alternatives you've considered**
I searched for existing solutions online that provide this functionality, to no avail.

**Additional context**
If implemented, it should probably be optional for users to turn this on.

**Comment by jgoldhammer** [comment]
Hi @ewolfe,

thanks for requesting this feature. It was so interesting for me that I have a prototype available on my local machine.

![image](https://user-images.githubusercontent.com/3872101/159580038-47731b58-be45-4aab-ab9c-25a1f4b1d5dc.png)

![image](https://user-images.githubusercontent.com/3872101/159580102-3871d399-2823-4206-a3b2-e5836eb2d28c.png)


There are some questions left:
- What about the starting time options (see above)?
- When you are late to the game, do you expect meetingbar open an event which is already running?
- When you have a all day event, do you want meetingbar to open it automatically? If yes, when?

Thanks
Jens

**Comment by leits** [comment]
Included in the next 4.0 release.
