### ISSUE TITLE
Feature: Skip meetings I'm not an attendee of 

### ISSUE THREAD

**Issue by colejd** [leits/MeetingBar#416]
**Is your feature request related to a problem? Please describe.**
My work calendar is a mix of events I'm personally expected to be at (meetings) and events that I've been invited to (company events, talks, and so on). I work around this by accepting the invitations for meetings I'm personally involved in, and not responding to meetings where I'm not explicitly requested (or setting my response to "maybe").

Right now, MeetingBar shows the next event in the menu bar, regardless of my intent to actually attend or not.

**Describe the solution you'd like**
It would be helpful to be able to show only the next event I've accepted the invitation for.

**Describe alternatives you've considered**
N/A.

Thank you!

**Comment by colejd** [comment]
Aw jeez, right after I posted this I think I found it in the settings. I think this is what "pending events" refers to.

**Comment by colejd** [comment]
Reopening because I think "pending events" doesn't do what I'm looking for.

MeetingBar is currently showing me a meeting that's marked as "tentative", which is to say that I haven't accepted or rejected the meeting. Is this what the "pending events" dropdown is meant to handle, @leits?

**Comment by patrickrushton** [comment]
My guess is that pending events are ones that I've been invited to but haven't yet responded to.

Like you, I also respond as Maybe/Tentative to a lot of work events and would prefer not to have these show up in my menu bar.

**Comment by leocaseiro** [comment]
This Issue seems to be "closed" still.
