### ISSUE TITLE
Feature: add support for Livestorm webinars

### ISSUE THREAD

**Issue by LionelPaulus** [leits/MeetingBar#417]
Would it be possible to add support for Livestorm webinars?

Here is how they show up in the calendar: [event example](https://calendar.google.com/event?action=TEMPLATE&tmeid=Nzk0cTNqc2FkdG5ua2JqMDloN3JpbnVtZjUgbGlvbmVscGF1bHVzQG0&tmsrc=lionelpaulus%40gmail.com).
As you can see, the join link is inside the event description.
I've anonymized my data for privacy but I respected the format.

Thanks in advance!

**Comment by jgoldhammer** [comment]
Hi @LionelPaulus ,

i have no access to the event. Please paste the link here. Thanks

**Comment by jgoldhammer** [comment]
Hi Lionel,

can you please post an example link for livestorm? I need to see how the url looks in general to implement support.
Thanks!

**Comment by LionelPaulus** [comment]
Hey @jgoldhammer, can I send it to you privately? Clicking on the link automatically authenticates you with my account and let you do actions under my name...

**Comment by jgoldhammer** [comment]
Hi @LionelPaulus 

does the link looks like this?

https://app.livestorm.co/p/cc113fd5-5de1-40a6-ba74-85d9c4892530/live?s=0231a8fb-fce9-48b0-9263-525f4234234234 

You can also post the url, but modify the url before like I did.
Thanks

**Comment by LionelPaulus** [comment]
Hi!

Yes it does.
On my side, I also had an `email` and `key` url query parameters in addition to the `s`:

https://app.livestorm.co/p/fb311b9e-4ae7-41c6-831c-xxxxxxxxxx/live?email=my@email.com&key=3cf911952d2exxxxx&s=ede30d94-32fc-4296-b047-xxxxxxxxx

**Comment by jgoldhammer** [comment]
Thanks @LionelPaulus -
So the pattern would be something like this:

`app.livestorm.co/p/<anything>/live?<anything>`

**Comment by LionelPaulus** [comment]
Correct 🙂

**Comment by jgoldhammer** [comment]
![image](https://user-images.githubusercontent.com/3872101/161385378-5892ec23-fe1c-47f3-8b90-a1b219e6d929.png)

@LionelPaulus - is this the correct icon?

**Comment by LionelPaulus** [comment]
Looking good! Yes, all good 👌
