### ISSUE TITLE
Feature: Support for Gong and Chorus links

### ISSUE THREAD

**Issue by rykermorgan** [leits/MeetingBar#418]
I'm getting more and more meeting links for Gong and Chorus, and cannot open these meetings from MeetingBar because they aren't recognized as meeting links.

I'd love for support to be added for both Gong and Chorus. Here are a couple example the url structure from recent meetings:

- **Chorus**: `https://go.chorus.ai/{{meeting id}}`
- **Gong**: `https://join.gong.io/{{company}}/{{user}}`

Let me know if I can provide additional context or color. 

Thanks!

**Comment by jgoldhammer** [comment]
Hi @rykermorgan - 
thanks for requesting two new services to be supported- I will try my best. 

Can you post modified urls which show how the meeting id, company and user look like?
Thanks

**Comment by rykermorgan** [comment]
@jgoldhammer sure thing

Here they are:
- *Gong*: `https://join.gong.io/mycompany/ryker.morgan`
  - company name is usually one word (from what I've seen), and usernames I've seen is first.last, but I don't know if this is universal or just consistent from the links I get from different companies. 
- *Chorus*: `https://go.chorus.ai/1234567890`
  - meeting id is a 10-digit code

Let me know if this isn't what you were after, and I can provide additional details.

**Comment by jgoldhammer** [comment]
I have created a PR to integrate Chorus and Gong.
It looks like this:
![image](https://user-images.githubusercontent.com/3872101/160016747-ace41811-a628-4513-b965-d6020833f686.png)

Are these the correct icons?

**Comment by rykermorgan** [comment]
Amazing! And yes, those are the correct icons.
