### ISSUE TITLE
Feature: Option to automatically hide next meeting when screensharing

### ISSUE THREAD

**Issue by malexmave** [leits/MeetingBar#419]
**Is your feature request related to a problem? Please describe.**
Similar to #206, I often find myself in an impromptu screensharing session. Now that the feature of hiding the name of the next meeting is implemented, I could hide it explicitly, but often forget.

**Describe the solution you'd like**
It would be great if Meetingbar could be set up to automatically enable the "hide meeting title" setting when screensharing starts, and disable it when it ends. I am not sure if this is even possible, but asking can't hurt :).

**Describe alternatives you've considered**
Maybe something could be done with the Shortcuts app, but that would likely be an even larger implementation effort.

**Additional context**
None

Thank you for building Meetingbar, I use it productively every day and will use this opportunity to make a donation 😊.

**Comment by malexmave** [comment]
Hi @jgoldhammer - sorry, I'm not an OS X developer, so I definitely don't know anything about this :(. We could leave the issue open and tag it with "help wanted" to see if someone else has any ideas, but if you think it is not possible, we can also close it.

**Comment by devnoname120** [comment]
I'm not sure sure how they do it but [Muzzle](https://muzzleapp.com/) has this feature. Unfortunately it's not open-source. Maybe they would be open to sharing this part if we ask nicely by email?

**Comment by jgoldhammer** [comment]
I have contracted Brian from Muzzle and wait for a feedback. Thanks @devnoname120 for the pointer.

**Comment by devnoname120** [comment]
@jgoldhammer Did you hear back from him? 🙏

**Comment by leits** [comment]
I will close the issue now for two reasons: there is no info from Muzzle developer and it looks like part of accessibility permission that I'm not sure we want to ask the user for.
