### ISSUE TITLE
Bug: code in preferences_advanced_apple_script_placeholder is translated

### ISSUE THREAD

**Issue by batmac** [leits/MeetingBar#422]
**App version**
3.10.1

**Describe the bug**
Some languages have the placeholder applescript code executed when joining translated, and so it doesn't work ootb.
You can see it here: https://hosted.weblate.org/translate/meetingbar/app/fr/?checksum=ce122dde10d76982&sort_by=-priority,position#translations

**Expected behavior**
don't translate the 'tell application "Music" to pause' part.

**Comment by jgoldhammer** [comment]
Hi @leits - I have also corrected in weblate. Maybe you can take a look?

**Comment by leits** [comment]
Thanks, @jgoldhammer! 
Merged #432

**Comment by batmac** [comment]
thanks!😃
