### ISSUE TITLE
Bug: Wrong icon appearing in status bar

### ISSUE THREAD

**Issue by JordanTranchina** [leits/MeetingBar#428]
**App version**
3.10.1

**Describe the bug**
Status Bar Icon is a checkbox & calendar instead of just a calendar item

**Expected behavior**
Only a calendar icon

**Screenshots**
![Screen Shot 2022-03-27 at 5 55 23 PM](https://user-images.githubusercontent.com/41443492/160304666-c1a7f254-65c0-459f-8a16-3cd9297861e5.png)

**Desktop (please complete the following information):**
 - macOS version: 11.6.4

**Comment by jgoldhammer** [comment]
Hi @JordanTranchina ,

thanks for your request. This icon in the statusbar indicates that there are no upcoming meetings.
The icon setting in your screenshot only relates to the icon if there are upcoming meetings.

What do you think? Should we introduce a new setting for the icon when no meetings are upcoming?
