### ISSUE TITLE
Bug: Not appearing in menu bar

### ISSUE THREAD

**Issue by scaraux** [leits/MeetingBar#429]
**App version**

3.10.1

**Describe the bug**

It's not really a bug but I wanted to report that in case people run through the same issue
I noticed my MeetingBar wasn't displayed anymore, and that's because I probably had too many items in the menu bar, removing the spotlight item immediately gave space for MeetingBar to show up again.

<img width="689" alt="CleanShot 2022-03-28 at 11 11 08@2x" src="https://user-images.githubusercontent.com/26309761/160460371-4546f479-1e03-4afc-911d-b817529c2a1f.png">

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - macOS version: [e.g. 10.15.4]

**Additional context**

**Comment by 0bmxa** [comment]
I'm observing a very similar behavior. The MeetingBar menu item completely disappears when there is not enough space for it to fit into the menu bar. There's no indication that MeetingBar is still running, the item is just completely gone.

This is especially an issue on the new MacBooks with the "notch", as there is quite a bit less space for menu bar items.
@scaraux is your issue as well from a MacBook (Pro) with the "notch", or is this on a "full width" menu bar?

A workaround is to manually limit the number of characters in the event title, but as the available space might change with menu bar items showing and disappearing, it would be ideal if we could detect whether the item is currently visible and automatically shorten the title as appropriate.
<img width="502" src="https://user-images.githubusercontent.com/15385891/161272470-e0eb138c-7356-42ae-bb60-807487f9e8e2.png">

**Comment by jgoldhammer** [comment]
I have investigated some time to find a good solution.
Meetingbar can now detect if the app is not displayed in the statusbar and will notify the user by default.

![image](https://user-images.githubusercontent.com/3872101/161434416-fd42fb20-a6b2-4edc-b741-9f39338ff0ac.png)

The user can decide to stop these notifications by deactivating the notifications in the preferences dialog.

![image](https://user-images.githubusercontent.com/3872101/161434456-f00da86f-a98a-4aca-95bd-83fbdf5073ab.png)

This notification is displayed if you cannot see meetingbar in the statusbar as well.
What do you think @0bmxa and @scaraux ?
