### ISSUE TITLE
Can't join Zoom meeting

### ISSUE THREAD

**Issue by sn0wyfall** [leits/MeetingBar#43]
**Describe the bug**
I have a Zoom meeting in my calendar with the URL in it. When I click "join next meeting" it doesn't seem to do anything. 

**To Reproduce**
1. Add meeting in calendar with zoom URL for later today
2. Try to join it using menu bar app

**Expected behavior**

Should open Zoom _directly_ (i.e. not web browser)

**Desktop (please complete the following information):**
 - macOS version: 10.15.5

**Comment by globau** [comment]
> Should open Zoom directly (i.e. not web browser)

That's https://github.com/leits/MeetingBar/issues/11

**Comment by sn0wyfall** [comment]
@globau Awesome, thanks! It's even added in the next release it seems? Which is super cool.

However, I still can't open any Zoom meetings from the menu bar. I have an event coming up soon, but when I click "join meeting" nothing happens. Isn't Safari supposed to open?

**Comment by insipidlight** [comment]
I'm having this issue too. Half my meetings are in Google Meet and half in Zoom. Clicking "Join next event" doesn't do anything. There's no documentation about where to actually put the meeting URL?

**Comment by sn0wyfall** [comment]
@insipidlight My understanding is that it should grab the meeting URL automatically from the calendar event. That's how Meeter does it. Idk about this though

**Comment by chaseadam** [comment]
I can report the same from #61 comments
> Zoom links aren't working, whether it's the default browser or the native Zoom app.

Attached is an example meeting entry in OS X Calendar

![image](https://user-images.githubusercontent.com/333031/91877788-77cfd400-ec4c-11ea-91ac-0a7712053062.png)
