### ISSUE TITLE
Feature: Hide events I have responded to as 'Maybe'

### ISSUE THREAD

**Issue by jhogendorn** [leits/MeetingBar#438]
**Is your feature request related to a problem? Please describe.**
I have a lot of meetings i need to be aware of but typically do not attend, so I respond as 'maybe'. I dont really want to know when they're coming up so can they be hidden?

**Describe the solution you'd like**
A preference setting to hide events where my attendance is marked as 'maybe'

**Describe alternatives you've considered**
I could respond no to these events but its kind of a problem, both practically and politically. I could also make a second calendar in each account and move these 'maybe' events to those calendars. Thats probably what I will do otherwise.

**Comment by jgoldhammer** [comment]
Hi @jhogendorn ,

thanks for your request. I think we have a setting for this.

![image](https://user-images.githubusercontent.com/3872101/163681125-aaf11915-fdee-48d1-94d5-746e72f45e83.png)

It basically allows you to hide those events completely or just mark them as inactive.
I will close the ticket. Please reopen if this does not work for you.

Thanks
Jens

**Comment by jhogendorn** [comment]
I dont believe this works for me unfortunately, as the events are not 'pending'. IE i have accepted the invite but as 'maybe' rather than 'yes'
