### ISSUE TITLE
Contacts acccess was NOT granted

### ISSUE THREAD

**Issue by wayneashleyberry** [leits/MeetingBar#44]
**Describe the bug**

The app does not start. I am seeing a ton of errors regarding being unable to access contacts. The app does not show under "Contacts" in Privacy settings though, so I cannot provide access manually.

**Screenshots**

<img width="1685" alt="Screenshot 2020-08-04 at 9 08 29 am" src="https://user-images.githubusercontent.com/727262/89269656-15c28580-d632-11ea-9793-51eff4d8bba0.png">

**Desktop (please complete the following information):**

64bit Mac OS X 10.15.6 19G73

**Comment by leits** [comment]
I assume that the program crash because of some other problem. Could you look at the logs further?

Contracts access request is the [old macOS bug](https://stackoverflow.com/questions/61103650/ekeventstore-requests-contacts-access-on-macos) but doesn't it crash the app.
