### ISSUE TITLE
🚀 Public beta 4.0 🚀  Direct Google Calendar integration

### ISSUE THREAD

**Issue by leits** [leits/MeetingBar#440]
Hi folks!

A new release with a huge number of new features is ready!
I need your feedback to make this version more stable.

----

### Major updates:
- #434 by @leits 
- #166 (merged) by @jgoldhammer (#148)
- #30 by @jgoldhammer 

### Features: 
- #387 by @niravbhimani53 
- #431 by @jgoldhammer 
- #425 by @jgoldhammer 
- #426 by @gianpispi
- #436 by @jgoldhammer 

----

### DMG is here: https://github.com/leits/MeetingBar/releases/download/v4.0/MeetingBar.dmg

-----

#### Thank you all for sharing your ideas, reporting bugs, and joining the discussion!

- #434 @sasaplus1
- #148 #166 #281 #350 @shadyabhi @jovobe @jverhoeks @nikjft
- #30 #274 @bberenberg @usmanity @hkdobrev @darthwalsh @AdeelK93 @jasiek @Laica-Lunasys @pietvanzoen @bigethan
- #417 @LionelPaulus
- #418 @rykermorgan
- #354 @ltaupiac @tizmagik @xeroxoid @rvadaga @david-dasilva

and many others who create&upvote issues and support MeetingBar via AppStore or on Patreon!

Special thanks to @jgoldhammer, who made most of these updates and actively participated in each discussion!

**Comment by jgoldhammer** [comment]
Great @leits! 

I really like the gmail integration - due to my work I will use macos calendar. 
The integration works really fine, especially the setup was working now without any problems.

After trying googlemail integration out and switching back to MacOS Calendar, the screen still shows the googlemail calendar entries instead of the macos calendars...

![image](https://user-images.githubusercontent.com/3872101/165253897-0ba8571b-82d3-4d66-a3f4-5835ccc06ed2.png)

**Comment by jgoldhammer** [comment]
After closing the preferences dialog and reopen it, it will show the correct calendar list...

![image](https://user-images.githubusercontent.com/3872101/165254343-bfb504d5-756b-4bf6-9c3c-894ee5ce92a1.png)

**Comment by bigethan** [comment]
Auto join! thank you!  Though I might be the only person using MeetingBar in non-dark mode, as the txt is white on white:
![Screen Shot 2022-04-26 at 9 17 19 AM](https://user-images.githubusercontent.com/627/165346891-df6c5e79-df02-4f52-a8c4-2ac5358576f6.png)

**Comment by niravbhimani53** [comment]
Hi @leits @jgoldhammer, I noticed that the issue number is missing for this feature in the _Whats New_ window.

Should the issue number be mentioned or need to be removed? 

<img width="1702" alt="Screen Shot 2022-04-27 at 6 13 07 pm" src="https://user-images.githubusercontent.com/12537912/165473835-2abf5441-644d-4fed-a4c7-a82fdf29a3a9.png">

**Comment by leits** [comment]
> Auto join! thank you! Though I might be the only person using MeetingBar in non-dark mode, as the txt is white on white: ![Screen Shot 2022-04-26 at 9 17 19 AM](https://user-images.githubusercontent.com/627/165346891-df6c5e79-df02-4f52-a8c4-2ac5358576f6.png)

Thanks, @bigethan, I'll take a look.

> Hi @leits @jgoldhammer, in the What's New window, one of the feature is missing the MR number.

Thanks, @niravbhimani53, I'll update changelog!

**Comment by leits** [comment]
> In the new version, it cannot detect Zoom links in meetings when using the Google Calendar integration. It works when using the macOS Calendar sync. The meetings are still listed via Google, but it says "link not found or your meeting service is not supported". It works immediately when switching calendar sync method.
> 
> The Zoom links use the normal Zoom <> Google integration.

Thanks, @hkdobrev. I managed to reproduce the bug and I'll fix it!

**Comment by leits** [comment]
@bigethan  @niravbhimani53 @hkdobrev uploaded a new version with fixes!
DMG is here: https://github.com/leits/MeetingBar/releases/download/v4.0/MeetingBar.dmg

**Comment by jgoldhammer** [comment]
> @bigethan @niravbhimani53 @hkdobrev uploaded a new version with fixes! DMG is here: https://github.com/leits/MeetingBar/releases/download/v4.0/MeetingBar.dmg

Great! My reported bug is fixed...

**Comment by leits** [comment]
@jgoldhammer, I didn't mention you above because I haven't made a fix yet 😅
It looks like this bug is reproducing erratically.

**Comment by bigethan** [comment]
Not sure if this was present in the previous version, but the dropdown seems to flicker for me every couple of seconds:

https://user-images.githubusercontent.com/627/166560818-37176f75-8a9b-45e2-8934-ac08456633b1.mov

**Comment by jgoldhammer** [comment]
Yes, this was also

> Not sure if this was present in the previous version, but the dropdown seems to flicker for me every couple of seconds:
> 
>  Screen.Recording.2022-05-03.at.1.29.24.PM.mov

Yes, this flickering exists also in older versions because we update the menu items every x seconds

**Comment by jgoldhammer** [comment]
After using the feature "Automatically Join Meeting" a couple of days - yes, it is really cool , but sometimes it is a little bit unexpected that a new meeting is started without interaction. The problem is that it also shows up when you are in another meeting. So maybe sensitive information will be shown.

My idea is:
- show up (optional) a notification dialog in the middle of the screen where the user has to confirm that the meeting 
- the notification dialog will be hidden after 10 seconds and the meeting is starting
- include a new setting in the preferences dialog to enable or disable this notification dialog

What do you think @leits?

**Comment by bigethan** [comment]
> After using the feature "Automatically Join Meeting" a couple of days - yes, it is really cool , but...

Agree with @jgoldhammer - there needs to be maybe just a light confirmation in some form.

A different app that does this in a nice way is [Tandem](https://blog.tandem.chat/auto-join-meetings/) - it pops up a non-native notification ~5 minutes before the meeting to say "Hey there's a Zoom coming up, click to auto-join 1 minute before"

**Comment by leits** [comment]
It's a good idea. Let's try to improve this feature with the next release.

**Comment by leits** [comment]
RELEASED!
