### ISSUE TITLE
Feature: Open teams link in any browser, not necessary the default one

### ISSUE THREAD

**Issue by jdupont22** [leits/MeetingBar#441]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I would like to choose any browser to open my team link. Today, only the default browser and the team app is available.
My default browser is "Safari", i would like to open with "Brave"

**Describe alternatives you've considered**

**Additional context**

**Comment by thomaswitt** [comment]
I would second that, also for Zoom links as well.

**Comment by leits** [comment]
Done!
