### ISSUE TITLE
Feature: Change notification sound

### ISSUE THREAD

**Issue by jvzaniolo** [leits/MeetingBar#444]
**Is your feature request related to a problem? Please describe.**
The notification sound is the same as the sound for messages and I always find myself not paying attention to it because my brain thinks it's only a message.

**Describe the solution you'd like**
Change the notification sound to the same sound Calendar.app makes for upcoming meetings

**Describe alternatives you've considered**
Find another sound that relates to meetings

**Additional context**
N/A

**Comment by leits** [comment]
Thanks for the request, @jvzaniolo!
Sorry, but it doesn't look like a problem for extending already extensive app settings.
