### ISSUE TITLE
Feature: Copy meeting URL to clipboard

### ISSUE THREAD

**Issue by michaelpearson** [leits/MeetingBar#447]
**Is your feature request related to a problem? Please describe.**
Often people are focused or busy and forget that they have a meeting coming up. It's pretty common practice in my org to message that person directly and include a link to the meeting for them to quickly join.

**Describe the solution you'd like**
I think It could be helpful to add the ability into meeting bar to copy the join url to the clipboard. I'd imagine it could be done with an option in the "quick actions" menu.

**Comment by jgoldhammer** [comment]
Hi @michaelpearson ,

When you enable the details as submenu in the preferences, you should see an action to copy the url.
I hope this will work for you. If not, you can reopen the ticket. Thanks
