### ISSUE TITLE
Feature: Dismiss current active meeting

### ISSUE THREAD

**Issue by bitboxer** [leits/MeetingBar#452]
**Is your feature request related to a problem? Please describe.**

I often have meetings that end earlier than expected, and I would love to dismiss them in the meeting bar as "done" so that it just shows the next meeting.

**Describe the solution you'd like**

Maybe an action item in the Menubar popup saying: "Dismiss this meeting" or something similar to hide it and show the next meeting.

**Describe alternatives you've considered**

Sadly, nothing came up when thinking about it apart from deleting the event in the calendar.

**Comment by leits** [comment]
I'll close it as a duplicate.
@bitboxer, please follow #469.
