### ISSUE TITLE
Bug: The filtering of events via regex (to hide them) is not working anymore

### ISSUE THREAD

**Issue by fkrauthan** [leits/MeetingBar#454]
**App version**: 4.0.4

**Installation source**
- Homebrew

**Describe the bug**
The filtering of events via regex (to hide them) is not working anymore

**To Reproduce**
1. Create some filter rules (e.g. `Focus Time \(via Clockwise\)`)
2. Create an event with title `Focus Time (via Clockwise)`
3. Check if events are filtered

**Expected behavior**
The two regex rules should have filtered out some events.

**Desktop (please complete the following information):**
 - macOS version: 12.3.1

**Comment by JordanTranchina** [comment]
I'm seeing this as well!
<img width="653" alt="Screen Shot 2022-05-17 at 12 34 56 AM" src="https://user-images.githubusercontent.com/41443492/168736510-27c34b52-a385-4ed6-89e8-072225d83ded.png">
<img width="812" alt="Screen Shot 2022-05-17 at 12 35 01 AM" src="https://user-images.githubusercontent.com/41443492/168736512-bab33f37-655a-4d90-843d-0f90b62600a9.png">

**Comment by fkrauthan** [comment]
@leits yes version `4.0.5` fixes the issue. Thank you so much for the quick turnaround.
