### ISSUE TITLE
Bug: authuser parameter missing in Google Meet links

### ISSUE THREAD

**Issue by jeffgreco** [leits/MeetingBar#456]
**App version**
4.0.4

**Installation source**
- AppStore

**Describe the bug**
Copying or opening a meeting link no longer redirects to the proper Google account automatically if a user is logged into multiple.

**To Reproduce**
1. Log into multiple Google accounts
2. Create an event in the account in the second position
3. Trigger "Join Current Meeting"

**Expected behavior**
The meet.google.com link opens up with the correct authuser URL parameter included.

**Desktop (please complete the following information):**
 - macOS version 12.3.1

**Comment by leits** [comment]
@jeffgreco , thanks for the report!
Looks like I found out where the problem was and fixed it.
Can you try this version? https://github.com/leits/MeetingBar/releases/tag/v4.0.5

**Comment by jeffgreco** [comment]
Back in business! Great work :)

**Comment by jeffgreco** [comment]
Hi! This issue has reemerged.

**Comment by cjohnson78** [comment]
@jeffgreco If you primarily Meet with a certain Google User (I primarily use authuser=1 for work, for example), this is a temporary workaround:  https://chrome.google.com/webstore/detail/redirector/ocgpenflpmgnfapjedencafcfakcekcd?hl=en

I created a RegEx to append ?authuser=1 to any Meet URLs that try to load:

Redirect:	^(https://meet.google.com/[^\?]+)$
to:	$1?authuser=1
