### ISSUE TITLE
Feature: Auto dismiss notifications after a set number of seconds

### ISSUE THREAD

**Issue by mlcampbe** [leits/MeetingBar#459]
**Is your feature request related to a problem? Please describe.**
I get a notification for an upcoming meeting as expected. But, I have to manually click the 'x' to dismiss that notification to get rid of it.

**Describe the solution you'd like**
A setting that will automatically dismiss the notification after a defined period of seconds

**Describe alternatives you've considered**

**Additional context**

**Comment by leits** [comment]
Hi @mlcampbe,
Thanks for the request. It's by design, but you can change this for yourself in System Preferences. In Notifications section find MeetingBar and change the alert style from "Alert" to "Banner".
