### ISSUE TITLE
Search location field for meeting link

### ISSUE THREAD

**Issue by jt2k** [leits/MeetingBar#46]
**Is your feature request related to a problem? Please describe.**
Some of my meeting events use the location field to store a Zoom or Google Meet link. I cannot join a meeting when the meeting link is in the event's location field.

**Describe the solution you'd like**
In addition to looking in the event notes, look for meeting links in the [location property](https://developer.apple.com/documentation/eventkit/ekcalendaritem/1507269-location). It might even make sense to check the location field first.

Thank you!

**Comment by cromulus** [comment]
This! My colleagues all put the meeting link in the location.

Thanks!

**Comment by AnthonySmith01** [comment]
I'd also love to see this, particuarly in these COVID times.

Still a great addon but this would be a nice to have, I might have a go at a PR if no one else is onto it.
