### ISSUE TITLE
Bug: MeetingBar randomly quits many times per day

### ISSUE THREAD

**Issue by paul-gauthier** [leits/MeetingBar#463]
**App version**
This has happened with every version I have used over the last ~year. I upgrade frequently, hoping that new versions might fix this bug. They don't.

**Installation source**
Release dmg from GitHub.

**Describe the bug**
MeetingBar just silently exits many times per day. I notice when I hit the hotkey to launch into my next meeting, and it's no longer active in the menu bar.

**To Reproduce**
I don't know what triggers the exit. It happens very often though.

**Expected behavior**
MeetingBar should continue running and never quit.

**Screenshots**
N/A

**Desktop (please complete the following information):**
MacOS Big Sur  11.6.6 (20G624). I believe this bug happened on prior versions of MacOS that I've had installed.

**Additional context**
I find stack traces in Console. Example below:

```
Process:               MeetingBar [829]
Path:                  /Applications/MeetingBar.app/Contents/MacOS/MeetingBar
Identifier:            leits.MeetingBar
Version:               3.10.1 (131)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           MeetingBar [829]
User ID:               501

Date/Time:             2022-05-24 15:31:49.068 -0300
OS Version:            macOS 11.6.6 (20G624)
Report Version:        12
Bridge OS Version:     6.5 (19P5071)
Anonymous UUID:        3B449A5F-B03A-E161-6E14-C03F6289B52B

Sleep/Wake UUID:       4336E0B8-16F2-4D07-824C-86655464ED9E

Time Awake Since Boot: 240000 seconds
Time Since Wake:       2500 seconds

System Integrity Protection: enabled

Crashed Thread:        10  Dispatch queue: com.apple.root.user-interactive-qos

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSWindow drag regions should only be invalidated on the Main Thread!'
terminating with uncaught exception of type NSException
abort() called```

**Comment by leits** [comment]
Hi @paul-gauthier,
Can you check the latest version? Looks like it's already fixed!
