### ISSUE TITLE
Bug: WebEx URLs not recognized

### ISSUE THREAD

**Issue by JohnLockeNJ** [leits/MeetingBar#464]
**App version**
4.0.5

**Installation source**
manual

**Describe the bug**
Meetings with Cisco WebEx urls (ending in webex.com) are not recognized as containing valid meeting URLs, even though Cisco WebEx is listed as a supported service.

**To Reproduce**
1. Accept a WebEx meeting 
2. MeetingBar does not recognize the URL as a meeting link

**Expected behavior**
I expected it to recognize those URLs as it does with other supported meeting types. Ideally it would even launch the WebEx app directly but what I expected was for it to at least recognize the URL and facilitate launching the browser to join the meeting.

**Desktop (please complete the following information):**
 - macOS version: 12.2.1 Monterey, MacBook Pro 2021 16", Apple Silicon

**Additional context**
I added a regex as a workaround. 
(https?:\/\/(.+?\.)?webex\.com(\/[A-Za-z0-9\-\._~:\/\?#\[\]@!$&'\(\)\*\+,;\=]*)?)

**Comment by leits** [comment]
Thanks for the report!
Could you also share some example link?

**Comment by leits** [comment]
Closed due to no response.
