### ISSUE TITLE
Question: Android equivalent

### ISSUE THREAD

**Issue by devnoname120** [leits/MeetingBar#466]
Does anyone know if there is a similar app but for Android?

I'd like to have a permanent notification displaying the time until the next meeting, as well as how much time is remaining in the current meeting. I don't need to join conferences from my phone.

If it doesn't exist, I'm going to create it on my own.

**Comment by leits** [comment]
Hi @devnoname120,
This seems like a good idea for your own app because I haven't found any similar apps for Android.

**Comment by akirk** [comment]
I was also looking for this and found [Calendar Notify](https://play.google.com/store/apps/details?id=com.cliffcawley.calendarnotify&hl=en). Not open source and has a one-time premium purchase but works well for me.

**Comment by devnoname120** [comment]
> I was also looking for this and found [Calendar Notify](https://play.google.com/store/apps/details?id=com.cliffcawley.calendarnotify&hl=en). Not open source and has a one-time premium purchase but works well for me.

Thanks a lot! I'll give it a try
