### ISSUE TITLE
Bug: Newly accepted meetings are not shown in the Bar

### ISSUE THREAD

**Issue by sshresthaEG** [leits/MeetingBar#467]
**App version**
3.2.0

**Installation source**
- AppStore

**Describe the bug**
If I accept a new meeting invite, it won't show up in the list of meetings in the menu

**To Reproduce**
1. Create a new Event in Google Calendar
2. In MeetingBar menu, click Quick Actions -> Refresh Sources
3. Wait for some time.
4. Check if you see the new Event created shows up

**Expected behavior**
New event shows up in the MeetingBar menu

**Screenshots**
New event not showing up
![image](https://user-images.githubusercontent.com/62610476/171912602-c0c26470-c0d5-4868-96ad-9b8dc52b1bc7.png)

**Desktop (please complete the following information):**
 - macOS version: 12.4

**Comment by jgoldhammer** [comment]
Thanks for the bug report.
I have two questions:

- Can you please check if your macos calendar contains the new event? 
- Can you please update Meetingbar to the newest version 4.0.5 and check again?

Thanks

**Comment by jgoldhammer** [comment]
As there was no feedback, I will close the issue now. Feel free @sshresthaEG  to reopen the issue again.
