### ISSUE TITLE
Feature: Support for Google Meet Streams

### ISSUE THREAD

**Issue by jaredgaut** [leits/MeetingBar#468]
**Is your feature request related to a problem? Please describe.**
Google calendar events that only have a Google Meet livestream attached fail to launch the stream.

<img width="447" alt="screenshot 2022-06-08 at 08 58 39 " src="https://user-images.githubusercontent.com/1099620/172703076-2471c208-317c-4914-8efe-cbf33a0d3781.png">

<img width="250" alt="screenshot 2022-06-08 at 08 58 19 " src="https://user-images.githubusercontent.com/1099620/172702856-4587a4b0-2efb-48a8-9c6b-3a0c0b7b434a.png">

**Describe the solution you'd like**
Browser set for "Open Google Meet link in" should launch the livestream.

**Describe alternatives you've considered**
N/A

**Additional context**
Example pattern: `https://stream.meet.google.com/stream/abc12ab1-abc1-1234-123a-a1234a1abc12`

**Comment by jgoldhammer** [comment]
Hi @jaredgaut.

Thanks for reporting this issue. I guess, we do not recognize the url pattern well. So can you please update the issue with the necessary pattern? Is it https://stream.meet.google.com/stream/<anything> only or are there any other links to support?

Thanks
Jens

**Comment by jaredgaut** [comment]
`https://stream.meet.google.com/stream/` is the only one I've seen.

Example full stream link: `https://stream.meet.google.com/stream/abc12ab1-abc1-1234-123a-a1234a1abc12`

**Comment by leits** [comment]
It should work: https://github.com/leits/MeetingBar/blob/master/MeetingBar/MeetingServices.swift#L269

Do you have this issue still?
