### ISSUE TITLE
Feature: less memory usage

### ISSUE THREAD

**Issue by adamlaz** [leits/MeetingBar#475]
**Is your feature request related to a problem? Please describe.**
MeetingBar consistently uses 700+MB of memory, on some machines this is causing issues. 

**Describe the solution you'd like**
IDK! But, if there is anything that could be done so it uses less, that'd be great.

**Additional context**
It doesn't feel right that this mostly background app is consistently towards the top of the list on memory usage. Love the app, but want to file this feature request because I've noticed this issue on my mac that only has 16GB ram 😢 
![screenshot-Activity Monitor-Activity Monitor on 2022-07-13 at 12 46 13PM](https://user-images.githubusercontent.com/2012381/178787527-cf064781-9df6-462b-a460-ebcf9bd712ec.png)

**Comment by benbeilharz-beem** [comment]
Yes, I only have 8MB of memory (M2 macbook) and found MeetingBar was using 1.2GB

**Comment by leits** [comment]
Hi @adamlaz  @benbeilharz-beem,
Can you check the latest version?
https://github.com/leits/MeetingBar/releases/download/v4.0.6/MeetingBar.dmg

I have made some optimizations and want to check if the situation has improved.

**Comment by tomschlenkhoff** [comment]
I can comment using 4.0.6 and a M2 (all updated): MeetingBar is running for a few hours now and shows with 36,3 MB RAM usage. Very decent!

**Comment by adamlaz** [comment]
@leits  -- situation has definitely improved! Thank you for looking into this and making the optimizations. 

The app now sits under 30MB, an incredible ~30x improvement! Awesome job. This app is definitely sticking around as a must-have on my work computers. 

![screenshot-Activity Monitor-Activity Monitor on 2022-08-22 at 10 01 03AM](https://user-images.githubusercontent.com/2012381/185939827-50ad33e2-7c45-47bd-ae64-0714995de8b7.png)

**Comment by alexnault** [comment]
I can also attest: MeetingBar went from ~760MB to ~16MB of memory usage after upgrading from 4.0.5 to 4.0.6. Thank you @leits!

**Comment by noriHanda** [comment]
I am using 4.0.6 but still encountering this excessive use of memory: 1.37GB.
```
specs:
- MacOS 12.6（21G115）
- MacBook Pro (13-inch, 2019, Two Thunderbolt 3 ports)
```

<img width="964" alt="image" src="https://user-images.githubusercontent.com/18581236/205293709-8c404061-d86a-457b-9d92-5098ca25e661.png">

**Comment by AdrianFahrbach** [comment]
I got the same Issue on 4.2.2.
<img width="739" alt="screenshot 2023-03-07 at 10 52 16@2x" src="https://user-images.githubusercontent.com/45072099/223387251-300075e9-a47a-469b-a27f-f66cd248133b.png">

I regularly use programs that need a lot of ram, therefore I try to avoid every unnecessary usage.
As much as I like this app, this is something that I can't really work with.

**Comment by leits** [comment]
Included a few optimizations in the 4.5 version. Please, check it out!

**Comment by gido** [comment]
I will try 4.5 and give feedback as version `4.4.0` is eating 1.3 GB on my Mac M1.

(Great app! I use it everyday!)

**Comment by leits** [comment]
Thanks @gido! 

Looking forward to your feedback!
Also, there is already 4.5.1, check it out

**Comment by leits** [comment]
I'm closing this topic due to inactivity.
Feel free to reopen the issue if the problem still exists.
