### ISSUE TITLE
Feature: Support Google Meet Progressive Web App (PWA)

### ISSUE THREAD

**Issue by dserodio** [leits/MeetingBar#481]
I use the [Google Meet Progressive Web App](https://support.google.com/chrome/answer/9658361) (PWA), and I'd like to be able to use it when I open Google Meet links in MeetingBar. When I try to change the **Open Google Meet links in** option, this PWA is not available.
![image](https://user-images.githubusercontent.com/233589/180306537-237889dc-7c95-4f81-af03-443d31ea4db1.png)

Thanks for this amazing app!

**Comment by dserodio** [comment]
Update: I just noticed that it's possible to manually add browsers to MeetingBar; however, I added the Google Meet PWA and when I try to use it to join a Google Meet meeting I get this error from macOS:
![image](https://user-images.githubusercontent.com/233589/180488317-803f1d48-3505-4b82-a8c7-b80351e29180.png)
And this notification from MeetingBar:
![image](https://user-images.githubusercontent.com/233589/180488671-40490f10-7ea3-4db0-b9d1-08187a347b2d.png)

**Comment by leits** [comment]
Sorry, but Google Meet PWA still doesn't have the possibility to open a certain event from the URL.
