### ISSUE TITLE
Bug: Menu bar item doesn't show a next-day meeting even if enabled

### ISSUE THREAD

**Issue by jaklan** [leits/MeetingBar#485]
**App version**
4.0.6

**Installation source**
homebrew

**Describe the bug**
- In the past, when I had the `Show events for` setting set to `today and tomorrow`, if the closest meeting took place the next day - it was displayed in the macOS menu bar.
- Currently, if I don't have any more meetings on a given day - I simply see the _no more meetings_ icon. The meeting from the next day will be displayed after midnight, but no earlier.

I'm not sure if it's a bug or a feature actually, but I would really like to preserve the previous behaviour.

**Desktop (please complete the following information):**
 - macOS Monterey 12.4

**Comment by leits** [comment]
Thanks for the report!
I'll return the previous behavior in the next release.

https://github.com/leits/MeetingBar/commit/4d2d946aeace202b59dc79bc06ca2532ca61a30e
