### ISSUE TITLE
Feature: Support for Zoho Cliq application

### ISSUE THREAD

**Issue by onevoone** [leits/MeetingBar#486]
**Is your feature request related to a problem? Please describe.**
I use Zoho tools, Zoho Click as Slack lets me chat with teammates and participate in in-app meetings.

Thanks for app!

**Comment by leits** [comment]
Hi @onevoone!
Thanks for the request!
Can you also share some example meeting URLs? So I can add a regex in the app for recognition.

**Comment by onevoone** [comment]
@leits Hi, thanks. example meeting URL - https://cliq.zoho.eu/meetings/[meeting-id]
