### ISSUE TITLE
Bug: 24 hour event isn't treated as an all-day event

### ISSUE THREAD

**Issue by johnbillion** [leits/MeetingBar#487]
**App version**

4.0.5

**Installation source**

- homebrew

**Describe the bug**

I have an event in my calendar today which is a 24 hour event that runs from 00:00 to 00:00. In the MeetingBar preferences the "All-day events" option is set to "hide" but the event still appears.

I'm using the Google Calendar API provider.

**To Reproduce**

1. Create a calendar event that runs from 00:00 one day to 00:00 the next
2. In the MeetingBar preferences, hide all-day events
3. Observe that the event still appears in MeetingBar

**Expected behavior**

This event should be treated as an all-day event and hidden if necessary.

**Screenshots**

<img width="400" alt="" src="https://user-images.githubusercontent.com/208434/181464915-e53f2446-7a79-4ef3-850d-04b521aee4f5.png">

**Desktop (please complete the following information):**
 - macOS version: 12.3

**Additional context**

MeetingBar is a great app :)

**Comment by leits** [comment]
Thanks, @johnbillion!
Added fix to the next release scope!
