### ISSUE TITLE
Feature: Don't automatically open calls on maybe meets

### ISSUE THREAD

**Issue by GianlucaBobbioScale** [leits/MeetingBar#489]
**Is your feature request related to a problem? Please describe.**
Zoom auto-open on _maybe_ meets (gcalendar)

**Describe the solution you'd like**
Don't open automatically on _maybe_ meets (gcalendar)

**Describe alternatives you've considered**
I wait until it opens, and then close. Not the best experience.

**Comment by dtseiler** [comment]
+1

**Comment by leits** [comment]
Hi @GianlucaBobbioScale & @dtseiler,
This problem is fixed in v4.1.0.

Feel free to reopen the issue if it still reproduces for you!
