### ISSUE TITLE
Bug: quick actions submenu flickers every 5s

### ISSUE THREAD

**Issue by mjvmroz** [leits/MeetingBar#491]
**App version**
4.0.6

**Installation source**
- AppStore

**Describe the bug**
The quick actions menu flickers every 5s.

**To Reproduce**
1. Click on the MeetingBar menu bar item to expand its menu
2. Hover on "Quick actions" for up to five seconds
3. Observe the flicker
4. Hover on any sub-item under "Quick actions" for up to five seconds
5. Observe that the flicker now causes the menu to close.

**Expected behavior**
The menu should be stable.

**Desktop (please complete the following information):**
 - macOS version: 12.4

**Additional context**
Looks like it's due to `updateMenu` nuking the whole menu and rebuilding it from scratch. It doesn't seem to cause any issues for top-level items, but can be annoying for submenus if you get unlucky enough to see the flicker when you're traversing that menu, which is reasonably likely given the high frequency.

Since the sub-menu isn't informed by anything updated on a clock, the application could be modified to be more selective and only remove + recreate actual meeting items.

**Comment by dhleong** [comment]
This happens for mousing over event details as well FWIW.

**Comment by leits** [comment]
Thanks for the report!
Added fix to the next release scope (4.2.).

**Comment by leits** [comment]
I need to reopen the issue because the implementation works not in an expected way. It helps to avoid flickering but also adds a very strange delay for menu updates.

**Comment by kud** [comment]
Hey folks,

It's not only for Quick actions. It's any submenu.

Is it because you fetch and refresh every 5s the app?

**Comment by viewsourc3** [comment]
I also seem to experiment this bug, on v. 4.2.2. Refreshes every 5 seconds which makes the menu flicker and hard to select/click on text.
