### ISSUE TITLE
Feature: Hide menubar icon when there is no meeting shown

### ISSUE THREAD

**Issue by chrisgrieser** [leits/MeetingBar#492]
Pretty much what the subject says. Right now, meetingbar always shows an icon. However, I'd prefer it to only remove the icon altogether, when there is no upcoming meeting to display.

I am aware of apps like Dozer or Vanilla or Bartender which can hide menu bar items, however, they are not a solution since I *do* want meetingbar to be visible when there is an upcoming meeting.

Nonetheless, thanks for this useful app!

**Comment by EdsonBittencourt** [comment]
Exactly what I was searching for. If we had a command to list the next meetings, we would be able to do it via Bartender or some similar solution.

**Comment by leits** [comment]
Hi folks,
Thank you for your request. But I need to dismiss it because the menu bar item is the only way to interact with the app. This change may break the access flow for many users. There is no other way to even check if the program is still working properly.
