### ISSUE TITLE
Bug: Not updating events unless you restart app

### ISSUE THREAD

**Issue by alexec** [leits/MeetingBar#493]
**App version**

4.0.6

**Installation source**

AppStore

**Describe the bug**

When I add events to my calendar, they do not sync either automatically, or where I click "Refresh sources"

**To Reproduce**

1. Add a new event.
2. Wait for event to appear in Calendar
3. Wait forever
4. Event does not appear in Meeting Bar. 
5. Click "Refresh sources"6. 
6. Event still does not appear in Meeting Bar. 
7. Close and re-open Meeting Bar.
8. Event now appears.9. 

This makes Meeting Bar unusable. I need to trust it to correctly notfiy me of meetings.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - macOS version: [e.g. 10.15.4]

**Additional context**

**Comment by msztolcman** [comment]
Same issue here. Meeting bar has become unusable :( Need to remember about restarting all the time.

**Comment by leits** [comment]
Hi, @alexec @msztolcman.
Are you using macOS Calendar or a direct connection to Google Calendar as the data source?
If Calendar is macOS, can you check if the events are updating in the Calendar app?

**Comment by msztolcman** [comment]
Hi @leits ,
I am using it with macOS Calendar app. And yes, events appears in Calendar, after manual or automatic refreshing.

I've done small test: I've created an event in my own calendar. It appears in MeetingBar on one laptop after minute or two, but it doeasn't appear on second one. The most significant difference between my computers is one is Intel (works fine here), second one is Apple M1 (doesn't work). Maybe this is an issue?

**Comment by leits** [comment]
Can you check your calendar update time in the Calendar app settings? Here's the instruction: https://support.apple.com/en-gb/guide/calendar/icl1024/mac

Because "Refresh sources" only ask the Calendar app to update calendar info.

**Comment by msztolcman** [comment]
On Intel based I have refresh every 15 minutes, on Apple M1 based one there is 5 minutes.

**Comment by alexec** [comment]
I don't think this can be about referesh interval. It only correctly updates when I close and re-open meeting bar.

**Comment by leits** [comment]
> After some testing, I can confirm this is an issue with macos/calendar/exchange syncing. See here: https://discussions.apple.com/thread/253787531
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/7fd55c57bb5393d69c965d33caf936a71e362b4822bf26de092920cd47f36782/68747470733a2f2f636f6d6d756e69746965732e6170706c652e636f6d2f656e323032323036313530313332312f7075626c69632f6173736574732f66617669636f6e2e69636f">**[Exchange calendar not syncing in macOS Mo… - Apple Community](https://discussions.apple.com/thread/253787531)**

I hope that Apple will fix this soon!
