### ISSUE TITLE
Bug: launch after login not work

### ISSUE THREAD

**Issue by hongbeomi** [leits/MeetingBar#494]
**App version**
- 4.0.6

**Installation source**
- AppStore

**Describe the bug**
launch after login not work!

**To Reproduce**
1. turn off the mac

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - macOS version: [Monterey 12.2]

**Additional context**

**Comment by pietrorea** [comment]
Also happened to me, was about to open an issue

**Comment by GianlucaBobbio** [comment]
Not working for me neither!

**Comment by shnako** [comment]
Same here.

**Comment by yildirimatcioglu** [comment]
Same here MacOS Monterey 12.5.1 (21G83)

**Comment by mksglu** [comment]
Same here guys

**Comment by nedl86** [comment]
Also no longer working for me after updating to MacOS Monterey 12.6

**Comment by leits** [comment]
Thanks for the reports!

**Comment by leits** [comment]
@jogendra could you help here?

**Comment by PyvesB** [comment]
I just switched from an Intel-based 2020 MacBook Pro to the new M1 Max. Both are running Monterey 12.6.1, but interestingly only the new M1 seems to be affected by this issue. Not sure whether it's coincidental, if I ended up with different settings somewhere, or if it's actually something that somehow only affects M1s.

**Comment by pmaia** [comment]
I was facing the same issue but managed to fix it by adding MeetingBar to the list of apps that should automatically open on login.

System Preferences -> Users & Groups -> Login Items

Click the + sign and add MeetingBar app

**Comment by mb-ca** [comment]
> I just switched from an Intel-based 2020 MacBook Pro to the new M1 Max. Both are running Monterey 12.6.1, but interestingly only the new M1 seems to be affected by this issue. Not sure whether it's coincidental, if I ended up with different settings somewhere, or if it's actually something that somehow only affects M1s.

I'm currently on a Intel-based 2020 MacBook Pro and experiencing this issue, so maybe just coincidental.

**Comment by andfinally** [comment]
@pmaia's [workaround](https://github.com/leits/MeetingBar/issues/494#issuecomment-1372169583) fixed it for me, MeetingBar 4.2.2, macOS Ventura 13.1 on an M1 Mac.

**Comment by davidfranks** [comment]
Same issue here

**Comment by leits** [comment]
Migrated to https://github.com/sindresorhus/LaunchAtLogin from the homemade version.

This will be part of the next release!

**Comment by mrienstra** [comment]
Corresponding commit for the curious: https://github.com/leits/MeetingBar/commit/76b3c267af41dc72ffd5b713ae70955322a5607d
