### ISSUE TITLE
Bug: Randomly re-joining meeting that ended early

### ISSUE THREAD

**Issue by bradmurray** [leits/MeetingBar#495]
**App version**
4.0.6

**Installation source**
homebrew

**Describe the bug**
When I have left a zoom call that still has time left, MeetingBar will randomly re-start the call. 

**To Reproduce**
1. Leave a zoom call that was started with MeetingBar after a few minutes
2. Wait for it to join again

**Expected behavior**
MeetingBar should only join a call once.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - macOS version: 12.5

**Additional context**
None

**Comment by leits** [comment]
As there was no feedback, I will close the issue now. Feel free @bradmurray to reopen the issue again.
