### ISSUE TITLE
Feature: If there's nothing scheduled for tomorrow, tell me when my next meeting is

### ISSUE THREAD

**Issue by johnbillion** [leits/MeetingBar#496]
**Is your feature request related to a problem? Please describe.**

Most of the time I use MeetingBar Monday to Friday for work calls. On a Friday I would like to see when my first meeting on Monday is.

**Describe the solution you'd like**

If I have no call scheduled for the following day, I'd like to see when my next meeting is, just so I know what my Monday morning is going to be like.

<img width="247" alt="Screenshot 2022-08-19 at 17 46 32" src="https://user-images.githubusercontent.com/208434/185667743-67083d52-af39-46fb-bba9-a4db2160b2a8.png">

**Additional context**

I'm a very happy user of MeetingBar. Keep up the good work.

**Comment by leits** [comment]
Hi @johnbillion,
I'm glad you like the app.

Thanks for the request. 
It's interesting, but it's a very specific implicit case. It hasn't found any support from other users in these two months, so I'm going to close it. Sorry!
