### ISSUE TITLE
Notification is not shown if the title is too long and clashes with the app menu

### ISSUE THREAD

**Issue by durdevic** [leits/MeetingBar#5]
**Describe the bug**
So if the Calendar title is too long, the notification disappears. The solution would be, 

**To Reproduce**
1. Create an event with a very long title in the calendar
2. Open some app with a lot of menus in the top bar (e.g. Chrome)

Note: Using 13' MacBook Pro, This doesn't occur on larger screens obviously.

**Solution**
If there is any way to detect if the notification is going to get cut, if yes then display it with a shorter title. 

E.g. Customer Feedback Grooming now (58 min left) -> Customer Feed... (-58m)

**Screenshots**
<img width="864" alt="Screenshot 2020-06-02 at 14 48 24" src="https://user-images.githubusercontent.com/2753836/83522870-90abda80-a4e1-11ea-8f64-b921baf6dc15.png">
<img width="919" alt="Screenshot 2020-06-02 at 14 48 18" src="https://user-images.githubusercontent.com/2753836/83522877-92759e00-a4e1-11ea-8442-c9de56d1e263.png">

**Desktop:**
 - macOS version: 10.15.5
 - Macbook pro 13 inch

**Comment by leits** [comment]
@durdevic Add option to limit event title or change to"Meeting" in v1.1.
