### ISSUE TITLE
Remaining Time stopped working

### ISSUE THREAD

**Issue by sweiland** [leits/MeetingBar#50]
**Describe the bug**
I currently have a calendar event with a total length of 240 minutes. MeetingBar has been stuck displaying "223 min left" for a while now (the event started 46 minutes ago).

**To Reproduce**
Not sure if it's reproducible, I can try to reproduce it later and update accordingly.

**Expected behavior**
Correct remaining time should be displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/4283335/90231570-b0357c80-de1b-11ea-9f25-721d3b188284.png)

**Desktop (please complete the following information):**
 - macOS version: 11 Beta 4 (Build 20A5343i)

**Additional context**

**Comment by chaseadam** [comment]
I can report this same "frozen" behavior for several meetings as well as upcoming meetings "X in X min". I am not able to reliably reproduce, but happy to help debug with some guidance.

OSX 10.15.6 (19G2021)

**Comment by sweiland** [comment]
Sorry, but I think you'll have to reopen this issue. Installed 1.4 via homebrew earlier, and it got stuck again, next time I'll check out the beta too.

![image](https://user-images.githubusercontent.com/4283335/92696999-01695b00-f34b-11ea-94b3-dc9c2849507d.png)
![image](https://user-images.githubusercontent.com/4283335/92697041-0e864a00-f34b-11ea-8cb7-f84bb2fa37a7.png)

**Comment by leits** [comment]
Thanks, @sweiland!
I will continue to look for ways to solve this.

Could you help me with the information?
What is the duration of stucking did you notice and how often?
The countdown is restored by yourself, or are you doing something with the app?
Is your Mac heavily loaded at the stucking time?

**Comment by sweiland** [comment]
Don't know the exact duration, but I've been keeping an eye on it and it seems to resume every about 30 minutes or so. It just jumped from 1:15h to 50m, and is now stuck on that.
I'm not doing anything to get it to work, it just jumps sometimes.
My system load isn't that high, currently sitting at ~15% CPU and ~70% RAM utilization, with all typical processes running. It's an i9 MBP, so I would be very surprised if any hardware bottleneck was causing this.

**Comment by sweiland** [comment]
ok so it's exactly 25 minute intervals in which it updates apparently. interesting!

**Comment by sweiland** [comment]
1.5 _maybe (hopefully)_ fixed the bug. I’ll keep you updated, but for now it seems to be working as expected.

**Comment by sweiland** [comment]
![image](https://user-images.githubusercontent.com/4283335/93172661-91344e00-f72b-11ea-93b2-6628e0f1804f.png)
unfortunately it got stuck again, too bad

**Comment by shadyabhi** [comment]
Seeing similar behavior on 1.6 as well.

**Comment by chaseadam** [comment]
Is there a debug mode or verbose logging I can enable and post to help troubleshoot?

**Comment by jgoldhammer** [comment]
@sweiland , @chaseadam and @shadyabhi : Does this still happen with version 2.0.5? 

From the comments I see that this happens under Catalina and Big Sur as well. I have never noticed that and I have used it the last two weeks. @leits, have you changed between version 1.6 and version 2.0 something regarding schedule of title update?

**Comment by jgoldhammer** [comment]
@sweiland , @chaseadam  and @shadyabhi : Any input for us here? If we do not get any response, I have to close the issue. You are free to reopen it. Thanks.

**Comment by shadyabhi** [comment]
@jgoldhammer  Not seeing any issue so far in 2.0.5 which I updated on Jan 4. Since, it's been only 3 days of me using it, in this limited time, I've not seen this issue.

**Comment by jgoldhammer** [comment]
Thanks for the answer. Ok, I will close the Ticket for now...
