### ISSUE TITLE
Feature: Option to join meeting using URL(s) from the body of the invite - if the location/URL field is empty

### ISSUE THREAD

**Issue by sammcj** [leits/MeetingBar#502]
**Is your feature request related to a problem? Please describe.**

I often get sent meeting invites from people / tools that put the join link in the body rather than the location (or URL) field, this means you can't click to join.

**Describe the solution you'd like**

Option to allow - if no URL is found in the location or URL fields - use the URL(s) from the body to join the meeting.

--
Keep up the AWESOME work, I love this app!

**Comment by lohningerthomas** [comment]
Would be interested in that as well

**Comment by leits** [comment]
Hi @sammcj,
Thanks for the request!
It already works this way. The app can recognize meeting service links in the event body. It won't open any link from the body because of safety, but if the service is recognized - yes.

**Comment by sammcj** [comment]
Would it be possible to either:1. Allow users to provide additional trusted URLsOr 2. add Google forms to the trusted list?Thanks,--Sam McLeodOn 8 Oct 2022, at 08:39, Andrii Leitsius ***@***.***> wrote:﻿
Hi @sammcj,
Thanks for the request!
It already works this way. The app can recognize meeting service links in the event body. It won't open any link from the body because of safety, but if the service is recognized - yes.

**Comment by leits** [comment]
@sammcj, you can do it!
Add next regexes to custom regexes in the advanced section:
- `https:\/\/docs\.google\.com\/forms\/d\/e\/[a-zA-Z0-9_]+\/viewform`
- `https:\/\/forms.\gle\/[a-zA-Z0-9s]+`

**Comment by sammcj** [comment]
How did I not notice this! Thank you so much!!!

**Comment by ul** [comment]
For other people like me trying it and wondering why it doesn't work: restarting MeetingBar might help to activate these settings (MeetingBar 4.0.6, macOS 13.6).
