### ISSUE TITLE
Bug: Texts laid over each other making them unreadable

### ISSUE THREAD

**Issue by igorkulman** [leits/MeetingBar#505]
**App version**
4.0.6

**Installation source**
brew

**Describe the bug**
The main preferences screen contains 2 texts laid over each other making them unreadable and also the combo box under them is not clickable

**To Reproduce**
1. Open Meetingbar preferences

**Expected behavior**
When the warning about permissions is shown the notification time selection should be hidden.

**Screenshots**
![Screenshot 2022-09-13 at 17 35 15](https://user-images.githubusercontent.com/4746070/189945291-0276336d-1217-4862-b789-95d7c91ae6cd.jpg)

**Desktop (please complete the following information):**
 - macOS version: 12.6

**Comment by leits** [comment]
Fixed in https://github.com/leits/MeetingBar/commit/49101e03f46fbaf199a478a9de5cbc4f3af36b7a.
Fix will be in the next release.
