### ISSUE TITLE
Bug: Delegated calendars not appearing in MeetingBar

### ISSUE THREAD

**Issue by scottsb** [leits/MeetingBar#506]
**App version**
4.0.6

**Installation source**
App Store

**Describe the bug**
When integrating using native macOS calendar integration, my "delegated" calendars are not appearing as options in MeetingBar, whether read-only or read/write. These are calendars owned by other Google accounts that are shared with me. The main use case is my personal Google calendar which is shared (read/write) with my work Google Workspace account.

**To Reproduce**
1. Share a calendar from one Google account to another. (Receiving account might specifically need to be a Google Workspace account, but I've not confirmed.)
2. Set up the Google account receiving the share in macOS Calendar.
3. Enable the shared Google account as a displayed "delegated" calendar in macOS Calendar.
4. Configure MeetingBar to use the native macOS Calendar integration.
5. View the list of calendars in MeetingBar. Note that the shared calendar does not appear.

**Expected behavior**
All calendars that appear in macOS calendar are available in Meeting Bar.

**Screenshots**
List of calendars in macOS Calendar app:
![SCR-20220913-j5t](https://user-images.githubusercontent.com/6756989/189976415-547a7fae-49e7-41c8-9346-c204c29e5c34.png)

List of calendars in MeetingBar:
![SCR-20220913-j77](https://user-images.githubusercontent.com/6756989/189976691-a2ad5ef0-7a01-488d-8b29-9caa78b114d3.png)

**Desktop (please complete the following information):**
 - macOS version: 12.5.1

**Comment by scottsb** [comment]
This seems similar to #212 but that was supposed to have been fixed already.

**Comment by scottsb** [comment]
@leits Yes, you're right: it is there after restarting. I had never gone back into the settings screen after first installing and submitting this issue. Would be great to get that zero-state bug fixed, but thanks for pointing out the effective workaround: it solves the issue for my own personal purposes.

**Comment by leits** [comment]
@scottsb, great!
Added the bug fix to the next release scope (4.2.0)
