### ISSUE TITLE
Feature: Ability to hide any single meeting

### ISSUE THREAD

**Issue by khadiwaa** [leits/MeetingBar#509]
**Is your feature request related to a problem? Please describe.**
This is a feature that is available in the app Next Meeting from Nathan Spindel, but the ability to hide meetings to clean up the meeting menu. I sometimes have meetings that I want to keep on my calendar to block the time, but I don't need to see in MeetingBar. 

For example, every morning I have time allocated for comms, which I want to be aware of via MeetingBar. Then I have time I block out for lunch so my team doesn't book an event at that time, and I don't want to see that on MeetingBar. Or hiding the birthdays of some friends, while allowing the birthdays of others to remain visible. The use cases may vary by the user, but these are some examples that apply to me.

**Describe the solution you'd like**
I think the Next Meeting solution opening the list of meetings, then holding down the option key, which then shows the label "Hide" prefixed in front of the meeting. Then by clicking the menu item while holding down the option key, the meeting would then be hidden. There may be more elegant ways of solving this, but this simple solution worked great.

By hiding the meeting, then instead of the meeting the user hid showing up as the next meeting in the menu bar, then next non-hidden meeting would show, helping the user better prepare.  

In the case of recurring meetings, I personally think only the single instance of the meeting should be hidden, but that is something interesting to consider for whatever solution you might come up with.

In the case of accidentally hiding meetings, the user would need the ability to restore hidden meetings. Maybe making it as simple as restoring all hidden meetings, instead of giving the user to restore them individually.

**Additional context**
I have about 10-12 items on my calendar per day, both meetings with others or blocked out time for heads down work. So having this feature is incredibly helpful for me to narrow down to just the meetings that I want to have top of mind via the MeetingBar. I imagine other users that have similar workflows and volume would also greatly appreciate this feature :)

**Comment by leits** [comment]
Thanks for the request!
This feature is already in the backlog. Please follow the primary ticket for updates:
https://github.com/leits/MeetingBar/issues/205#issuecomment-1279927136
