### ISSUE TITLE
Bug: Meetingbar on M1 16" with long title becomes invisible

### ISSUE THREAD

**Issue by dkerwin** [leits/MeetingBar#512]
**App version**

**Installation source**
- AppStore

**Describe the bug**
Starting Meetingbar on my M1 MBP 16" with an active appointment collides with the camera notch. Other apps and Meetingbar itself are pushed into the invisible realm. Stopping Meetingbar resurfaces the other app icons.

**To Reproduce**
1. Start Meetingbar with a super long title for the next meeting
2. Watch it show up for a microsecond
3. Recognise that Meetingbar and other apps are no longer visible

**Expected behavior**
Have Meetingbar work with a camera notch present

**Screenshots**
Meetingbar not running
<img width="1045" alt="without_MB" src="https://user-images.githubusercontent.com/168948/192754718-dfd27d18-1429-441a-852c-62f443aad9dd.png">
Meetingbar running with normal length title
<img width="1063" alt="MB_with_short_title" src="https://user-images.githubusercontent.com/168948/192754714-976f9710-72e5-4eeb-be19-b48506bf93ca.png">
Meetingbar running with long title
<img width="1026" alt="MB_running_with_long_title" src="https://user-images.githubusercontent.com/168948/192754713-38402080-34e6-48ab-8224-bc98986a1458.png">

**Desktop (please complete the following information):**
 - macOS version: 12.6

**Comment by emretanriverdi** [comment]
I also have this problem.

**Comment by leits** [comment]
Thanks for the report, @dkerwin!

You can reduce the length of the header so that it fits:
<img width="812" alt="image" src="https://user-images.githubusercontent.com/12017826/193546518-fb3e328f-cddf-449f-a465-f9fd72a3be45.png">

Also, I recommend using apps like [Dozer](https://github.com/Mortennn/Dozer) to keep you status bar uncluttered.

**Comment by emretanriverdi** [comment]
We can't even open the app if we have a meeting present, to set this value.

**Comment by Gerrit-K** [comment]
@leits sorry to chime in here, but how can we open these preferences if MeetingBar is hidden in the first place? I also somehow don't get the notification on my M1 that supposedly fixed #429 :/

**Comment by shreyasbharath** [comment]
Running into the same issue on a 16" Mac, can we re-open this bug please?
