### ISSUE TITLE
Bug: All-day align event titles misaligned in AM/PM mode

### ISSUE THREAD

**Issue by kofigumbs** [leits/MeetingBar#513]
**App version**
4.0.6

**Installation source**
- homebrew

**Describe the bug**
The all-day event title is aligned in the middle of "second column" with the end times.

**To Reproduce**
1. Set _Appearance > Menu > Time format_ setting to _12-hour AM/PM_
2. Setup an all-day meeting and a normal meeting for today
3. See menu alignment issue

**Expected behavior**

The all-day event title should be aligned in the "third column" with the other event titles.

**Screenshots**

![Screen Shot 2022-10-05 at 11 35 15 AM](https://user-images.githubusercontent.com/3235964/194101937-121de8aa-a855-448c-a61b-04482412eaa6.png)

**Desktop (please complete the following information):**
 - macOS version: 11.7

**Additional context**

I think the resolution would be to change this bit

https://github.com/leits/MeetingBar/blob/35481c9832e0023c19e0db9779feedbc4e34b248/MeetingBar/StatusBarItemController.swift#L643-L649

To read like this

```swift
        if event.isAllDay {
            eventStartTime = "status_bar_event_start_time_all_day".loco()
            switch Defaults[.timeFormat] {
            case .am_pm:
                eventEndTime = "\t\t\t"
            case .military:
                eventEndTime = "\t"
            }
        } else {
            eventStartTime = eventTimeFormatter.string(from: event.startDate)
            eventEndTime = eventTimeFormatter.string(from: event.endDate)
        }
```

I'm just guessing it's 3 tabs based on the visual. I can test it and submit a PR with the change if that'd be helpful.

**Comment by leits** [comment]
Thanks, @kofigumbs!
Your guess was right, added your solution with two spaces and it works as expected!
I'll include the fix in the next release 👍
