### ISSUE TITLE
Feature: Self authorization/authentication instead of centralized one

### ISSUE THREAD

**Issue by thekoma** [leits/MeetingBar#514]
**Is your feature request related to a problem? Please describe.**
The functionality of directly sync with google API is awesome, BUT not every organization will let you use an external app talk to your calendar for security reasons.

**Describe the solution you'd like**
It would be cool if instead we could use a local authorization via serviceaccount or direct authentication. This will drive the ownershipo of the access to the API to the user instead of the application.

**Comment by leits** [comment]
Hi @thekoma,
I'm not sure I understand your suggestion. Do you know how it can be done or is it just an abstract idea?

**Comment by leits** [comment]
Closed due to no response. 

@thekoma feel free to reopen with the update.
