### ISSUE TITLE
Feature: Allow hide/formatting option for Tentative/Maybe events

### ISSUE THREAD

**Issue by mattmink** [leits/MeetingBar#515]
**Is your feature request related to a problem? Please describe.**
The user is unable to hide (or format differently) events that have been tentatively accepted (where response is "Maybe"). 

**Describe the solution you'd like**
Just like we can for Pending or Declined events, it would be helpful to hide these "Maybe" meetings or format them differently.

**Describe alternatives you've considered**
* Regex could be used to hide a specific, hard-coded set of meetings by title. This results in meetings being hidden that shouldn't be
* Meetings could be declined (or provided no response) instead of tentatively accepted. This results in an inaccurate response to the organizer.

**Additional context**
![Screen Shot 2022-10-11 at 11 47 32 AM](https://user-images.githubusercontent.com/2625927/195152259-589712e6-1303-4fa4-bc6f-67cc15d10ca9.png)

**Comment by whazlewo** [comment]
Can I tag a feature to this? For Auto Dialing meetings, it would be awesome if there was a flag to "ignore tentative meetings"

**Comment by jgoldhammer** [comment]
<img width="856" alt="image" src="https://user-images.githubusercontent.com/3872101/224572191-68466b05-b976-463b-bf64-61d1065b0858.png">

I have implemented this feature and will create a PR for this. 🎉

**Comment by leits** [comment]
https://github.com/leits/MeetingBar/pull/599 merged!
This feature included in the next release scope
