### ISSUE TITLE
Bug: Link not found for meetings with no link

### ISSUE THREAD

**Issue by ianhellstrom** [leits/MeetingBar#516]
**App version** 4.0.6

**Installation source**
AppStore

**Describe the bug**
When “Automatic join next event meeting” is set, any meeting without a link (e.g. lunch or in-person meeting), generates an error message “Ouch! Link not found”

**To Reproduce**
1. Go to preferences
2. Go to Advanced 
3. Enable “Automatic join…”
4. Create meeting without meeting linke

**Expected behavior**
The meeting notification but no second notification that there was no link

**Desktop (please complete the following information):**
 - macOS version: 12.6

**Comment by leits** [comment]
Thanks for the report!
I'll add a fix for this issue to the next release scope.
