### ISSUE TITLE
Feature: Menu item to disregard current meeting.

### ISSUE THREAD

**Issue by hrenkert-bw** [leits/MeetingBar#517]
**Is your feature request related to a problem? Please describe.**
When a meeting is in-progress and I am attending or otherwise no longer interested in knowing the in-progress meeting has 15 minutes left, I would rather know when the next meeting is. In case the two meetings are back to back.

**Describe the solution you'd like**
A menubar item should be present, perhaps on the meeting details sub menu, then when chosen will notify MeetingBar do display the next meeting. A sort of "yes, yes, I know there is a meeting right now, but I don't care, show me the next one." item. "Show next meeting" may be a title.

**Describe alternatives you've considered**
maybe it should be an option: display next meeting 15 minutes after current meeting started.

**Additional context**
None.

**Comment by leits** [comment]
Thanks for the request!
This feature is already in the backlog. Please follow the primary ticket for updates:
https://github.com/leits/MeetingBar/issues/205#issuecomment-1279927136
