### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by adamshand** [leits/MeetingBar#519]
**App version**

4.0.6

**Installation source**

- Homebrew

**Describe the bug**

In "Preferences – General" there is an alert overlayed on top of the "Send notification to join next event meeting" setting.   Screenshot below.

I am unable to select the tick box or dropdown and MeetingBar is not listed under "System Preferences - Notifications" to grant permissions to alert.

**To Reproduce**

This is the first time I've installed MeetingBar.  I haven't done anything other than run it and try and configure it.

**Screenshots**

<img width="713" alt="image" src="https://user-images.githubusercontent.com/130651/195519340-95587c2e-d95d-4ae9-b6bb-ffc4f10b4a83.png">

**Desktop (please complete the following information):**
 - macOS version: 12.6 (on an M1 MacBook Air)

**Comment by leits** [comment]
Thanks for the report, @adamshand!
The release with this bug fix for this issue is ready. After this PR https://github.com/Homebrew/homebrew-cask/pull/133436 will be merged it will be available via homebrew.

**Comment by adamshand** [comment]
Amazing, thanks!
