### ISSUE TITLE
Links in event description

### ISSUE THREAD

**Issue by antkiselev** [leits/MeetingBar#52]
Links are not clickable. Is it a bug? It would be great to be able to use them to access materials mentioned in the description or to join unsupported web conferencing clients (e.g. Skype for business).

**Comment by jgoldhammer** [comment]
Which kind of links are you refering @antkiselev? Links in the event notes, location or somewhere else? I think we could collect up to 5-7 links from the calendar event and create extra menu entries for them to be clickable. Will that work for you?

By the way, Skype for Business is supported. Or do you have any url for us which is not working for you?

**Comment by jgoldhammer** [comment]
Any input @antkiselev ? What do you think @leits ?

**Comment by jgoldhammer** [comment]
I will close the ticket for now. Feel free to reopen @antkiselev . Thanks

**Comment by antkiselev** [comment]
Hi @jgoldhammer. Thank you for your contribution!
I submitted the request when Skype For Business was not supported by "Join next meeting" functionality yet. Now it works, it grabs the link from the Notes and Location fields. 
But it would be still useful to have the same links to be clickable in the submenu. Besides that it would be great to open the event in the calendar by clicking event header, for example. Would it be possible? What do you think?
