### ISSUE TITLE
Bug: doesn't find meeting link in notes

### ISSUE THREAD

**Issue by j-ro** [leits/MeetingBar#524]
**App version**

4.0.6

**Installation source**
- AppStore / homebrew / manual

manual

**App Version**
- 4.0.6

**Calendars provider (selected in app)**
- macOS Calendar 

**Describe the bug**

I have zoom links in the notes of a calendar item (and it shows as in the notes in MeetingBar when I view details) but when I use the shortcode to open the zoom link, MeetingBar says it can't find a link to open.

**To Reproduce**
1. Go to a meeting with a zoom link in the notes
2. Use the shortcut to open the zoom link
3. Get an error saying no zoom link is found

**Expected behavior**
Zoom link opens in the browser

**Screenshots**
Meeting has zoom link in notes (cut off to preserve privacy but you get the idea): 

<img width="103" alt="Screen Shot 2022-10-19 at 9 15 51 AM" src="https://user-images.githubusercontent.com/1058998/196747341-428e383a-f177-4eb7-af08-d3bebd11c938.png">

But shortcut doesn't work:

<img width="367" alt="Screen Shot 2022-10-19 at 9 15 27 AM" src="https://user-images.githubusercontent.com/1058998/196747233-deb25323-2258-407b-8baa-77d76cedb017.png">

**Desktop (please complete the following information):**
 - macOS version: 12.6

**Comment by leits** [comment]
Thanks for the report, @j-ro!
Can you check your link in [regex101.com](https://regex101.com/) with this regex?
```
https?:\/\/(?:[a-zA-Z0-9-.]+)?zoom.(?:us|com.cn)\/(?:j|my|w)\/[-a-zA-Z0-9()@:%_\+.~#?&=\/]*
```

Or change a few symbols with similar ones and share the link with me?

**Comment by j-ro** [comment]
No match! Here's a link (the original link has 9 numbers at the end, but I changed them here): https://zoom.us/s/123456789

Adding as s option to the match for after zoom.com makes it work though, so maybe that's the answer here? 

https?:\/\/(?:[a-zA-Z0-9-.]+)?zoom.(?:us|com.cn)\/(?:j|my|w|s)\/[-a-zA-Z0-9()@:%_\+.~#?&=\/]*

**Comment by j-ro** [comment]
Nice, makes sense! Does the app do automatic updates?

**Comment by leits** [comment]
Yes, after the release, but only for homebrew and AppStore installation 😅

**Comment by j-ro** [comment]
ok cool, I think I'm appstore, will await the update!
