### ISSUE TITLE
Feature / Question: Open Slack on meeting start

### ISSUE THREAD

**Issue by diist** [leits/MeetingBar#525]
**Is your feature request related to a problem? Please describe.**
I have a daily stand-up in a Slack channel (using huddle), and it would be great if MeetingBar could open the right channel when the meeting starts. 

**Describe the solution you'd like**
Not sure, that's why I'm here!

**Describe alternatives you've considered**
I control the meeting and have added the channel link (like `https://xxxxxx.slack.com/archives/XXXXXX`) in the Google Calendar invite as both the location and the description, and I've set up `Open all meeting links in` to `Default Browser` in MeetingBar. 

I think I don't understand what a "meeting link" is, because I'm getting a `Link not found, or your meeting service is not yet supported`. Possibly what's needed is a Google Calendar Add-on that would let me set the right link?  We can go further and directly open into a huddle by using the link such as `https://app.slack.com/huddle/XXXXXX`

**Additional context**
Is this something I can achieve with AppleScript and Regexes?

ie. I'd like MeetingBar to open one of those links in my default browser:

![image](https://user-images.githubusercontent.com/5717892/196855967-239c8c5d-f8dc-497b-b866-af0599b5aa82.png)

Thanks a lot, I love `MeetingBar`!

**Comment by diist** [comment]
I got it t work by setting the following `Custom regexes for meeting link`: `https:\/\/app.slack.com\/huddle\/[a-zA-Z0-9]+`

**Comment by leits** [comment]
Great, @diist!
Is this some sort of Slack calendar integration or did someone manually add a link to a meeting?
For the first time I see Hadl links in the calendar)

**Comment by diist** [comment]
I manually added the link to the meeting. I don't think there is a Slack add-on for Gcal, the integration is usually done the other way around (using the Gcal app in Slack); though for me MeetingBar works much better as I have all Slack notifications disabled!
