### ISSUE TITLE
(Feature request) JOIN button

### ISSUE THREAD

**Issue by antkiselev** [leits/MeetingBar#53]
It would be great to automatically detect URLs of the most popular web conferencing services (Zoom, GoogleMeet, Skype, Skype for business, Webex) in the description or URL field and show button JOIN opening the URL 5 min before and during the meeting time.

**Comment by leits** [comment]
@antkiselev , do you try to click right on event title in main menu? It works just like a "join" button that you describe)

**Comment by antkiselev** [comment]
Thank you for your response. I've just tried to do that, but it didn't work for either Skype for Business or Zoom. How can I enable extended logging to track the bug?
From my perspective, it would be more intuitive to open the event in the calendar by clicking on the event title.

**Comment by leits** [comment]
The current version (1.3) has some issues with zoom connectivity and no Skype for Business support.
But both will be fixed in the next (1.4) release!

**Comment by antkiselev** [comment]
Thanks, looking forward to that! I'll definitely join the beta testing. In my case, Skype for Business URL looks like https://meet.[company domain]/[company domain]/meet/[username]/[meeting-id].

What about opening the event on the calendar app? Would it be possible to open that for example by clicking event description in submenu?

**Comment by leits** [comment]
Hm. I found in Microsoft documentation that they use lync.com domain and the links to Skype for Business meetings start from 'https://meet.lync.com'.
Thanks! I will update the regex for the service.

**Comment by antkiselev** [comment]
lync.com might be used for cloud version, the URL with a custom domain – for self-hosted enterprise solutions.
