### ISSUE TITLE
Bug: Regex did not catch meeting

### ISSUE THREAD

**Issue by whazlewo** [leits/MeetingBar#530]
**App version**
4.1

**Installation source**
- AppStore / homebrew / manual
homebrew

**App Version**
- 4.1

**Calendars provider (selected in app)**
- macOS Calendar

**Describe the bug**
I have this regex defined to filter out all "happy hours" and "office hours"
`/.*[office|happy] hour[s]?.*/ig`

But I got auto dialed into a meeting titled:
"Visual+UI Office Hours"

**To Reproduce**
1. Go to Preferences
2. Select Advanced Tab
3. Select "Add regex" under "Custom regexes to filter out meetings"
4. Add meeting titled "Visual+UI Office Hours" to calendar
5. Watch for auto-dial in

**Expected behavior**
I was expecting to
A) Not see the "Visual+UI Office Hours" meeting in my system tray
B) Not be auto dialed in.

**Screenshots**
<img width="720" alt="Screen Shot 2022-10-26 at 10 23 00 AM" src="https://user-images.githubusercontent.com/4400337/198094428-adfc2e07-bc31-4ee9-90f7-ba5a67d21542.png">

**Desktop (please complete the following information):**
 - macOS version: 12.6
 - 
**Additional context**
I'm unclear on exactly how we express the regex in the UI, I have the literal string 
`/.*[office|happy] hour[s]?.*/ig`. entered

I'd love some way to see a list of the events that my regexes are going to match as a way to confrm

I'd also love a feature that lets me just say "Don't auto dial these meetings" rather than filtering out all meetings (ie. i'd like the option to have it still show up in my system tray, just not auto dial that meeting)

While I'm just throwing feature requests out, I'd REALLY like the ablility to say "don't auto-dial tentative (maybe) meetings.  (ie. only auto dial meetings marked "Accept").

**Comment by leits** [comment]
Hi @whazlewo, 
Thanks for the report!
The regex modifier won't work in this way with Swift. Also, square brackets don't work the way you think.
`[office]` will match "office" as well as "off" or "ceo". 

So the correct regex for your case will be this one: 
```
(?i).*(office|happy) (hour)s?.*
```

**Comment by whazlewo** [comment]
Today I learned that a Regex is not the same in all languages :-)
and read up on brackets.

Thank you @leits
