### ISSUE TITLE
Bug: Regex filter are not applied immediatelly, the app needs to be restarted

### ISSUE THREAD

**Issue by igorkulman** [leits/MeetingBar#533]
**Installation source**
- homebrew

**App Version**
- 4.2.1

**Calendars provider (selected in app)**
- macOS Calendar

**Describe the bug**
When I add or edit a regex to filter out calendar events the regex change is not applied immediately. I have to quit the app and start it again for the change to get applied. 

**To Reproduce**
1. Go to Preferences, Advanced
2. Add a new regex filtering out some calendar events
3. See the calendar events are not immediately filtered out, you have to restart the app

**Expected behavior**
See calendar events being filtered out by the regex without restarting the app

**Desktop (please complete the following information):**
 - macOS version: 12.6.1

**Comment by untitled500** [comment]
Experienced this on 4.2.2.

**Comment by leits** [comment]
Thanks, @igorkulman!

Included a fix for this bug in the next release.

**Comment by igorkulman** [comment]
I still have the same problem on 4.3.0. I add a regex and the meeting does not disappear from the menu bar or the list, I have to kill the app like before. Same with removing a regex.
