### ISSUE TITLE
Make “What’s New?” text selectable

### ISSUE THREAD

**Issue by hughlilly** [leits/MeetingBar#535]
I was just looking at the changelog and wanted to quickly Google a term, and noticed the text isn’t selectable. I believe that adding `textSelection(.enabled)` to the end of the list here would enable this:
https://github.com/leits/MeetingBar/blob/a4d90a2d888d269d8fa5b42df2d8eca539326a0e/MeetingBar/Views/Changelog/Changelog.swift#L16-L19

See [Instance Method textSelection(_:)](https://developer.apple.com/documentation/swiftui/text/textselection(_:)).

**Comment by leits** [comment]
Thanks for the request, @hughlilly!

I've tried this method and it works so strangely:
<img width="712" alt="image" src="https://user-images.githubusercontent.com/12017826/202557426-ce3218a5-f18a-4158-873a-6f9e27e7ae56.png">

I'll see if I can do better.

**Comment by hughlilly** [comment]
Oh that’s very strange! Don’t spend too much time on this if you don’t want to.
