### ISSUE TITLE
Bug: Custom browser setting is ignored when using a custom regex for meeting links

### ISSUE THREAD

**Issue by notthebee** [leits/MeetingBar#537]
**App version**
4.2.1

**Installation source**
- AppStore

**Calendars provider (selected in app)**
- macOS Calendar 

**Describe the bug**

My default browser is set to Safari, but I would like to open my meetings in Chromium.
 I've set the "Open all meeting links in..." setting to Chromium and made sure that the Chromium executable is set correctly. However, when I open a meeting from MeetingBar, it opens in Safari instead of Chromium.

I'm not sure if the issue takes place with an officially supported meeting service (e.g. Teams or Google Meet)

**To Reproduce**

1. Create a custom Regex for meeting links2. 
2. Set the "Open all meetings in..." setting to "Chromium"
3. Click on the menu bar icon and then click on "Join current event meeting"

**Expected behavior**

The meeting opens in Chromium

**Screenshots**

N/A

**Desktop (please complete the following information):**
 - macOS version: 12.15.1

**Additional context**

None

**Comment by leits** [comment]
Thanks, @notthebee !

Included a fix for this bug in the next release.
