### ISSUE TITLE
Feature: Custom RegEx replacement (URL Defense / Proofpoint v2)

### ISSUE THREAD

**Issue by andrewmin** [leits/MeetingBar#539]
URL Defense/Proofpoint wraps external email links so that a third party (Proofpoint) can validate them. As discussed in #384 , you can solve this if your company uses Proofpoint v3 by using custom regexes for the meeting link—e.g., if the link is https://urldefense.com/v3/__https://mongodb.zoom.com/j/xxxxxxxxxxxxxx , you can filter out for just https://mongodb.zoom.com/j/xxxxxxxxxxxxxx

The challenge is that older versions of Proofpoint encode the URLs using UTF-8 (and also seems to throw some garbage at the end). For example, a link to https://meet.google.com/jyx-ifea-jjn will wrap into https://urldefense.proofpoint.com/v2/url?u=https-3A__meet.google.com_jyx-2Difea-2Djjn-3Fhs-3D224&d=DwMFaQ&c=rGIfYmk-1z7cfZPhPNJ2NJAhybwe4_LJFnxef54aLtE&r=mLNoUX_En2gO9geDTc5_aXaXNwQC36GV97jTrpAxXpM&m=kFBGgdOHVg5r5w1EG9xefdaB0FjkIky_N1iPUGkg1A0hjsdAQnWFfShNV8lkQLwl&s=hX9MGZGdvki7XoSbect74rQvY5DvQsUqiz9OGzGAttQ&e= .

Unless I'm mistaken, I think the custom filter is not sufficient—you would also need to replace the UTF-8 codes with characters.

**Comment by leits** [comment]
Hi @andrewmin,
Sorry for the delay, is this still relevant?

**Comment by andrewmin** [comment]
Interestingly MeetingBar now seems able to join meetings wrapped in URLDefense/proofpoint without any custom regex. Not sure if I missed a release note, but that's great!

**Comment by leits** [comment]
Awesome!

**Comment by andrewmin** [comment]
As a follow up, I noticed there are still some issues with URLDefense v3 links with Teams. I think the reason it was working for some but not all invites is that some calendar invites for Teams seem to include the full URL in plain text (the clickable href is wrapped in URLDefense/Proofpoint, but the text is still there) and MeetingBar grabs those URLs. For some calendar invites, it does not.

The following regex seems to work for these Teams links:
`https:\/\/urldefense\.com\/v3\/__https:/*teams\.microsoft\.com[^>\s]+`

It would be nice to build a URLDefense decoder for all supported links. If you use RegEx, you would need to build a unique RegEx for each service (you can't just do a generic URLDefense because then you'll pick up a lot of other non-meeting links). For example, there is a generic decoder gist at https://gist.github.com/baldwicc/3623b8eea96eb0cbbe41b1f51aeca21f

<blockquote><img src="https://github.githubassets.com/assets/gist-og-image-54fd7dc0713e.png" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> Gist</div><div><strong><a href="https://gist.github.com/baldwicc/3623b8eea96eb0cbbe41b1f51aeca21f">Proofpoint urldefense.com URL Decoder (v3)</a></strong></div><div>Proofpoint urldefense.com URL Decoder (v3). GitHub Gist: instantly share code, notes, and snippets.</div></blockquote>

edit: another advantage of having a native URLDefense decoder is that you could force the appropriate icons; for example, using this RegEx, I don't see a Teams icon.
