### ISSUE TITLE
Bug: Closed laptop still open next meet

### ISSUE THREAD

**Issue by GianlucaBobbioScale** [leits/MeetingBar#541]
**App version**

4.2.1

**Installation source**
- AppStore

**App Version**
- 4.2.1

**Calendars provider (selected in app)**
- macOS Calendar / Direct Google Calendar API integration (both)

**Describe the bug**
Closed laptop still open next meet. People find me on calls when my laptop is closed. Now I have to close and open the app everytime I leave.

**To Reproduce**

**Expected behavior**
Meeting bar not runnning when laptop is closed677

**Screenshots**

**Desktop (please complete the following information):**
 - macOS version: Monterey 12.4

**Additional context**

**Comment by jgoldhammer** [comment]
Hi @GianlucaBobbioScale - so it means that Meetingbar autojoins your meeting while macos is in sleep mode or only the screens are going to sleep?

I guess we have to pause and resume the opening of events depending on the state:
https://developer.apple.com/documentation/appkit/nsworkspace/1530075-willsleepnotification
https://developer.apple.com/documentation/appkit/nsworkspace/1530973-didwakenotification
https://developer.apple.com/documentation/appkit/nsworkspace/1530288-screensdidsleepnotification
https://developer.apple.com/documentation/appkit/nsworkspace/1524606-screensdidwakenotification

What do you think @leits ? It is worth to create a PR for this?

**Comment by FynnMazurkiewicz** [comment]
I also suffer from this issue. I am happy to donate 50€ for fixing this issue. Thank you for this great open-source tool!

**Comment by leits** [comment]
Thanks, folks
Added to the next release scope!

It's a good motivator, @FynnMazurkiewicz 😄

**Comment by FynnMazurkiewicz** [comment]
@leits Thank you so much, I am glad it helped 🥳  Could you publish a new release for it? 

I will contact you via the e-mail in your Github profile to discuss your preferred way of transferring the bounty 💸

**Comment by leits** [comment]
Released 🚀
