### ISSUE TITLE
Ignore events (e.g. availability blocks)

### ISSUE THREAD

**Issue by jaden-young** [leits/MeetingBar#55]
**Is your feature request related to a problem? Please describe.**
Work asks for calendar events for work from home (WFH)/availability. Status bar ends up showing `WFH Now` up until ~15 minutes before an actual event starts.

**Describe the solution you'd like**
I'd like to be able to have some way to prevent an event from showing on the status bar, I want the next event to show, e.g. `Team meeting in 2hrs` even if the ignored event is currently happening. I'd also want `Join next meeting` to skip the ignored event.

**Describe alternatives you've considered**
For WFH/availability blocks e.g. Google calendar has some options like working hours and appointment slots, but alas, thou shalt submit to the HTML email wielding branch of the organization.

**Additional context**
![without dropdown](https://user-images.githubusercontent.com/9858187/91252709-b5e86780-e723-11ea-83fd-67f3782a6083.png)
![with dropdown](https://user-images.githubusercontent.com/9858187/91252729-c26cc000-e723-11ea-9edf-d2d243c44375.png)

**Comment by leits** [comment]
Wow. Great idea, @jaden-young !

Do you have any things cleaning the filter ignoredCalendarItemIDs?
It looks like they will mostly just filling up.
And maybe it makes sense to do it only for recurring events?

Waiting for your feedback. Thanks for the feature!)

**Comment by jaden-young** [comment]
@letis I think your comment was meant for the PR in #56, moving discussion there.

**Comment by fuzzy76** [comment]
Would #84 help?

**Comment by leits** [comment]
@jaden-young, please, take a look on @fuzzy76 question

**Comment by jaden-young** [comment]
I think #84 is a great/elegant solution to this issue! I'd say to close #55 and #56 in favor of #84. The remaining functionality provided by manually ignoring events would just be swept up by declining attendance.

**Comment by jgoldhammer** [comment]
We will close this feature requests as suggested by @jaden-young and will follow #84 . Thanks!

**Comment by lilyball** [comment]
#84 is not enough. I want the status item to always show my next event, even if there's no meeting link (as I find MeetingBar a much better way of being aware of upcoming events than Calendar). However, I still want to filter out specific events.

In particular, when I have personal events during work time, I need to put an event on my work calendar to mark myself as busy. I typically title these events "Blocked out", for the same duration as my personal event, with no other information. And as a result, MeetingBar shows both events in the same time slot. It also can't seem to decide which one to prioritize.

For example, I had one such event this afternoon. When the event started, MeetingBar gave me a notification telling me "Blocked out" was about to start, though the status item showed the actual event. The event in question did not have a meeting link (as it was a personal event), but still, the notification was useless, and I have no reason to believe that the next time this happens (which is going to be once or twice a week for the forseeable future) it won't show "Blocked out" in the status item as well.

#56 is a potentially interesting solution, though primarily useful for recurring events (as I can't ignore the event until it's showing in MeetingBar). The other alternative that comes to mind would be an Advanced preference that lets me write a regex to filter out events. For my use-case I'd want it to only match on Title, though matching on event description is workable too (I'm just worried about false positives when matching event description).
