### ISSUE TITLE
Bug: Notifications (alerts) don't show when an event starts

### ISSUE THREAD

**Issue by Vadorequest** [leits/MeetingBar#553]
### macOS version

12.2.1 (21D62)

### MeetingBar version

4.2.1

### Installation source

Homebrew

### Calendars provider

Google Calendar

### Bug description

I have one issue:
- Notifications (alerts) don't show when an event starts

Here is a video (2mn) reproducing the bug, MeetingBar notices the event and even auto-open the meeting link when the event starts (as configured), but it doesn't show any alert notification on any of the 3 displays I'm using.
https://watch.screencastify.com/v/0EkCMFjX6HvchhLxY8JU 

I was using MacOS Calendar app before, and was experiencing the same issue. I upgraded today from 3.0.1 to 4.2.1, and also switched to Google Calendar, but none of those things helped regarding the notification issue.

### Expected behavior

It should display a notification on the top right.

### Screenshots/screen recordings

https://watch.screencastify.com/v/0EkCMFjX6HvchhLxY8JU 

<img width="671" alt="image" src="https://user-images.githubusercontent.com/3807458/204095548-ef614dc3-05e2-40b0-9a3e-91b3347012b7.png">

**Comment by 3r1k0n** [comment]
Same error on 13.0.1 (22A400)

**Comment by vassyz** [comment]
I have the same issue, not getting any notifications

### macOS version
13.2 (22D49)

### MeetingBar version
4.2.2

### Installation source
manual

### Calendars provider
Google Calendar

<img width="619" alt="Screenshot 2023-01-26 at 09 52 13" src="https://user-images.githubusercontent.com/1636476/214807165-d283dbcc-a1a3-4046-957b-bdf55dd11fd2.png">

<img width="474" alt="Screenshot 2023-01-26 at 09 52 55" src="https://user-images.githubusercontent.com/1636476/214807194-e5a3e73d-1c4c-4011-aea4-fe006f935962.png">

**Comment by jgoldhammer** [comment]
This should be solved in the newest release 4.3. Please reopen if this does not work for you. Thx.
