### ISSUE TITLE
Feature: Calendar Events deduplication

### ISSUE THREAD

**Issue by scyzoryck** [leits/MeetingBar#554]
### Issue that this suggestion fixes

I'm using 2 calendars connected to one mac. Sometimes it happens that I'm getting same invite for both calendars. In result event is visible twice with the same meeting link. 

### Solution description

We can deduplicate events in Meeting bar based on the meeting name, meeting time and meeting links

### Alternatives considered

None comes to my mind. 

### Additional context

Thanks for great software! It helps a lot on daily remote work!

**Comment by leits** [comment]
Thanks for the request!

It looks convenient, but there are many not so obvious corner cases.
Therefore, given that no one has upvoted this ticket, I will close it. Sorry!
