### ISSUE TITLE
Feature: Add Slack Huddle integration

### ISSUE THREAD

**Issue by gtrufitt** [leits/MeetingBar#555]
### Issue that this suggestion fixes

Slack now allows you to get a huddle link and it would be great to support this 

![image](https://user-images.githubusercontent.com/638051/204794650-2ff1eaf6-8569-4d60-b946-cad2fa664235.png)

### Solution description

When clicking on a meeting with a Slack huddle link as the location, it opens the link in slack

### Alternatives considered

'Open meeting link from clipboard' works when a huddle link is copied and I faffed about and got it working with the regex `https:\/\/app\.slack\.com\/huddle\/.+` which does then open the link in the browser and then in Slack for me

**Comment by leits** [comment]
Thanks for the request!
Support was added by @tsub in https://github.com/leits/MeetingBar/pull/556 today. I'm going to include it in the next release.

**Comment by gtrufitt** [comment]
Fantastic, thank you!
