### ISSUE TITLE
Bug: Need to restart the app for events to update / sync

### ISSUE THREAD

**Issue by sinewave** [leits/MeetingBar#558]
### macOS version

12.5.1 (21G83)

### MeetingBar version

4.2.2

### Installation source

AppStore

### Calendars provider

macOS Calendar app

### Bug description

I've noticed that in the past few weeks Meetingbar isn't detecting any changes to events unless I restart the app.

I'm using Apple Calendar to manage my events which primarily syncs with an MS Exchange Calendar. When I look at the Calendar app it's always up to date yet, MB is still showing outdated info.

Quitting and restarting the app fixes the issue.

### Additional context

Would love any help with this as this is making MB somewhat unusable as I've almost missed a few meetings now. I also tried searching for an existing issue but didn’t come across anything.

**Comment by thomasrene** [comment]
I got the exact same issue

**Comment by leits** [comment]
Thanks for the report!

Do you still have this problem with latest version, @sinewave, @thomasrene?

**Comment by leits** [comment]
I am closing this topic due to inactivity.
Feel free to reopen the issue if the problem still exists.
