### ISSUE TITLE
Bug: toolbar icon is missing, and is causing other icons to be missing, too

### ISSUE THREAD

**Issue by kholbekj** [leits/MeetingBar#561]
### macOS version

12.5

### MeetingBar version

4.2.2

### Installation source

AppStore

### Calendars provider

Google Calendar

### Bug description

The toolbar icon is mostly (but not always!) missing. In addition to that, it seems to push other icons "off" the bar. So that when I launch it, the net result is I have fewer toolbar icons than i did before, and nothing is clickable in the newly created empty space.

### Reproduction steps

Launch meetingbar

### Additional context

If there are any logs that would be helpful, please let me know. I'm not very savvy with OSX.

**Comment by ditkin** [comment]
Same problem here!
I'm on Monterey 12.01 with an Apple M1 Max, if it helps.

**Comment by ParksCF** [comment]
I am also experiencing this.

**Comment by mkcossin** [comment]
Same:

Monterey: 12.6.2
Version: 4.2.1
M1 Pro

**Comment by GabrieleCalarota** [comment]
Same on:

M1 Pro
Ventura: 13.1 (22C65)

**Comment by deathlyfrantic** [comment]
I have this same problem on an M1 Pro with Ventura 13.1, and suspect it has something to do with length of the meeting name. I just declined a meeting with a very long name and MeetingBar reappeared showing the next meeting after it, which has a much shorter name.

As an experiment, I created a dummy meeting on my calendar with a 50 character name, and MeetingBar disappeared again. I then changed the length of the name of the meeting until MeetingBar reappeared. For my setup, it seems like 34 characters is the max length a meeting name can be. At 35 characters, MeetingBar disappears.

As a workaround, setting the "shorten to XX characters" setting to 30 seems to have fixed the problem for my setup, on a 16" MBP:

<img width="509" alt="Screenshot 2023-01-18 at 9 08 05 AM" src="https://user-images.githubusercontent.com/7629614/213192619-ed3694db-54a1-4696-baf6-b588208f8eb6.png">

I'm guessing this will vary based on monitor size and number of other icons in the menu bar. Maybe this has something to do with the notch? 🤷‍♂️

**Comment by ParksCF** [comment]
> I just received my MacBook M2 and I'm having the same issue with the notch. I don't know how to open the app so I can change the settings now.

If you use an external monitor, it will display and you can change the preferences

**Comment by vassyz** [comment]
@ParksCF Thanks. I use an iPad as an external monitor but it doesn't have enough space either. I managed to solve it by changing the display setting to "More space". 👍

**Comment by icebearlabs** [comment]
@deathlyfrantic Thanks shortening the info fixed it for me, too! It apparently is a notch issue.

**Comment by kiview** [comment]
Can confirm it on my 14inch M2 MacBook Pro and it seemingly pushed my Docker icon away to be hidden. Noticed it specifically after detaching my external monitor.

**Comment by davidfranks** [comment]
Same issue here

**Comment by jgoldhammer** [comment]
We definitely know that this is a problem. I do not think that there is a real solution.
The underlying cause is the way how Apple handles menubars. Especially with the new notch the situation is worse than before because a full menubar means that macOS eats the overflowed items.

I do not see a real solution besides that we try to open the preferences dialog when you try to open meetingbar if it is already opened to be able to change the length of the meeting title. But in the end it does not really helps.

Additionally we should change the default for new installations to only show a dot for the event title.

<img width="478" alt="image" src="https://user-images.githubusercontent.com/3872101/224554450-6a95bc8d-ee16-4928-8bdd-60c74d88f9e1.png">

What do you think @leits?

**Comment by leits** [comment]
> Hi folks,
> Sorry for the delay. The app shows in the status bar only if there is enough space. Unfortunately, there is no way to detect whether the app is visible or not.
> 
> In the next version, I will add the ability to open the application settings via the meetingbar://preferences link.
> There you will be able to change the settings for the length of the meeting name and display rules in general.
> 
> In addition, I highly recommend using apps that remove unnecessary apps from the bar status, such as Dozer or Bartender 2.

https://github.com/leits/MeetingBar/issues/613#issuecomment-1676405319

Let's move the conversation to newer issue > #613
