### ISSUE TITLE
Feature: Make notifications "Time Sensitive"

### ISSUE THREAD

**Issue by mybuddymichael** [leits/MeetingBar#562]
### Issue that this suggestion fixes

MeetingBar notifications do not currently register themselves as ["Time Sensitive"](https://developer.apple.com/documentation/usernotifications/unnotificationinterruptionlevel/timesensitive). This means that notifications do not show if the user is in a focus mode that normally blocks notifications. MeetingBar notifications are inherently time sensitive (just like Calendar.app's notifications) and so should be set as time sensitive.

### Solution description

Update all notifications to be "time sensitive".

### Alternatives considered

I don't believe there are any alternatives. Time Sensitive notifications are the mechanism to provide this functionality.

### Additional context

I am not a macOS developer but I attempted to [implement this myself](https://github.com/leits/MeetingBar/compare/master...mybuddymichael:MeetingBar:time-sensitive-notifications). However it seems that I might need an Apple Developer Program account to add this capability to the app configuration? Any insight would be appreciated.

**Comment by leits** [comment]
Hi @mybuddymichael,
Thanks for the request!
I'll use your code as a base for this feature: https://github.com/leits/MeetingBar/pull/596

**Comment by leits** [comment]
Added to the next release scope: https://github.com/leits/MeetingBar/commit/e60b8c567884303818087f3d0bc86c28d148425c
