### ISSUE TITLE
Feature: some way to get to meeting invite

### ISSUE THREAD

**Issue by alexec** [leits/MeetingBar#566]
### Issue that this suggestion fixes

Sometimes a meeting comes up, and I'm too busy to attend. I want to be able to quickly decline the meeting. I have to go into Outlook to do that (I sync Outlook with Calendar using Exchange). 

### Solution description

I guess I want:

(a) Support for Outlook.
(b) A way to decline meetings.

### Alternatives considered

None

**Comment by jgoldhammer** [comment]
The new Outlook for Mac does not support Applescript at the moment, so it is not possible to jump directly to the appointment in Outlook.

We will follow the roadmap and I will try to extend it when it is ready.
https://www.microsoft.com/de-de/microsoft-365/roadmap?filters=&searchterms=88537

Cancelling appointments would be a great feature, so I will try to implement a cancel feature in the notification. Would this a good way to cancel the meeting?

**Comment by alexec** [comment]
I just update my description. “Cancel” is the term used when I cancel my own meeting. “Decline” is the term used to decline invites to other people’s meetings.

I don’t know how valuable declining meeting from the UI is.

\

**Comment by leits** [comment]
Hi,
Sorry for the delay. 

Apple still does not allow programmatically denying events so I will close this ticket due to a technical impossibility.
Sorry!
