### ISSUE TITLE
Feature: hide icon completely when there are no events

### ISSUE THREAD

**Issue by Samanm** [leits/MeetingBar#567]
### Issue that this suggestion fixes

Currently, the following icon appears in the menu bar when there are no events.

<img width="71" alt="Screen Shot 2022-12-20 at 3 41 08 PM" src="https://user-images.githubusercontent.com/863113/208786957-11946b0d-b8e2-43d9-8599-d4580a6a929f.png">

### Solution description

Instead, hide the icon completely when there are no more events coming up for the day

### Alternatives considered

NA

**Comment by leits** [comment]
Hi @Samanm,
Thanks for the request!
You can interact with MeetingBar only through this icon, so if remove it, you will completely lose the ability to interact with the app. So I'm sorry, but I have to decline this request because it's intentional by design.

**Comment by lecodeski** [comment]
Hi all 👋 I was interested in this feature, too.
What about to start interaction with the app by normally opening it (from Dock or Launchpad or however). This way it would start if not running in background already. Or open the preferences if already running. Then from the preferences one could choose to show or hide a sole icon.
I know this behaviour from other background apps.

**Comment by Samanm** [comment]
@leits I agree with @lecodeski above. I know many apps utilize the same approach by offering an icon in the Dock.
