### ISSUE TITLE
Option to show only menu bar icon

### ISSUE THREAD

**Issue by leits** [leits/MeetingBar#57]
From @advicepyro

Hi there! Nice app, really like the ability to see event details on the menu.

I'd like to see the option of having the menu bar icon show without changing into an upcoming events timer, or a timer for the current event.

**Comment by Itaybre** [comment]
@leits I am working on this

**Comment by jgoldhammer** [comment]
This is now possible with the unreleased version of meetingbar.

![image](https://user-images.githubusercontent.com/3872101/103651551-143f1580-4f62-11eb-8f08-b8cd4b551ffd.png)
![image](https://user-images.githubusercontent.com/3872101/103651602-291ba900-4f62-11eb-8dbc-ebde2ba3ddf4.png)

**Comment by leits** [comment]
@advicepyro released! Check it out!
