### ISSUE TITLE
Feature: Automatically open the virtual meeting link X minutes before the meeting

### ISSUE THREAD

**Issue by salonluden** [leits/MeetingBar#570]
### Issue that this suggestion fixes

Although the app clearly states the next meeting, sometimes you still don't consistently look at the bar / calendar app (your too immersed in solving something else, etc.)

### Solution description

Have the option to open meeting links automatically X minutes before they start (with a startup sound?). This since most meeting apps have a screen before actually joining, this would save time but still keep your privacy.

### Alternatives considered

NA

**Comment by bigethan** [comment]
![Screen Shot 2023-01-05 at 12 11 09 PM](https://user-images.githubusercontent.com/627/210871084-b8a6f2bb-4ee6-4010-84a7-c4775ad29f7f.png)

It feels like the app already does this?

**Comment by salonluden** [comment]
I'm embarrassed to say I thought I went through the whole app looking for this - this app is truly amazing

**Comment by leits** [comment]
@salonluden thank you and have nice meetings!
