### ISSUE TITLE
Feature: Run AppleScript on keyboard shortcut

### ISSUE THREAD

**Issue by neilkimmett** [leits/MeetingBar#573]
### Issue that this suggestion fixes

When I'm working from my office I need to dig into a meeting's notes to find the Zoom meeting id and passcode so I can join from a conference room. I've written up a nice AppleScript that finds these from the meeting notes and displays a dialog with them (can share if interested) **but** instead of running this script on every meeting, I want to run it "on-demand" when I decide to go into a conference room.

### Solution description

An extra row in the "Advanced" section of the app preferences:

`Run AppleScript when you press <keyboard shortcut>            <Edit script>`

### Alternatives considered

I thought about writing my own app to do this but so many of the moving parts are already here!

### Additional context

I'm an iOS developer, already poked around in the code and it looks like this will be pretty easy to add. I am **more** than happy to do so myself in the next few days, I just wanted to get a 👍 from you that its a feature you'd be interested in supporting?

**Comment by slawekp** [comment]
Alternative solution: save your AppleScript as an app in Applications and then add a keyboard shortcut to it

https://support.apple.com/en-gb/guide/mac-help/mchlp2271/mac

**Comment by leits** [comment]
https://github.com/leits/MeetingBar/pull/575#issuecomment-1460488397
> Hi @neilkimmett. Sorry for the delay!
You can get the same result in a few clicks with the built-in macOS app Shortcuts.
Thank you for the request and the implementation but sorry, but I'll close this PR to not inflate the application's functionality.
>
> Share late if you managed to set up Shortcuts!

Sorry!
