### ISSUE TITLE
Feature: Autojoin meeting that has a link when there are simultaneous "meetings"

### ISSUE THREAD

**Issue by bigethan** [leits/MeetingBar#574]
### Issue that this suggestion fixes

I have a "lunch" meeting, but often someone schedules over it. This leaves me with two simultaneous meetings: one that has a meeting link and ones that does not. This means that when the time comes the autojoiner doesn't fire on the right meeting (as the lunch meeting was created "first" - not sure how it sorts, but it's always wrong).And as I depend on the autojoiner, I'm always late to those meetings.

I don't want to filter my lunch meeting from meetingbar, as I appreciate it being in the menubar when it's appropriate.

### Solution description

If there are multiple meetings starting when checked, the auto joiner would skip meetings without a link and fire when a meeting has a link rather than alert that the meeting doesn't have a link and ending there.

### Alternatives considered

I thought about filtering out the meetings with no other attendees, but I like having those on meetingbar

### Additional context

This is the setup where meeting bar will notify that there's no link to join (for Lunch), but the meeting with Jake certainly does have a link

![Screen Shot 2023-01-11 at 12 23 55 PM](https://user-images.githubusercontent.com/627/211910103-57c57256-0059-4235-9992-1212775aeafc.png)

**Comment by bigethan** [comment]
Repro steps:

- Schedule a meeting without VC link
- Schedule another meeting at the same start time that _does_ have VC link.
- Wait for the auto-join check to run

You'll get a "this meeting doesn't have a link" alert and the meeting with the VC isn't processed when the autojoin check runs. I'm not sure why the one without the link is always processed first, but that always seems to be the case for me.

**Comment by leits** [comment]
Thanks for the request @bigethan!
Added to the next release scope.
