### ISSUE TITLE
Bug: Unclickable links in event description

### ISSUE THREAD

**Issue by viewsourc3** [leits/MeetingBar#579]
### macOS version

13.1 (22C65)

### MeetingBar version

4.2.2

### Installation source

AppStore

### Calendars provider

macOS Calendar app

### Bug description

Invitation created with Skype Business have embedded links, displayed in the calendar as this : 

[Join Skype meeting here]() 

These links are not seen by Meetingbar, which only sees "Join Skype meeting here", and thus cannot launch the meeting. 

It seems like MeetingBar only sees url which are in play text in the invitation. 

Ex. https://meet.google.com/....

I would expect embedded links to be clickable or recognized by MeetingBar. 

### Reproduction steps

This is is a screenshot of the invitation notes as seen by MeetingBar. 

![SCR-20230120-ahf](https://user-images.githubusercontent.com/76497381/213632529-27da1bc4-e816-424e-839b-4679572be2b7.png)

The address of the meeting is embedded in the text "Participer à une Réunion Skype" and can be seen on the Calendar app (As seen below), or Outlook app. But not by MeetingBar which only keeps the text "Participer à une Réunion Skype" and not the Skype Business URL it points to.

![SCR-20230120-ajt](https://user-images.githubusercontent.com/76497381/213632902-fea871a4-e344-42a3-9dd1-ff901be0faa7.png)

### Expected behavior

I expect the html markup to be interpreted by MeetingBar as an URL

**Comment by leits** [comment]
Hi @viewsourc3,
After several iterations of displaying text in this field, this is the best we've come up with. Therefore, unfortunately, there are no planned changes here. Sorry.
