### ISSUE TITLE
Bug: notifications still shown for Google cal when "do not notify" set

### ISSUE THREAD

**Issue by kolakode** [leits/MeetingBar#580]
### macOS version

13.2

### MeetingBar version

4.2.2

### Installation source

AppStore

### Calendars provider

Google Calendar

### Bug description

Notifications are still displayed for Google calendar entries with "do not notify" (no notifications) set.

### Reproduction steps

1. create reoccurring meeting in Google calendar and make sure there are no notifications for the event
2. ensure Meeting Bar preferences are using Google calendar and notification are enabled and set to 5 minutes before the meeting
3. ensure macOS notifications in System Preferences for Meeting Bar is set to "badges, sounds, alerts"
4. observe that at 5 minutes before reoccurring meeting you will get a notification alert about the meeting

### Expected behavior

Calendar entries without any notifications set should not display notification alerts.

**Comment by leits** [comment]
Hi @kolakode,
MeetingBar acts in the same way as the macOS Calendar and don't take Google Calendar reminders settings into account.
We decided to leave it as is to have a unified and predictable behavior.

And since there are no more supporters of this feature, I'll close this ticket, sorry.
