### ISSUE TITLE
Feature: AI assistance

### ISSUE THREAD

**Issue by alexec** [leits/MeetingBar#586]
### Issue that this suggestion fixes

I don't want to click or type anything anymore. It is 2023, I want AI to do it for me.

I want to say: "MeetingBar: skip meeting" or "MeetingBar: create a new event and invite these people"

### Solution description

AI

### Alternatives considered

Human, human rejected

**Comment by jgoldhammer** [comment]
Thanks for your request. 

We could solve that by using Apple Shortcuts to trigger these features. 
What should happen with "skip meeting"? Is this "Dismiss meeting" or a real cancellation of the meeting? For real cancellation you could use Siri.

For creating events you could use Siri with the built-in calendar. What should be different with Meetingbar?
What do you think, @alexec?

Thanks
Jens

**Comment by alexec** [comment]
Good idea. I want to ignore some meetings.

**Comment by leits** [comment]
Hi @alexec,

I added "Dismiss Nearest Meeting" AppIntent to the next release scope.
After release, you can find it in Shortcuts app and use it with Siri.

**Comment by leits** [comment]
Released 🚀
