### ISSUE TITLE
Feature: Show many many accepted invite

### ISSUE THREAD

**Issue by alexec** [leits/MeetingBar#589]
### Issue that this suggestion fixes

I sometimes schedule meeting and the require attendees do not accept the invite.

### Solution description

I’d like to see a count X/Y of the number of people who have accepted so I can, at a glance, chase them.

### Alternatives considered

Do nothing?

**Comment by leits** [comment]
Thanks for the feature request

You already can do it with a detailed event view!
Rejected participants are marked with a strikeout, and tentative participants are marked with "[tentative]".
