### ISSUE TITLE
Open Calendar event in Submenu

### ISSUE THREAD

**Issue by dev10110** [leits/MeetingBar#59]
**Is your feature request related to a problem? Please describe.**
Feature Request. 
When I click into the details of an event in the meeting bar, I can't click anything, especially links that are embedded in the event details.

**Describe the solution you'd like**
I would like to be able to click somewhere to open my calendar (hopefully to the specific event) so I can see all the details. 

**Describe alternatives you've considered**
Currently, I just open the calendar separately, find the event and open the links.

**Comment by dev10110** [comment]
Addressed by #60, but not fully - calendar app can be opened, but not to a specific event.

**Comment by leits** [comment]
Thanks, @dev10110!
It's a great idea to open a calendar app for the event!

I think the opening event in the calendar is much more valuable than the calendar opening. 
This can be done easily in other ways, as opposed to opening an event in the calendar.

Did you try to use `calshow:` URI scheme? Maybe it will works as you want.

**Comment by dev10110** [comment]
I tried, but I am not familiar with the URI scheme, and couldn't figure out what the right URI should be.
If you point me in the right direction, I'll implement it!

btw, for mac it seems we need to use `ical`, `calshow` is for iOS (?).

**Comment by leits** [comment]
@dev10110 , looks like I found the way:
`let url = URL(string: "ical://ekevent/\(identifier)")`

Try it when you'll have a time.

**Comment by dev10110** [comment]
@leits  thats awesome!! and it works! 

im just (very) new to Swift in general, and can't figure out how to pass the event identifier as an argument from `StatusBarItemController.swift` into `AppDelegate`. If you point me in the right direction I can try it again.

**Comment by leits** [comment]
@dev10110 added in https://github.com/leits/MeetingBar/releases/tag/v2.0.
Check it out!
