### ISSUE TITLE
Feature: Auto-open links in meeting invite

### ISSUE THREAD

**Issue by alexec** [leits/MeetingBar#591]
### Issue that this suggestion fixes

My meeting invites almost always contain a link to the meeting agenda. I would like that automatically opened when the meeting starts.

### Solution description

Open the agenda automatically.

### Alternatives considered

Nothing

**Comment by jgoldhammer** [comment]
This already works. Please activate the feature in the advanced section.

**Comment by alexec** [comment]
I don't see an option title "open all Google Docs links in meeting invite" or similar?

<img width="691" alt="image" src="https://user-images.githubusercontent.com/1142830/220978742-97a40edb-bdd0-4cd4-a11e-6fcb854beff5.png">

**Comment by leits** [comment]
Sorry, but it's kind of an overhead for the app.

But it can use Run AppleScript when joining a meeting with a script that will open your agenda based on event notes 👀
