### ISSUE TITLE
Feature Request - MenuBar Delimiter

### ISSUE THREAD

**Issue by starck22** [leits/MeetingBar#592]
Would like a feature that only adds the text up to a certain character for the Menubar. For example:

"Some text here - some text there" and I chose "-" as my delimiter, then in the menubar, I would only see "Some text here". If there is no delimiter, then all the text would show. If there were multiple delimiters, then it would show up to the first one only.

Very helpful if you have multiple meetings that follow a pattern (like multiple one on one meetings).

**Comment by leits** [comment]
Thanks for the request, @starck22 

Sorry, I don't think we'll be adding this feature to the already very bulky settings.
