### ISSUE TITLE
Bug: high cpu and energy use

### ISSUE THREAD

**Issue by BlaineEXE** [leits/MeetingBar#597]
### macOS version

13.2.1

### MeetingBar version

4.2.2

### Installation source

AppStore

### Calendars provider

macOS Calendar app

### Bug description

You can see that MeetingBar is amongst my highest 12-hour power uses. It's notably 6x higher than Meeter, which is a similar application. It is regularly in my top 3 energy users despite using Slack, Signal, and Outlook quite a lot at work. I notice MeetingBar regularly using 40-60% of a CPU core.

![image](https://user-images.githubusercontent.com/3989526/224088279-a8abef59-a8a7-49bc-a91d-7a2ac950befa.png)

Tested on a MacBook Pro M1 Max.

I prefer MeetingBar to Meeter, but the CPU issue is a big turnaway for when I need to just work on documents rather than hardcore coding like in the screenshot. 
(In MeetingBar, I love the feature of being able to see my meetings' descriptions from the menu bar to easily open meeting minutes! 1000 IQ play)

### Expected behavior

MeetingBar should not use very much energy. It definitely shouldn't be in my top 3 energy users. Frankly, even Meeter's energy usage seems high to me compared to Outlook from my screenshot, which I use constantly.

**Comment by leits** [comment]
Thanks for the report!

Included a few optimizations in the 4.5 version. Please, check it out!

**Comment by leits** [comment]
I am closing this topic due to inactivity.
Feel free to reopen the issue if the problem still exists.
