### ISSUE TITLE
Sometimes the time get's stuck

### ISSUE THREAD

**Issue by durdevic** [leits/MeetingBar#6]
**Describe the bug**
The time just get's stuck and now counting correctly

**To Reproduce**
Don't know how to reproduce, just happens

_**Should be 13 min left**_
<img width="796" alt="Screenshot 2020-06-02 at 16 47 10" src="https://user-images.githubusercontent.com/2753836/83536380-6cf19000-a4f3-11ea-8303-b6ebfeeea115.png">

**Desktop (please complete the following information):**
 - macOS version: 10.15.5

**Comment by leits** [comment]
Thanks for the bug report.

How often it's happening?

**Comment by durdevic** [comment]
Today was fine, I'll let you know if it comes up again.

**Comment by leits** [comment]
@durdevic, did this happen to you again?

**Comment by durdevic** [comment]
Everything is fine up until now, so I'm gonna close this one, and let you know if something happens later on.

**Comment by quentinms** [comment]
Happens to me every other day or so. 
What info do you need from me to debug this?

**Comment by durdevic** [comment]
Got stuck again 

![Screenshot 2020-08-10 at 16 14 39](https://user-images.githubusercontent.com/2753836/89792493-e70e4880-db24-11ea-864c-675398e62a87.png)
