### ISSUE TITLE
Feature: Add Google Meet (Progressive Web App) support in Services dropdown

### ISSUE THREAD

**Issue by DominikTo** [leits/MeetingBar#601]
### Issue that this suggestion fixes

Would be great if one could select the Google Meet app (progressive webapp: https://support.google.com/meet/answer/10708569?hl=en) in the "Open with" Services configuration.

### Solution description

Add support for Google Meet Progressive Webapp

### Alternatives considered

n/a

**Comment by leits** [comment]
Hi @DominikTo ,
Thank you for your request! Unfortunately, PWAs cannot open links on their own.
But you can enable link handling in Chrome with this guide:
https://developer.chrome.com/docs/web-platform/declarative-link-capturing/
With this Chrome will automatically open Google Meet PWA for all meet links.

**Comment by sgtsquiggs** [comment]
Declarative Link Capturing was cancelled and they now have another method for capturing:
<img width="823" alt="image" src="https://user-images.githubusercontent.com/3420325/232819629-f1277e80-df66-4717-a6b8-1101a06fd88a.png">
https://developer.chrome.com/docs/web-platform/declarative-link-capturing/#migration

**Comment by leits** [comment]
This is great. Looking forward to seeing the Google Meet team roll this out!
