### ISSUE TITLE
Feature: Auto join only accepted meetings

### ISSUE THREAD

**Issue by chrneu** [leits/MeetingBar#604]
### Issue that this suggestion fixes

Currently if you check the auto join feature, all events which are displayed will be joined. 

If you have multiple events at the same time, maybe also as a placeholder or you are not sure if you can join it and are therefore not accepted yet still will be joined automatically.

### Solution description

It would be nice to have another checkbox to select if you also want to auto join not responded meetings.

### Alternatives considered

It seems to be possible to add custom regex which is not suitable as an easy digest solution.
You could exclude the open meetings in the settings. But as a user maybe wants to join the meeting on a short notice the meeting should not be removed from the calendar.

**Comment by leocaseiro** [comment]
I would love this feature, to only join meetings that are confirmed, but not maybe ones.
I am not familiar with Swift or Objective-C, is that too hard to implement?

**Comment by leocaseiro** [comment]
Is it possible to filter only confirmed meetings by regex? I need to learn that...

**Comment by leocaseiro** [comment]
Sorry @leits, why is this issue closed if is not available yet?
