### ISSUE TITLE
Feature: support focus mode

### ISSUE THREAD

**Issue by oliverandrich** [leits/MeetingBar#605]
### Issue that this suggestion fixes

Meeting Bar is awesome, but for my workflow it is missing a single feature. Support for the new focus system of macOS. I rely on this functionality to only see work events on workdays or when I am not in focus mode. It would be cool, if Meeting bar would also support this feature by only showing events from calendars that are currently active in the current selected focus.

### Solution description

If I activate a focus which filters the available calendars in the Calendar.app, I want MeetingBar to only show events from these active calendars.

### Alternatives considered

Add focus support to MeetingBar, then I will configure MeetingBar with the same filters as Calendar.app.

**Comment by leits** [comment]
Thanks for the request, @oliverandrich!

Although Calendar app itself displays filters, as a datasource it does not allow you to take them into account in any way when receiving data.

Therefore, I am sorry, but there is no technical possibility to do this. :(

I will keep an eye on the API and if the functionality appears, I will add support to MeetingBar.
