### ISSUE TITLE
Feature: Open Slack huddle directly in Slack

### ISSUE THREAD

**Issue by ekrapfl** [leits/MeetingBar#609]
### Issue that this suggestion fixes

It is annoying when links have to open a new browser tab, then launch in the correct app.

### Solution description

It would be amazing if Slack huddle links could open directly in the Slack app (similar to how it works for Teams and Zoom links):
<img width="649" alt="image" src="https://user-images.githubusercontent.com/5939413/232068517-10be1a52-e36f-448b-a8d5-e0ddd41afa50.png">

### Alternatives considered

It works now with a browser tab in between, it is just annoying.  First world problems ¯\\\_(ツ)_/¯

**Comment by leits** [comment]
Thanks for the request, @ekrapfl
Added to the next release scope!

**Comment by leits** [comment]
Released 🚀
