### ISSUE TITLE
🚀 Public beta: 1.4 

### ISSUE THREAD

**Issue by leits** [leits/MeetingBar#61]
Hi folks!

**A new release with a huge number of new features is ready!**
I need your feedback to make this version more stable.

----------
Check the full list of features and bug fixes here:
https://github.com/leits/MeetingBar/issues?q=milestone:1.4
(except LaunchAtLogin feature (_WIP_))

DMG is here: https://github.com/leits/MeetingBar/releases/download/v1.4.rc3/MeetingBar.dmg

----------

Thank you all for sharing your ideas, reporting bugs, and joining the discussion!

@dev10110 #54 
@antkiselev #52 #53 
@sweiland, @chaseadam #50 
@advicepyro #49 
@dommerq #48 
@jt2k, @cromulus, @AnthonySmith01 #46
@wayneashleyberry #44 
@sn0wyfall #40 #42 #43 
@insipidlight #43
@Rucknar #40
@FrankKair #39
@globau, @vforge #38 
@dutzi #35 #36 
@jamesray #32 
@usmanity #31 
and many others who create&upvote issues and support MeetingBar on Patreon!

**Comment by AnthonySmith01** [comment]
Thanks! great work, still one of my favourite little apps.

**Comment by dutzi** [comment]
Nice! Looks really good 👍

**Comment by advicepyro** [comment]
Thanks @leits! Wanted to report though Zoom links aren't working, whether it's the default browser or the native Zoom app. This is either clicking the notification to join, or clicking the event name in the menu.

**Comment by leits** [comment]
Thanks, @advicepyro. Can you give an example of a link? And where is it stored in the location or in the notes?

**Comment by chaseadam** [comment]
I can report the same
> Zoom links aren't working, whether it's the default browser or the native Zoom app.
Attached is an example meeting entry in OS X Calendar
![image](https://user-images.githubusercontent.com/333031/91877788-77cfd400-ec4c-11ea-91ac-0a7712053062.png)

**Comment by insipidlight** [comment]
@advicepyro @chaseadam See #43, probably more useful than the release thread 🙂

**Comment by leits** [comment]
@insipidlight @advicepyro @chaseadam  I made Zoom links regex less specified for better handling.
https://github.com/leits/MeetingBar/releases/download/v1.4.rc2/MeetingBar.dmg
Please, try it now

**Comment by advicepyro** [comment]
Unfortunately links are not working still. They were fine in the last stable release. Either 'default browser' or 'Zoom app' causes the Zoom app to open if it wasn't open already, but beyond that nothing happens.

My settings for apps (default browser doesn't work either):
<img width="682" alt="Screen Shot 2020-09-01 at 4 23 36 PM" src="https://user-images.githubusercontent.com/6377466/91902924-6d273600-ec70-11ea-8613-bd5ee44e545a.png">

The event details look like this in the submenu:
<img width="343" alt="Screen Shot 2020-09-01 at 4 24 33 PM" src="https://user-images.githubusercontent.com/6377466/91902952-757f7100-ec70-11ea-809f-bbd83e273861.png">

Zoom app is the latest 5.2.2

**Comment by leits** [comment]
Thanks to @advicepyro , I finally understood where the problem was.
In fact, there were even two of them, and none of them was regex.
1. Ignoring app config and always try to open Zoom links in the app
2. A small difference in zoommtg protocol for Zoom app with http zoom links from the calendar

I finally managed to reproduce both bugs and fix them.
@advicepyro Please, try one more time:
https://github.com/leits/MeetingBar/releases/download/v1.4.rc3/MeetingBar.dmg

**Comment by dev10110** [comment]
Hi @leits, 

Just wanted to raise another issue that's kinda weird. 

Here is what v1.4 is showing me

<img width="567" alt="Screenshot 2020-09-02 at 11 15 47 PM" src="https://user-images.githubusercontent.com/26798612/92002334-57019e80-ed72-11ea-9e22-a77867bd47ed.png">


and here is the set of events coming up:
Today 23:30 - Tomorrow 01:00 : Aerosp 584
Tomorrow 1:30 - Tomorrow 2:30 : ME564

Heres a small part of my calendar for reference.
<img width="1620" alt="Screenshot 2020-09-02 at 11 22 04 PM" src="https://user-images.githubusercontent.com/26798612/92003037-20785380-ed73-11ea-81bf-6cd68ec599be.png">
so I'm unsure about why the first entry is ME540 today. 
If it helps, I had ME 540 yesterday from 23:30 - 01:00

I just checked - this is happening in V1.3 as well. 

I wonder if the issue is to the timezones - my events were created in US Eastern time, but my calendar here is in Singapore time.

-- 

Also an event that starts today but ends tomorrow seems to be in both today and tomorrow's list of events but I can live with that. 

Sorry this is such a weird edge case of users, if you don't want to support it I'm fine with that

**Comment by dev10110** [comment]
OHHH nvm, I just figured out what was happening. It was showing me yesterdays event that ended today (ME 540) as part of today's events. 

So i think both issues I just raised are actually the same - you just need to classify today vs tomorrow based on when they started, not when they ended. 

This might raise some issues for multi-day events...

Here is a proposed fix. 

In the headings, label it as "Started on ..." but allow events to be visible in the meeting bar if they are still going on or are coming up in the upcoming future?

**Comment by leits** [comment]
Thanks, @dev10110 !
I added filtration for events here https://github.com/leits/MeetingBar/commit/823bed00275783ce390e6a027b0660473343c60f and https://github.com/leits/MeetingBar/commit/48a52aa45ab607702fe8f7fff667b8c87da8748b.
First for hiding events that start not today and the second to show all-day events that start not today.

**Comment by dev10110** [comment]
@leits Awesome! Thanks for the really quick update :) I just built the app and its looking good. 

Currently the events that are tomorrow but start today but end tomorrow are repeated in both today and tomorrow (see ME540 in the attached, but this is something I'm personally alright with. Just putting it here for reference. 

<img width="478" alt="Screenshot 2020-09-03 at 1 12 44 AM" src="https://user-images.githubusercontent.com/26798612/92015148-ed3dc080-ed82-11ea-8a63-317644b1799d.png">

**Comment by advicepyro** [comment]
@leits the native app links are working on my end, thanks 👍

**Comment by leits** [comment]
MeetingBar 1.4 released 🚀 
Thank you all!
