### ISSUE TITLE
Bug: Freezing when joining meeting by hotkey

### ISSUE THREAD

**Issue by rkrueger11** [leits/MeetingBar#610]
### macOS version

13.3.1 (22E261)

### MeetingBar version

4.4.0

### Installation source

Homebrew

### Calendars provider

Google Calendar

### Bug description

Out of nowhere, MeetingBar now freezes up and starts "Not Responding" when using hotkey to join meeting. Requires me to kill the app using Activity Monitor.

### Reproduction steps

1. Use hotkey to join an upcoming meeting.
2. MeetingBar freezes and shows "not responding" in Activity Monitor.
3. Kill in Activity Monitor

### Expected behavior

1. Use hotkey to join an upcoming meeting.
2. Successfully join meeting in Zoom.

**Comment by leits** [comment]
Thanks for the report!

Included a few optimizations in the 4.5 version. Please, check it out!

**Comment by leits** [comment]
I am closing this topic due to inactivity.
Feel free to reopen the issue if the problem still exists.

**Comment by mig8447** [comment]
I'm experiencing this whenever I click or open by shortcut. I upgraded to 4.6.0 and nothing change, I'm starting to think that my settings are the cause. @leits is there any way of resetting the settings or just delete the plist file?
