### ISSUE TITLE
Bug: App does not open (does not show in menu bar)

### ISSUE THREAD

**Issue by noozo** [leits/MeetingBar#613]
### macOS version

13.2.1 (22D68)

### MeetingBar version

4.4.0

### Installation source

AppStore

### Calendars provider

macOS Calendar app

### Bug description

When running from the command line:

![image](https://user-images.githubusercontent.com/3353/233329452-f5739a41-0639-4146-870f-1bf0d7a4ba8b.png)

### Expected behavior

The menu bar button shows and i can see my meetings.

**Comment by spencer-barton-kobold** [comment]
I'm on 13.3.1 and seeing similar. MeetingBar process is running however nothing appears in the toolbar. @noozo How did you fetch those logs?

**Comment by skyloud22** [comment]
I am facing the same issue. In the activity monitor

**Comment by spencer-barton-kobold** [comment]
In my case it was fixed by removing more icons from the toolbar!

**Comment by ronothan** [comment]
Same issue with me too, also on MacOS 13.3.1.  - Icon not being displayed, and cannot see anything working.

**Comment by richardklose** [comment]
Same here on Mac OS 13.3.1 with MeetingBar 4.4.0 from AppStore as well as Homebrew.

**Comment by gregsadetsky** [comment]
This is a reoccurring problem for me as well. I just upgraded to version 4.4.0 running on macOS 12.4. In the Console app, I see:

```
MeetingBar  Firing reccuring updateStatusBarItem
MeetingBar  [leits.MeetingBar] Requesting authorization with options 7
MeetingBar  [leits.MeetingBar] Requested authorization [ didGrant: 1 hasError: 0 hasCompletionHandler: 1 ]
```

happen over and over, which seems like everything is working i.e. "didGrant: 1" so... MeetingBar should have access to my meetings? i.e. there aren't any obvious errors..?

Thanks!

**Comment by lbain** [comment]
I'm on version 4.5.0 and MacOS 13.4.1 and have the same issue.

**Comment by leits** [comment]
Hi folks,
Sorry for the delay. The app shows in the status bar only if there is enough space. Unfortunately, there is no way to detect whether the app is visible or not.


In the next version, I will add the ability to open the application settings via the [meetingbar://preferences](meetingbar://preferences) link.
There you will be able to change the settings for the length of the meeting name and display rules in general.

In addition, I highly recommend using apps that remove unnecessary apps from the bar status, such as Dozer or Bartender 2.

**Comment by gregsadetsky** [comment]
I wish I could reclaim the notch space then!! :-) Thanks for the explanation @leits! And the great app! Cheers

**Comment by ronothan** [comment]
4.5.1 appears to have fixed this issue. I'm not on MacOs 13.4.1

**Comment by benrki** [comment]
does this mean it is impossible to display meetingbar on some devices?

for example, the 13" mbp has very limited menu bar room with the notch. even after hiding as many menu bar items as i can (using hidden bar)

<img width="1280" alt="image" src="https://github.com/leits/MeetingBar/assets/4446950/10bd94f3-aa83-4f66-8172-5f9264ea2951">

still useful when using an external screen
would be fantastic if automatically hiding on was a checkbox so i can control the visibility same as other menu bar apps

**Comment by timodonoghue** [comment]
I use [Bartender 4](https://www.macbartender.com/) to make sure that MeetingBar gets the space it needs.  For me, MeetingBar is one of the most important apps in my menu bar so it gets the space.  But looks like you can use [Hidden Bar](https://apps.apple.com/us/app/hidden-bar/id1452453066?mt=12) or [Dozer](https://github.com/Mortennn/Dozer) to do the same / similar.

(Makes note to take a look at Hidden Bar which I wasn't aware of...)

**Comment by lbain** [comment]
Resolved for me! The icon shows up and I get notifications again 😄 Thank you!
