### ISSUE TITLE
Feature: Completely invisible when no upcoming meetings

### ISSUE THREAD

**Issue by the-baaron** [leits/MeetingBar#614]
### Issue that this suggestion fixes

The overload of icons in the top bar on Mac OS. There are already too many icons, and while I love using MeetingBar, I think it doesn't have to be visible all the time.

### Solution description

I think that hiding MenuBar when there are no upcoming meetings, would be a great feature to have. When the user wants to access the settings, they can simply run the menubar app again. If menubar is already running in the background, that could trigger the settings screen.

### Alternatives considered

-

**Comment by technicalpickles** [comment]
In case it is helpful, I think you can greatly reduce how frequently it's shown and how much is shown.

1. Be aggressive with what you hide:

![CleanShot 2023-05-09 at 10 24 02](https://github.com/leits/MeetingBar/assets/159/a643ddc8-0e8a-41f5-9df3-19d311850220)

2. Reduce what's shown for an event, ie: 
![CleanShot 2023-05-09 at 10 25 27](https://github.com/leits/MeetingBar/assets/159/a7b5e2fa-0f0c-440f-a749-3ac46c1188fa)


3. Adjust down to whatever you feel is appropriate:

![CleanShot 2023-05-09 at 10 22 46](https://github.com/leits/MeetingBar/assets/159/381159eb-bd38-4b94-81ab-e9e8b176d432)

Between those, you can hide it _most_ of the times. It seems that you can't fully get rid of it, even if you hide all the event details, there is a blank spot you can click.

---

Not a way to address within MeetingBar, but I am a fan of [Bartender](https://www.macbartender.com/) which lets tweak what is shown and when in the bar. There is even conditional logic so you could hide if you did something like... show the meeting icon and event title, and configure it to hide if it matches just the icon.

**Comment by leits** [comment]
Thanks for the request @the-baaron.

And thanks for the response @technicalpickles! These are great tips for minimizing the presence of the MeetingBar in the status bar.

It won't be possible to hide it completely, because there is no other possibility to interact with the app besides the status bar.
