### ISSUE TITLE
auto-join only accepted meetings

### ISSUE THREAD

**Issue by staubda** [leits/MeetingBar#616]
It would be great if there was a setting that could let you only auto-join meetings that you've accepted. Currently (as far as I can tell) auto-join forces me to join meetings I haven't confirmed I'll attend. Thanks!

**Comment by leits** [comment]
Thanks for the request, @staubda 

I'll close this one as a duplicate of existing #608

**Comment by staubda** [comment]
@leits is this a duplicate? at a glance it seems like a completely different issue to me

**Comment by leits** [comment]
Sorry, wrong link!
https://github.com/leits/MeetingBar/issues/604
