### ISSUE TITLE
Bug: Need to update regular expression for matching a Gong meeting link domain/URL

### ISSUE THREAD

**Issue by sleach** [leits/MeetingBar#618]
### macOS version

13.3.1

### MeetingBar version

4.4.0

### Installation source

AppStore

### Calendars provider

Google Calendar

### Bug description

Hey all - thanks for adding Gong support to the product. There are some additional domain names you need to account for to properly spot Gong links.

The current regexp is:
`let gong = try! NSRegularExpression(pattern: #"https?://join\.gong\.io/.*"#)`

There are additional host names that look like:

`us-[\d]+.join.gong.io`

that would be good to add. So maybe just anything `join.gong.io` and `.join.gong.io` given others outside the US might have different hostnames.

Thanks!

### Reproduction steps

Just have a Gong meeting on your calendar with that new hostname format.

### Expected behavior

MeetingBar should see the extended format of Gong domain names/URLs to match and identify it as a Gong meeting.

**Comment by leits** [comment]
Thanks, @sleach!
Added to the next release scope!
