### ISSUE TITLE
Bug: Meeting titles aren't shown in menu bar or notifications, just "Meeting"

### ISSUE THREAD

**Issue by statico** [leits/MeetingBar#621]
### macOS version

13.2.1 (22D68)

### MeetingBar version

4.4.0

### Installation source

manually

### Calendars provider

Google Calendar

### Bug description

Meeting names aren't shown in the menu bar or notifications, just "Meeting." It used to show the title of the meeting, and the titles are shown in the dropdown.

### Reproduction steps

1. Use MeetingApp, connect to Google calendar
2. Everything works fine except for seeing the meeting name 

### Expected behavior

The title of the meeting should be shown and truncated in the menu bar and notifications.

### Screenshots/screen recordings

![CleanShot 2023-05-25 at 12 05 38](https://github.com/leits/MeetingBar/assets/137158/48be936d-8859-402c-9a57-3db0d61b6b7a)
![CleanShot 2023-05-25 at 12 06 19](https://github.com/leits/MeetingBar/assets/137158/26848c4d-9a21-460a-bb62-f4cef362b659)

### Additional context

Great app. Thank you so much!

**Comment by jgoldhammer** [comment]
Can you check if you have checked the option "Hide meeting title"?

<img width="748" alt="image" src="https://github.com/leits/MeetingBar/assets/3872101/c44b381f-f85d-4278-99eb-0ad1a90220c9">

**Comment by statico** [comment]
How in the world did I click this? I'm a dope 😂

Thank you.

**Comment by pmuntyanu** [comment]
I experienced this issue as well. This is not obvious IMHO. I would suggest removing the option or adding it to the preferences window
