### ISSUE TITLE
Bug: Very high battery use

### ISSUE THREAD

**Issue by nikjft** [leits/MeetingBar#623]
### macOS version

13.4 (22F66)

### MeetingBar version

4.4.0

### Installation source

AppStore

### Calendars provider

Google Calendar

### Bug description

With MeetingBar active, my MacBook's (Pro M1 Max) battery depletes extremely rapidly - getting ~3 hours of battery life instead of 8+ without MB running. This makes it utterly unusable if I'm not plugged in.

I do have an unusually large number of calendar events (my task lists all publish to my calendar), but even still, this seems excessive.

When I watch MeetingBar in Activity Monitor, it regularly shows an "energy impact" of 80 when it's idle, and then it bumps up to 150 - 400 intermittently (presumably when syncing). Not sure what that metric means, but it's more than known-energy-hungry apps like Chrome and Slack.

CPU, likewise, sits at 4% when it's just idle.

Wondering if it isn't polling too frequently or looping through to keep the countdown of minutes-until-next-meeting up to date so it never truly idles. Can only assume there's a less expensive way of doing that.

### Reproduction steps

Open Activity Monitor

Look at Energy and CPU for MeetingBar.

You will see ~3 - 6% CPU and 80+ "energy impact" when idle

### Expected behavior

Minimal or no energy impact or CPU usage when idle

### Screenshots/screen recordings

Here's MeetingBar at rest:

![image](https://github.com/leits/MeetingBar/assets/828123/09470011-1aff-43c2-9d12-5991eabb2633)

![image](https://github.com/leits/MeetingBar/assets/828123/ca2e10e5-2a70-4969-9cd0-0debe72e92b3)

**Comment by leits** [comment]
Thanks for the report!

Included a few optimizations in the 4.5 version. Please, check it out!

**Comment by leits** [comment]
I am closing this topic due to inactivity.
Feel free to reopen the issue if the problem still exists.
