### ISSUE TITLE
Feature: Open links in specific browser profile

### ISSUE THREAD

**Issue by jamtur01** [leits/MeetingBar#626]
### Issue that this suggestion fixes

I use multiple browser profiles for work, personal, etc. (Google Chrome, but the same applies to Edge, Brave, Firefox, etc.). If I click on a meeting link, it opens that link in the default browser profile, and I cannot choose a specific profile to use.

the 

### Solution description

I want to be able to open meeting links from specific calendars in specific browser profiles.

### Alternatives considered

Unclear?

**Comment by MohamadKh75** [comment]
Hey

I guess we need something like `Custom URL` for joining meetings too (ref https://github.com/leits/MeetingBar/issues/520)

**Comment by leits** [comment]
Hi!
Thanks for the request.
Google Meet links have account recognition based on calendar email. Same with custom links to create appointments. It works via `authuser` URL parameter. 

Instead, the configuration of the profile does not take place through the URL, but through the program launch parameters. Also, a profile is a static parameter. I suggest giving the option to configure the profile as a browser configuration. Accordingly, it will be possible to add another Chrome, which will be launched in a certain profile.

What do you think?

**Comment by jamtur01** [comment]
Sounds good to me.

**Comment by leits** [comment]
I dug deeper and there is actually no way for sandboxed to pass arguments when launching other apps:
> If the calling process is sandboxed, the system ignores the value of this property.

Sorry, there is no possibility to choose a profile on MeetingBar side
You can try apps like [Choose](https://choosy.app/) or [OpenIn](https://loshadki.app/openin/#can-i-configure-profiles-for-chromium-based-browsers). They have this functionality available as they are not in the sandbox. But be careful, it carries security risks.

**Comment by jaklan** [comment]
It should be possible when [this](https://github.com/leits/MeetingBar/issues/816) issue is finalised, right?

As for now, I handle that with BetterTouchTool:

<img width="366" alt="Image" src="https://github.com/user-attachments/assets/014ac244-1bfe-4619-90e1-f26354d8abbe" />

<br>

<img width="416" alt="Image" src="https://github.com/user-attachments/assets/32cf3cf7-bc0a-4477-b214-997b5b731204" />
