### ISSUE TITLE
Bug: Meeting bar opens meetings multiple times

### ISSUE THREAD

**Issue by sumpg41** [leits/MeetingBar#628]
### macOS version

13.2.1 (22D68)

### MeetingBar version

4.4.0

### Installation source

AppStore

### Calendars provider

Google Calendar

### Bug description

I have my MeetingBar set up so that it automatically opens up a meeting for me 1 minute before the meeting starts, and it does this every time flawlessly. The bug, is that 5-10 minutes later it opens up the meeting again a second time, and occasionally a third time. 

I am using the Brave browser and Google Meet

### Expected behavior

Expected behavior would be that MeetingBar only opens the meeting one time

**Comment by leits** [comment]
Thanks for the report!
Included in the next release scope
