### ISSUE TITLE
Add 'Launch on Login' feature

### ISSUE THREAD

**Issue by jogendra** [leits/MeetingBar#63]
**Is your feature request related to a problem? Please describe.**
It is frustrating to run MeetingBar every time I start my machine to show up in Menu.

**Describe the solution you'd like**
Add an option to Launch on Login in preferences which can be enabled or disabled according to user convinience.

If you think this feature worth add, I can open a pull request for the same.

**Comment by leits** [comment]
Thanks for request @jogendra!

This duplicates #27 , folow it instead

**Comment by jogendra** [comment]
Thanks, @leits for letting me know. I went through open issues but somehow missed the already opened issue. Will follow up from #27
