### ISSUE TITLE
Feature: Ignore "Out of office" by default

### ISSUE THREAD

**Issue by johnbillion** [leits/MeetingBar#630]
### Issue that this suggestion fixes

Google Calendar supports an "Out of office" event type. These show up as meetings in MeetingBar but it would be great if they didn't.

Example:

<img width="395" alt="" src="https://github.com/leits/MeetingBar/assets/208434/08583ff7-b2f8-4c4d-a57e-b45d7efec01f">

(Ignore the 01:00 time, this is a bug in Google Calendar when you move between time zones)

### Solution description

"Out of office" events should be ignored by default, possibly with an option to show them if other users find them useful.

### Alternatives considered

None

### Additional context

I appreciate the time you put into MeetingBar!

**Comment by leits** [comment]
Thanks for the request @johnbillion!

You can use `Custom regex to filter out meetings` setting from the Advanced Preferences for this case.
I don't think we are going to add filtering OOO events as option to already extensive settings.
 
<img width="634" alt="image" src="https://github.com/leits/MeetingBar/assets/12017826/b5e121dc-54bf-42ea-98bf-b8f4ed175a08">
