### ISSUE TITLE
Feature: Pumble integration

### ISSUE THREAD

**Issue by y0d4a** [leits/MeetingBar#639]
### Issue that this suggestion fixes

issue is that i do not have support for Pumble

### Solution description

create integration with pumble.com ?

### Alternatives considered

some kind of workaround for the meets?

**Comment by leits** [comment]
Thanks for the request, @y0d4a!

Can you help with an example link?

**Comment by y0d4a** [comment]
sorry for late response , here it is: https://meet.pumble.com/vly-hggs-xsn

**Comment by leits** [comment]
Sorry for the delay 😅 
Added to the next release scope
https://github.com/leits/MeetingBar/commit/fdca4726ea9c4d122da89559dbe9ef8063087670
