### ISSUE TITLE
Bug: Automatically join Teams meeting doesn't work

### ISSUE THREAD

**Issue by moegelin** [leits/MeetingBar#645]
### macOS version

13.5

### MeetingBar version

4.6.0

### Installation source

AppStore

### Calendars provider

macOS Calendar app

### Bug description

I got a new mac and installed MeetingBar and wanted to join automatically my teams meetings.

I activated the checkbox in the settings and chose $Teams$ in the services tab.

Sadly, nothing happens when the meeting starts.

I don't know if this is a bug or if I need to give the application some more access rights?

### Reproduction steps

1. Create a teams meeting in the calendar
2. Go to MeetingBar settings and activate the setting to automatically join the meeting when the event starts
3. Wait for the meeting start
4. --- nothing happens ---

### Expected behavior

I expect the Teams app to open the meeting

**Comment by leits** [comment]
Hi @moegelin!

Sorry for the delay. Do you expect the same issue with the latest version?
Both Teams links recognition and auto-join feature have been improved since then and I hope it also fixed your problem!

**Comment by leits** [comment]
Iʼm closing this topic due to inactivity.
Feel free to reopen the issue if the problem still exists!
