### ISSUE TITLE
Unexpected event name clipping with "..."

### ISSUE THREAD

**Issue by insipidlight** [leits/MeetingBar#65]
This isn't a big issue, I think it's just a matter of a string index being one off. When the event name is the same length as the max displayed, the ellipses appear one character earlier than expected–it already shows the whole name. The gif should explain it better.

I do also wish there were an option to remove the "in" & "...", or have a custom separator (adding on to #42)

![output](https://user-images.githubusercontent.com/34975382/92350037-c85c8c80-f0a5-11ea-9b5d-2b64414d817e.gif)

macOS 10.15.6

**Comment by leits** [comment]
Thanks, @insipidlight!
This will be fixed in the next release
