### ISSUE TITLE
Feature: Join Current meeting keyboard shortcut

### ISSUE THREAD

**Issue by br0p0p** [leits/MeetingBar#651]
### Issue that this suggestion fixes

First of all, thanks for your work on this app. I use it every day and it's made managing meetings so much easier.

There are times I am a minute or so late to a meeting and am unable to join using this app because the "Join next meeting" shortcut is already bound to the upcoming meeting.

### Solution description

I would love a configurable keyboard shortcut to join the current meeting.

### Alternatives considered

none

### Additional context

Additionally, it would also be very convenient to have a "Join meeting" button in the specific meeting menu. I can create a separate issue for this if needed.

<img width="260" alt="Screenshot 2023-08-24 at 1 49 11 PM" src="https://github.com/leits/MeetingBar/assets/657922/a61ccaec-d384-4d85-b4e9-ed472309b979">

**Comment by leits** [comment]
Hi @br0p0p,
Thanks for the request

The app switches to the next meeting 12 minutes before it. You can easily join any meeting from the list by clicking on it!

Would this be a sufficient solution for your case? 
I wouldn't want to add another shortcut for such a narrow case.

**Comment by br0p0p** [comment]
oh wow I had no idea I could just click on the meeting to join it. that will work just fine. thanks!

**Comment by leits** [comment]
Great! Have a nice day!
