### ISSUE TITLE
Bug: zoom.com meeting links not detected

### ISSUE THREAD

**Issue by andrew-craig** [leits/MeetingBar#652]
App Version: 4.6.0
Calendars provider: MacOS Calendar

**Issue**
MeetingBar does not detect zoom meeting links in the calendar event when the link uses the zoom.com domain. 

**To Reproduce**
Steps to reproduce:
- create a meeting with a zoom link using the zoom.com domain (e.g. https://testcompany.zoom.com/j/92313847288?pwd=cY792Kdy4js92JA90kasYhTsL26Jhjwx8sg)
- Select the event from the list of meetings in MeetingBar
- Get an error saying Ouch! Can't join the {event_name} Link not found, or your meeting service is not yet supported

Expected behavior:
- Zoom link opens in the browser

**Potential Cause**
The `zoom` and `zoom_native` LinksRegex do not include the zoom.com domain. Updating the regex to 
`https?:\/\/(?:[a-zA-Z0-9-.]+)?zoom.(?:us|com|com.cn)\/(?:my|[a-z]|webinar)\/[-a-zA-Z0-9()@:%_\+.~#?&=\/]*` and `zoommtg://([a-z0-9-.]+)?zoom\.(us|com|com\.cn)/join[-a-zA-Z0-9()@:%_\+.~#?&=\/]*` will correctly identify the meeting link in regex101.com (I have not been able to test this locally in the app).

**Comment by leits** [comment]
Thanks for the report!
Fixed in the new release. Please check it out!
