### ISSUE TITLE
Bug: Slack Huddle URLs for channels using Slack Connect do not open directly in Slack App

### ISSUE THREAD

**Issue by tsub** [leits/MeetingBar#653]
### macOS version

13.5

### MeetingBar version

4.6.0

### Installation source

Homebrew

### Calendars provider

Google Calendar

### Bug description

refs: https://github.com/leits/MeetingBar/issues/609

We use a feature called Slack Connect to share a channel with another workspace.
If the owner of that channel is another workspace, the Slack Huddle URL will look something like this

```
https://app.slack.com/huddle/<Other Workspace ID>/<Channel ID>
```

This is converted internally in Meetingbar to the following URI.

```
slack://join-huddle?team=<Other Workspace ID>&id=<Channel ID>
```

The channel ID is the same, but the workspace ID is different, so when you open the Huddle URL directly in the Slack App, you must belong to that workspace to open Huddle.

### Reproduction steps

1. have a common channel from another workspace via Slack Connect (I do not participate in that workspace)
2. copy the channel's Huddle URL
3. paste the Huddle URL into an appointment on your calendar
4. set up MeetingBar to open in the Slack App
5. Open the link from MeetingBar
6. The Slack App on your desktop will be focused, but the Huddle popup will not appear.

### Expected behavior

A browser (Slack's web application) will automatically interpret a different workspace ID.

The Slack desktop app does not do this, so it would be best to have the ability to replace the workspace ID with an arbitrary ID when opening the URI from the MeetingBar.

If you can replace the workspace ID with any workspace ID included in the URI, you can replace it with the workspace ID you are participating in and the desktop app will open Slack Huddle correctly.

**Comment by leits** [comment]
Thanks for the request, @tsub!

Looks like a bug in the Slack app.
It's a very narrow case and the extra step will slow down joining a huddle in the common case. 
So I'm sorry, but I won't be making those changes. 

Please contact Slack support so they can fix this bug in their desktop app.
