### ISSUE TITLE
Bug: Notifications don't work on MacOS Sonoma

### ISSUE THREAD

**Issue by saeedesmaili** [leits/MeetingBar#660]
### macOS version

14.0

### MeetingBar version

4.6

### Installation source

manually

### Calendars provider

macOS Calendar app

### Bug description

I have set up my Meetingbar notifications to appear as banners (since they go away without requiring any dismiss action from me) and it was working fine until I upgraded my MacOS to Sonoma this morning.
I don't get any banner notifications when a meeting starts (didn't get any notification for an existing event, then I tested again with another event and the app didn't display any banners again).

<img width="698" alt="image" src="https://github.com/leits/MeetingBar/assets/13351748/49f9ec5d-3815-4926-9c41-43e30ea57239">
<img width="496" alt="image" src="https://github.com/leits/MeetingBar/assets/13351748/ecb4ab3f-0a35-4b4e-bc9f-57cf63309021">

**Comment by leits** [comment]
Hi @saeedesmaili,
Sorry for the delay! Do you still have this bug on the latest 4.7.1 version?

**Comment by leits** [comment]
I am closing this topic due to inactivity.
Feel free to reopen the issue if the problem still exists!

**Comment by jakemauer** [comment]
Chiming in to say I have the exact same issue where I see the "Your macOS notification settings for MeetingBar are not set to alert. Do so if you want persistent notifications." 

These are my current notification settings:
<img width="498" alt="image" src="https://github.com/leits/MeetingBar/assets/361568/2ca8c5c0-4c63-4e91-aaa0-da4f4cab0a83">

My system:
MBP M3 Pro
MacOS Sonoma 14.4.1 (This is a corporate managed machine so this is the latest approved version I can run.)
MeetingBar 4.10.0 (Tried both App Store and GitHub release versions.)

**Comment by leits** [comment]
Hi @jakemauer,
Don't worry, it's only a warning about notification persistence.
Banner notifications will go away automatically so you see that warning in Preferences. No actions needed!

**Comment by jakemauer** [comment]
oh great! thanks for responding so quick.
