### ISSUE TITLE
Feature: Skip alerts for GCal's "Focus time"

### ISSUE THREAD

**Issue by OldhamMade** [leits/MeetingBar#663]
### Issue that this suggestion fixes

Many users block out chunks of their google calendar with "Focus time" events. Generally we don't need to be notified of such events. 

For example, I block out my first hour of every day as focus time to work on administrative tasks. I don't need to be notified of this, it is simply to ensure nobody books in a meeting during that time.

### Solution description

Provide a toggle in settings to "Account for Focus Time", which would check the event's notification settings and only raise a notification if any notification is set.

```gherkin
Given a meeting's title begins with "focus time" (case insensitive)
And the "Account for Focus Time" setting is enabled
When the time of the meeting arrives
And the meeting does NOT have a notification set
Then an alert should NOT be raised

Given a meeting's title begins with "focus time" (case insensitive)
And the "Account for Focus Time" setting is enabled
When the time of the meeting arrives
And the meeting DOES have a notification set
Then an alert SHOULD be raised
```

### Alternatives considered

Another option might be to provide a textarea in Advanced settings where users can define regular expressions to use to filter and suppress alerts. Eg:

```
Suppress alerts for events that match the following expressions:
^(Focus time).*
```

**Comment by leits** [comment]
Hi @OldhamMade,
Thanks for the request!

You can achieve this with the following settings:
<img width="742" alt="image" src="https://github.com/leits/MeetingBar/assets/12017826/aedbb53a-5519-4c34-ad83-2ef2d6c80646">

This will show all events without a link as inactive.
