### ISSUE TITLE
Show next meeting after some time if already in a meeting

### ISSUE THREAD

**Issue by raivivek** [leits/MeetingBar#67]
**Is your feature request related to a problem? Please describe.**
If I have two back to back meetings, then it'd be nice to have the next meeting start to show up in the menu bar when it's near the start time. Currently, it continues to show "XXX (9m left)" for the current meeting I am in right now.

**Describe the solution you'd like**
Given a preference of say 15 mins, show next meeting details when 15 mins are left until start.

**Comment by leits** [comment]
Hi, @raivivek. Can you dublecheck? This feature works from the beginning, showing next meeting 10 minute before.)
https://github.com/leits/MeetingBar/blob/master/MeetingBar/EventStore.swift#L79

**Comment by raivivek** [comment]
Thanks, I see the 10 minute countdown now. Dunno why I didn't see it earlier.
