### ISSUE TITLE
Feature: full screen notification

### ISSUE THREAD

**Issue by alexec** [leits/MeetingBar#674]
### Issue that this suggestion fixes

I using [InYourFace](https://www.inyourface.app/) because the notification for meeting bar are not enough ... in my face.

But that doesn't do quite what I want either.

### Solution description

I want a full screen pop-up, but only with the following information:

- The meeting name.
- A list of everyone who accepted the meeting invites and their real names (not emails).
- A second list of anyone who has not accepted (both declined and no-reply, because it seems that no-reply===declined+impolite).
- A meeting agenda.
- A link to the vide call.

Looking at this information allows me to take a moment to mentally prepare for the meeting

### Alternatives considered

None

**Comment by leits** [comment]
Thanks for the request!
Yesterday, I released a new version with a minimal version of this feature. There is only a meeting title, service icon, time range, and button to join.

You can turn it on in the Advanced settings as an auto-join to the meeting. Please check it out!

**Comment by ebosveld** [comment]
I'm not too happy about this change either, @leits. This now means I need to do a 2nd click. Could you put this behind a different configuration?

**Comment by mig8447** [comment]
@leits I'm in love with this new feature, however, I saw that there's no keyboard focus for the buttons once the notification comes up. It would be great if I could either tab and hit enter or escape or hit enter or escape directly for joining/cancelling

**Comment by shimonacarvalho** [comment]
Thank you! This is great, been waiting for this.

**Comment by secjur** [comment]
> Hi @lecodeski, Thanks for the feedback! Yeah, I got multiple responses like yours, and I'm going to bring back the original advanced auto-join feature as it was before, and add the new settings for the full-screen notification!

Is the old behavior already available somehow? With the full-screen notification the app is not usable for me unfortunately. thanks!

**Comment by lecodeski** [comment]
Good question!
I upgraded yesterday to 4.7.1 and got the "old" new behaviour back why I downgraded. Ist this fullscreen notification already configurable? @leits

**Comment by shimonacarvalho** [comment]
Same, where did it go! Going to downgrade.

**Comment by lecodeski** [comment]
There it is! 🎉  Shipped together with the new version `4.8.0`. Thank you very much! ❤️

**Comment by leits** [comment]
Yes, "Show a fullscreen notification" is now available for all as a separate feature in 4.8.0 🚀
