### ISSUE TITLE
Allow more specific increments for pre-notification times 

### ISSUE THREAD

**Issue by sn0wyfall** [leits/MeetingBar#68]
**Is your feature request related to a problem? Please describe.**
Hi! I would love to be able to choose to see the notification either 2 or 3 minutes before the meeting starts. IMO 1 minute is a bit too late and 5 minutes is a bit too early. I feel like being able to choose a range from 1-5 minutes would be perfect for most people. 

**Describe alternatives you've considered**
I have Meeter installed right now, but it doesn't offer in-app direct link opening unless you purchase premium, so I was hoping I could use Meeting Bar instead :)

**Comment by sn0wyfall** [comment]
@leits would this be possible 😇 is it as easy as changing a string in the code? Sorry I'm inexperienced with coding so I don't know how much effort it would entail, I figured it would be easy but I may be wrong!

**Comment by leits** [comment]
@sn0wyfall added in https://github.com/leits/MeetingBar/releases/tag/v2.0
Check it out!

**Comment by sn0wyfall** [comment]
> @sn0wyfall added in https://github.com/leits/MeetingBar/releases/tag/v2.0
> Check it out!

Awesome! Thanks a ton mate.
