### ISSUE TITLE
Bug: Can't connect to Google Calendar API in v4.7.0

### ISSUE THREAD

**Issue by adirizka7** [leits/MeetingBar#683]
### macOS version

14.3 (23D56)

### MeetingBar version

4.7.0

### Installation source

AppStore

### Calendars provider

Google Calendar

### Bug description

I attempted to perform a clean installation of Meetingbar on my new Mac, but encountered difficulties connecting to my Google account. Despite attempting reinstalls via both the AppStore and Homebrew, I was unable to resolve the issue.

Upon investigating my old Mac, I observed that it was running version 4.6.0 of Meetingbar. Subsequently, I manually installed version 4.6.0 on my new Mac, and this allowed me to successfully connect my Google account to Meetingbar.

### Reproduction steps

1. Install the Meetingbar v4.7.0
2. Connect to a google account
3. Once all needed access are granted and google account is logged in on browser, nothing would happen.

### Expected behavior

Calendar options of the logged-in calendar should show up in the `Calendars` tab of Meetingbar

**Comment by leits** [comment]
Thanks for the report!

Fixed the bug with incorrect credentials!
https://github.com/leits/MeetingBar/releases/tag/v4.7.1

Already available via homebrew. The AppStore version is on Review and should be available soon as well!

**Comment by adirizka7** [comment]
Works great @leits! Thanks for addressing it quickly 🚤
