### ISSUE TITLE
Bug: Notifications sent even when event has no meeting

### ISSUE THREAD

**Issue by jvacek** [leits/MeetingBar#688]
### macOS version

14.2.1

### MeetingBar version

4.6.0

### Installation source

Homebrew

### Calendars provider

macOS Calendar app

### Bug description

Notifications are sending even if no meeting in event

### Reproduction steps

Have an event with no meeting in the calendar
Enable notifications for "Events with meetings"

### Expected behavior

No notification when there's no meeting in event

### Screenshots/screen recordings

<img width="661" alt="image" src="https://github.com/leits/MeetingBar/assets/1302278/53f4c4ec-71e9-40c3-a4ce-dcadda9274c4">

### Additional context

This might just be a language issue, and the setting was supposed to just send notifications on events. If that's the case, it would be nice to have an additional toggle to _only_ send the notification for events with meetings.

**Comment by leits** [comment]
Hi @jvacek,
Thanks for the report!
Yeah, that's a setting description issue. 
The app will send notifications for all events configured as active in the appearance settings. The same events will be shown in the status bar.

I'll update the setting wording in the next release!
