### ISSUE TITLE
Bug: full-screen notification appears on app-start

### ISSUE THREAD

**Issue by patrickrushton** [leits/MeetingBar#695]
### macOS version

14.3.1 (23D60)

### MeetingBar version

4,71

### Installation source

AppStore

### Calendars provider

macOS Calendar app

### Bug description
When the app launches, the full screen notification is displayed. This started appearing ever since I added a regex to filter out meetings on the advanced settings.

![image](https://github.com/leits/MeetingBar/assets/6472595/660369ac-f918-40d5-a1f5-82216e261e06)

### Reproduction steps

Quit and relaunch MeetingBar

### Screenshots/screen recordings

See above

**Comment by patrickrushton** [comment]
Actually I don't think this is even a notification because it still appears every time I start the app even with the "Send notification to join" checkbox off.

**Comment by patrickrushton** [comment]
Maybe related to this https://github.com/leits/MeetingBar/issues/674 ?
Although I don't have auto-join meeting enabled...

**Comment by feferka** [comment]
I saw this full screen notification as well, the case was there were ongoing meeting in calendar and I started meeting bar.
Just stupid question, can you see this full screen notification also as standard notification of new meeting? Normally I can see just a MacOS alert but this screen will be better to me. Maybe it could it be configurable ?

Note: I run macbook pro M2, Sonoma 14.4. with external display (mac macbook build-in display is closed)

**Comment by leits** [comment]
Thanks for the reports!
I'm going to fix this in the next 4.8.0 release!

**Comment by leits** [comment]
Fixed!
