### ISSUE TITLE
O365 (Outlook and Teams) calendar integration

### ISSUE THREAD

**Issue by paulshryock** [leits/MeetingBar#7]
**Is your feature request related to a problem? Please describe.**
I don't use MacOS calendar, but I use O365 calendar in Outlook and Teams.

**Describe the solution you'd like**
I would find this app useful if it integrated with the O365 calendar in Outlook and Teams. I'd love to be able to view upcoming meetings and easily create new meetings.

**Comment by ZoeLeah** [comment]
+1

**Comment by leits** [comment]
@paulshryock , @ZoeLeah , this app is based on macOS calendar API.

But it's not a problem at all!

You can connect your O365 calendar to mac in 10 simple steps from [this](https://support.cc.gatech.edu/support-tools/howto/add-office-365-account-mac-calendar) or any other guide.

**Comment by leits** [comment]
upd: official apple guide:
 https://support.apple.com/guide/calendar/add-or-delete-calendar-accounts-icl4308d6701/mac
