### ISSUE TITLE
Zoom URL with a dash in orgnization name not recognized

### ISSUE THREAD

**Issue by insipidlight** [leits/MeetingBar#70]
I've finally had some time to fork and look through things. I noticed that university Zoom link with a dash would not open. Looks like it doesn't match the regex, which explains why I've been having some issues.

https://*-edu.zoom.us/j/

Current regex is
`https://([a-z0-9.]+)?zoom.(us|com.cn)/j/[^\s]*`

From the [Guidelines for Vanity URL Requests](https://support.zoom.us/hc/en-us/articles/215062646-Guidelines-for-Vanity-URL-Requests), `****-org-au.zoom.us` would also be a valid link, with two hyphens. "Vanity URLs must only contain letters, numbers and dashes (-)."

1.4
macOS 10.15.6

**Comment by leits** [comment]
Thanks, @insipidlight. I will update the regex!

**Comment by leits** [comment]
Fixed in 1.5!
