### ISSUE TITLE
Bug: Meeting bar running but just the blank icon and not auto updating infomratin.

### ISSUE THREAD

**Issue by uratrtl** [leits/MeetingBar#708]
### macOS version

14.2.1

### MeetingBar version

4.7.1

### Installation source

AppStore

### Calendars provider

Google Calendar

### Bug description

Every couple of days I look up and see my meetings information is empty, the app is running and its just showing the black default icon. If I navigate to calnedars it either crashes or refreshes, this is with google calendar.

**Comment by jin-ds** [comment]
Having the same issue here, where I need to go to the Calendars tab in order for the meetings to be loaded that day. It seems mostly consistent, and some days it does work automatically.

**Comment by hamxabaig** [comment]
Same for me, also there are huge number of ports opened by MeetingBar app

**Comment by hamxabaig** [comment]
Same for me, also there are huge number of ports opened by MeetingBar app

**Comment by eshao** [comment]
I'm also having this issue. Every couple days, it'll stop working and I'll need to go to Preferences → Calendars tab for meetings to get loaded.

**Comment by xiaoyingshi** [comment]
Same here, MAC OS 14.0, dont know why.

**Comment by brumhard** [comment]
Same for me, It works for me after manual Quick Actions > Refresh Sources

**Comment by leits** [comment]
Hi folks,
Added a fix for this in 4.10.0. Thanks for the reports!
