### ISSUE TITLE
List supported services on the front page

### ISSUE THREAD

**Issue by fuzzy76** [leits/MeetingBar#71]
I actually dismissed this program early on, because the web page said it was for Google Meet and Zoom only. Both the web page and the README gives the impression that these are the two services supported.

I returned after a while, and searched your issues for news on Teams support, and suddelnly noticed it was already supported.

**Comment by leits** [comment]
Thanks. @fuzzy76!
Support for this service was added just a few days ago. I updated the readme and will update the site soon!
