### ISSUE TITLE
Feature: Display on all monitors

### ISSUE THREAD

**Issue by jshepherd377** [leits/MeetingBar#710]
### Issue that this suggestion fixes

Connecting laptop to an external monitor as primary, MeetingBar appears on this monitor. When I unplug the laptop to walk away, the MeetingBar is lost and does not appear on the laptop monitor. 

### Solution description

Having it appear on all monitor's top menus would be amazing and solve the above problem.

### Alternatives considered

When I unplug the external laptop monitor, I can quit meetingbar and re-start it. That makes it appear on my laptop. Not a good hacky fix.

**Comment by LouisJS** [comment]
This is so annoying. Please it needs a fix

**Comment by leits** [comment]
Hi @jshepherd377 @LouisJS,
The status bar is fully managed by macOS. So, if you don't have enough space in your status bar, macOS will hide all the items that don't fit. When you restart the app, macOS can remove some other items to fit the new item. It's just a macOS behavior and can't be changed from the app side.

I recommend using apps like [Dozer](https://github.com/Mortennn/Dozer), [Bartender](https://www.macbartender.com/), or similar to clean up your status bar.
