### ISSUE TITLE
Bug/Feature: Auto refresh sources every X minuetes - they are not refreshed and often missing

### ISSUE THREAD

**Issue by Tom-Potanski** [leits/MeetingBar#717]
### macOS version

14.0 (23A344)

### MeetingBar version

4.8

### Installation source

AppStore

### Calendars provider

macOS Calendar app

### Bug description

Right now, every day, MeetingBar in the morning doesn't show any meetings, and I need to manually click "refresh soruces" which doesn't make sense. Would be great to make it automatic. 

Would be great to make it possible to set that the sources refresh automatically after a certain interval, for instance every 5 min.

### Reproduction steps

It just happens for me everyday

### Expected behavior

Would be nice for the meatings to simply appear, without a manual action.

**Comment by leits** [comment]
Hi @Tom-Potanski,
MeetingBar fetches the data from macOS Calendar app every minute and also is subscribed to updates.
"Refresh source" has an additional ask to macOS Calendar to refresh remote sources.
By default, all macOS Calendars refresh their sources every 15 minutes. It's recommended by Apple to not overuse the programmatical ask to refresh source but to reduce [refresh calendars interval in the Calendar app](https://support.apple.com/en-gb/guide/calendar/icl1024/mac).
