### ISSUE TITLE
Bug: Full screen notification does not work

### ISSUE THREAD

**Issue by adamsaghy** [leits/MeetingBar#719]
### macOS version

14.5 Beta (23F5074a)

### MeetingBar version

4.8.0

### Installation source

Homebrew

### Calendars provider

macOS Calendar app

### Bug description

I tick to show full screen notification about the event, but nothing happens

**Comment by adamsaghy** [comment]
I was wrong. it works now :D

**Comment by kkerr123** [comment]
Full screen notifications are still not working for me.

**Comment by adamsaghy** [comment]
After i restarted the machine and the event had a link to the meeting it started to work.

**Comment by habioye** [comment]
Does that mean that you can only use fullscreen if there is a valid meeting / eventlink
