### ISSUE TITLE
Toggle Do Not Disturb mode

### ISSUE THREAD

**Issue by fuzzy76** [leits/MeetingBar#72]
I would love for MeetingBar to toggle DnD mode on (and off again) for meetings I have accepted.

To avoid clutter, perhaps there should be a separate calendar selection to choose which calendars should affect DnD mode.

Bonus points for adding presence control for external services (set me as busy in Teams/Skype etc when I'm in a Zoom meeting).

**Comment by Itaybre** [comment]
It seems there is no public API for this, at least not for sandboxed apps

But can be done with [sindresorhus/do-not-disturb](https://github.com/sindresorhus/do-not-disturb) for unsandboxed

**Comment by jgoldhammer** [comment]
If it is not possible for sandboxed apps, how to release a version as unsandboxed apps with do-not-disturb control for homebrew/self installation and a sandboxed app without do-not-disturb control for the appstore?

**Comment by jgoldhammer** [comment]
@Itaybre  - any idea how to introduce this, so that the app still can be published to the appstore?

**Comment by Itaybre** [comment]
@jgoldhammer I guess we could ask for the user to set a Keyboard Command to toggle DND and then use a script to enable it, like [this](https://apple.stackexchange.com/a/145491)
I can try this approach later tonight

**Comment by jgoldhammer** [comment]
Thanks! Maybe we can integrate it into the apple script which gets executed when we join a meeting...

On the other side- activating and deactivating DND is one click away (Hold OPTION and click on the notification center in the menubar)...

**Comment by Itaybre** [comment]
@jgoldhammer Tried it but it won't work this way, you cannot trigger System Events from a sandbox app.

But, using a user supplied script may work, but will require an extra step for the user, to download and save an AppleScript

**Comment by Itaybre** [comment]
Also tried Accesibility API, but it won't work inside a sandbox

**Comment by jgoldhammer** [comment]
@leits - would this be a good way to go with a user supplied script?  Should we really change settings automatically when a meeting begins or ends? If so, should we introduce notifications so that we show what will happen? Or should we offer options in the menu of the app to activate or deactivate dnd?

**Comment by leits** [comment]
I think this feature is difficult to implement and possible bugs in it will be a terrible experience.

The user already has the ability to run scripts at the beginning of the meeting. Thanks to this, the advanced user can implement this functionality independently, taking all the risks.


So, in summary, there is no simple or even correct method of implementation, and the user has a workaround to have this functionality.
So I close this issue.
