### ISSUE TITLE
Feature: CMD-Click the current meeting name to join

### ISSUE THREAD

**Issue by spencerlavallesonos** [leits/MeetingBar#720]
### Issue that this suggestion fixes

When a meeting has started or is in progress I need to click MeetingBar, then click on "Join current event meeting", as a lazy  engineer this is too many steps. 

### Solution description

CMD-click on the nav bar to join current meeting 
![2024-05-02 10 04 44](https://github.com/leits/MeetingBar/assets/129799088/29d92824-e5e9-4eb8-bfdb-37a8dcb630f2)

### Alternatives considered

if CMD isn't a key that can be used, maybe an option-click, or something similar.

**Comment by jgoldhammer** [comment]
Currently this is possible with a double click via two fingers. If that works for you, please close the ticket. Thanks
