### ISSUE TITLE
Feature: Detect link without https://

### ISSUE THREAD

**Issue by emilevictorportenart** [leits/MeetingBar#722]
### Issue that this suggestion fixes

When a google meet link doesn't have the `https://`, it's not detected as a link and it's not possible to open the event in the browser. 

![CleanShot 2024-05-08 at 10 51 28](https://github.com/leits/MeetingBar/assets/921074/2e2b9db3-caf4-4633-9fd8-b5d8f2611612)

### Solution description

Detect Google meet links automatically, even when https:// is not present. 

### Alternatives considered

Add https:// to all links

**Comment by leits** [comment]
Hi @emilevictorportenart, 
You can use custom regexes in Advanced Preferences for any of your custom search preferences.
Detecting links without `https://` is a dangerous behavior and can be unpredictable for users. The meeting services are quite in line with this so if a meeting is created from any of the integrations it always has the `https://` prefix.

**Comment by emilevictorportenart** [comment]
Thanks for letting me know!
