### ISSUE TITLE
Bug: Meetingbar no longer recognizes rescheduled meetings

### ISSUE THREAD

**Issue by sumpg41** [leits/MeetingBar#723]
### macOS version

14.4.1 (23E224)

### MeetingBar version

4.8.0

### Installation source

AppStore

### Calendars provider

Google Calendar

### Bug description

Meetingbar no longer recognizes rescheduled meetings, even if they were rescheduled multiple days ago

**Comment by leits** [comment]
Hi @sumpg41,
Please, share more details. I can't reproduce it.
Only rescheduled meetings are not changed in the list of meetings or all list is outdated?
If you just create an appointment will it appear?

**Comment by sumpg41** [comment]
These appear to be fixed now...the issue may have been local to my machine
