### ISSUE TITLE
Zoom link doesn't show up; can't join meeting

### ISSUE THREAD

**Issue by oakif** [leits/MeetingBar#74]
**Describe the bug**
I'm having the following problems: 
* I can't join meetings using Meeting Bar, either using the menu bar item or through Meeting Bar's notifications
* I can't see any Zoom link from Meeting Bar (screenshot below)
* I get a strange "status" (screenshot below)

<img width="398" alt="Untitled1" src="https://user-images.githubusercontent.com/48932412/92961676-a5333380-f43d-11ea-82d0-b8b1ab47fc4f.png">

Note: title, calendar, and location were blanked out

**To Reproduce**
This issue started occurring from the time I installed Meeting Bar. 

**Desktop (please complete the following information):**
 - macOS version: 10.15.6

**Additional context**
I tried reinstalling Meeting Bar but that didn't seem to solve anything.

**Comment by oakif** [comment]
@leits the join next meeting is working now, thanks! I still have the arcane "Participant Status" string, although functionally it doesn't bother me. Thank you for the update.

**Comment by leits** [comment]
Great! 
Can you create an issue for Participant Status bug?
