### ISSUE TITLE
Bug: meeting title missing from the status bar

### ISSUE THREAD

**Issue by salmiakki** [leits/MeetingBar#745]
### macOS version

Sonoma 14.5

### MeetingBar version

4.10.0

### Installation source

AppStore

### Calendars provider

macOS Calendar app

### Bug description

The meeting names are missing in the Status Bar. It says _Meeting in Xm_ (_Meeting now_) instead of _<Actual meeting title> in Xm_ (__<Actual meeting title> now_).

When I click on MeetingBar and the dropdown shows up, the titles are there, as expected.

### Reproduction steps

- Go to _Preferences_ > _Appearance_
- Set _Title_ to _event title_, _shorten to 55 characters_.

### Expected behavior

The status bar should display the actual meeting name.

### Screenshots/screen recordings

![image](https://github.com/leits/MeetingBar/assets/4760420/a376d23f-70eb-48a5-b3d1-8bf3db10fe80)

### Additional context

It used to work as expected.

**Comment by salmiakki** [comment]
> Ensure that the "Show meeting title" option is checked.

I don't see that.

_Title_ is set to _event title_ though.

**Comment by salmiakki** [comment]
That does not help.

**Comment by salmiakki** [comment]
@leits Could I help in any way, perhaps provide some additional info?

**Comment by leits** [comment]
Hi @salmiakki,
Sorry for the delay. Can you check the Quick Action in the main menu?
There is a "Show/Hide meeting title" option
<img width="482" alt="image" src="https://github.com/user-attachments/assets/bd7f363d-00d3-450e-8dad-7cd266cddf20">

**Comment by salmiakki** [comment]
Yes, that was it! I must have butt-disabled it. Embarrassing. Thank you so much 👍

**Comment by salmiakki** [comment]
On a related note, maybe this setting could also be visible in the Preferences Appearance tab.
