### ISSUE TITLE
Settings not persisting; welcome dialog appears on each launch

### ISSUE THREAD

**Issue by advicepyro** [leits/MeetingBar#75]
**Describe the bug**
Since 1.4, on each launch of the app the welcome dialog appears. It also looks like settings don't persist after I quit the app; for example, my preference to show the dot or the event name in the menu bar.

**To Reproduce**
1. Launch the app and go through the welcome process
2. Go to preferences. Under the Appearance tab, change the show option to be a dot
3. Quit MeetingBar and relaunch. The welcome dialog appears again
4. Going back to preferences, the show option reverts to the event title

**Desktop (please complete the following information):**
 - macOS version: 10.15.6

**Comment by leits** [comment]
Fixed in 1.5!

**Comment by advicepyro** [comment]
@leits thanks for fixing the welcome dialog bug!

Did some testing and looks like the event title setting is the only one that does not persist after quitting the app; other settings are fine. I can open a new issue for this if you wish.
