### ISSUE TITLE
Limit calendar event title length via configuration

### ISSUE THREAD

**Issue by shadyabhi** [leits/MeetingBar#81]
**Describe the bug**
MeetingBar disappears if the calendar event title is too long. 

**To Reproduce**
1. Open "MeetingBar"
2. Wait for an event where the title of event is too long to be shown in the bar.
3. Observe the "missing" MeetingBar.

**Expected behavior**
We can wrap the title to only show first "x" characters in case users have a lot of icons in the bar.

**Screenshots**
![image](https://user-images.githubusercontent.com/631797/93921369-50a57900-fcc5-11ea-9ea9-1a7cf17b659c.png)

**Desktop (please complete the following information):**
 - macOS version: [e.g. 10.15.6]

**Comment by Itaybre** [comment]
@shadyabhi You can already do that inside Preferences -> Appearance
![image](https://user-images.githubusercontent.com/860036/93935593-3d150500-fcfb-11ea-8e57-7e8cf1f5dfcd.png)

**Comment by shadyabhi** [comment]
@Itaybre  I feel really stupid for creating this issue. Thanks a lot, I'll go ahead and close this.

**Comment by egorf** [comment]
Hi @Itaybre!

When using a 13-inch laptop you don't really get much space in the top bar. An app like a browser with lots of menus in the top bar will most likely push MeetingBar out of view. To solve this, I need to make the max length really really small. However, I can't read the name of the meeting even when focused on an app that takes way less space in the top bar, like Finder. So I have to choose between:
1. The name being readable with FInder open but not there when Firefox is open
2. Being there all the time, but not readable at all.

Have you considered making these transitions automatic? Fill the available space type? Or maybe show some kind of icon (different for upcoming and ongoing meetings) and remaining time when there's not enough space to render things?
