### ISSUE TITLE
Update FAQ for "warnings from Apple"

### ISSUE THREAD

**Issue by crstauf** [leits/MeetingBar#82]
[The FAQ](https://github.com/leits/MeetingBar/wiki/FAQ) may be slightly outdated ([the "warnings from Apple" section](https://github.com/leits/MeetingBar/wiki/FAQ#i-try-to-install-this-app-but-i-have-warnings-from-apple-and-cant-installopen)) after [version 1.6](https://github.com/leits/MeetingBar/releases/tag/v1.6) was released, which included signature and notarization from Apple.

**Comment by leits** [comment]
Thanks, updated!
