### ISSUE TITLE
Create Meetings in Outlook Web Access

### ISSUE THREAD

**Issue by kidGodzilla** [leits/MeetingBar#86]
Enhancement: It would be neat to set "Create Meetings in" to "Outlook Web Access" (the official name for Outlook for the web).

Most corporate environments create meetings from Outlook or Outlook Web Access (instead of Teams). Many may not use Teams at all.

The URL to create a new meeting in Outlook Web Access is:

`https://outlook.office.com/calendar/deeplink/compose?popoutv2=1`

<img width="1440" alt="Screen Shot 2020-10-03" src="https://user-images.githubusercontent.com/6320214/94966307-9ff27180-052f-11eb-8483-bf799ec73143.png">

**Comment by kidGodzilla** [comment]
Looks like `https://outlook.office365.com/calendar/0/action/compose` might be a better option for Office 365, with `https://outlook.live.com/calendar/0/action/compose` for Outlook (personal).

**Comment by leits** [comment]
Added in https://github.com/leits/MeetingBar/releases/tag/v2.0
@kidGodzilla check it out!
