### ISSUE TITLE
Support for opening zoommtg:// URIs in Zoom?

### ISSUE THREAD

**Issue by jasonhan-vassar** [leits/MeetingBar#93]
Hi, are there plans to be supporting zoommtg:// URIs in addition to zoom.us links? If not, could you please let me know why? Thanks!

**Comment by jgoldhammer** [comment]
Can you elaborate a little bit more? Are these zoommtg:// uris in your calendar events? Currently only https-links of zoom are recognized, but this can be easily enhanced...

**Comment by jgoldhammer** [comment]
@jasonhan-vassar - I will close the ticket for now. You can reopen it with more information. Thanks!

**Comment by jasonhan-vassar** [comment]
Sorry for not getting back sooner — they are in the URL field of my calendar event.

**Comment by jgoldhammer** [comment]
🎉 zoommtg-links are now recognized as valid zoom link and will be opened directly in the zoom app.
For more details, see the attached merge request.
