### ISSUE TITLE
Launch at Login config setting has no effect

### ISSUE THREAD

**Issue by stolowski** [leits/MeetingBar#94]
**App version**

1.6.1 (from App Store)

**Describe the bug**

I've the "Launch at Login" option ticked ON, but I've never seen MeetingBar after re-login/restart. I've to start it manually every time after login.

**To Reproduce**
1. Go to Preferences/General.
2. Enable "Launch at login"
3. Restart the system.
4. Log in; MeetingBar should be automatically started, but it is not.

**Expected behavior**
MeetingBar should automatically get started if "Launch at Login" is ON.

**Desktop (please complete the following information):**
 - macOS version: 10.15.7 (19H2)

**Additional context**

Using MeetingBar from App Store; was using the one from homebrew before (removed it before switching to App Store version).

**Comment by leits** [comment]
The fixed version here and on homebrew available in AppStore, on homebrew and here:
https://github.com/leits/MeetingBar/releases/tag/v1.6.2

**Comment by igorkulman** [comment]
I started having this problem after some Monterey updates. The option is checked but the app does not start after login, is not visible in login items.

**Comment by felixmagnus** [comment]
Same here - Lauch after login is checked but MeetingBar does not start after login.

**App Version**:

![image](https://user-images.githubusercontent.com/49987425/174257088-acd9009b-99ea-41c6-a9d8-d97494ceb433.png)

**OS Version**:

![image](https://user-images.githubusercontent.com/49987425/174257159-824a835e-6912-4d34-8d1e-c661c0364cc1.png)

**Comment by sh-cho** [comment]
Same here (monterey 12.1, Version 4.0.5)

**Comment by hongbeomi** [comment]
Same hear (monterey 12.2, Version 4.0.6)

**Comment by phugodness** [comment]
pump the issue. (monterey 12.6, Version 4.0.6)

**Comment by leits** [comment]
Moved to the new issue #494.
