### ISSUE TITLE
Feature Request: Use a different style to display past meetings

### ISSUE THREAD

**Issue by tmchow** [leits/MeetingBar#96]
**Is your feature request related to a problem? Please describe.**
It can be hard to scan the list of past and upcoming meetings due to the use of the checkmark since the text is all the same style.

**Describe the solution you'd like**
Instead of a checkmark indicating a past meeting, I think it would work better to dim the row like how the "Next Meeting" product works.

**Comment by jgoldhammer** [comment]
Hi Trevin, 

something like this?

![image](https://user-images.githubusercontent.com/3872101/103648168-b52ad200-4f5c-11eb-85ce-bd59c5f5d48b.png)

We have removed the checkmark...

**Comment by tmchow** [comment]
@jgoldhammer yes! that would help immensely by making the list easier to scan for current+future mtgs vs past mtgs.

**Comment by jgoldhammer** [comment]
Thanks for your answer. We will release this as feature for the upcoming 3.0 release. 🎉

**Comment by leits** [comment]
@tmchow,  released! Check it out!
