### ISSUE TITLE
Persistant notifications

### ISSUE THREAD

**Issue by xdjuj** [leits/MeetingBar#97]
Hi! I'm using Meeter since a while, and really appreciate the fact that a free alternative (using by a part of my team) is existing.

I've had a try with MeetingBar and also remove Meeter! Till I notice that there was no persistant notifications and few more clicks to join the "next meeting" (which can be the "ongoing meeting" if you've 1min delay, a quite bit confusing but not a big deal).

In Meeter, the notification stay, till you click on it (and then you're automatically redirected on your call, no need to find the icon, clic on it, then find "join next meeting", which save some clicks, gain of time) or dismiss it. This is very useful! Especially when you've a lot of meetings, where the first one never ends before the second one, and so on, which is, I guess, why we use Meeter or MeetingBar (if you have few meetings, you don't care about those tools).

This only little thing make me, this morning, uninstalling MeetinBar, and re-installing Meeter, because yesterday, I've missed the beginning of a call, because I didn't see the quick notice on time (that can't arrive if the notification stay till you've choose an action, and then, a quick click let you in! Very fast).

By the way, many thanks for the great work (looking like "Up next" from 2018), half my team using it, I hope to be able to say "all my team", including me :p As soon as the product will improve :)

All the best.

**Comment by leits** [comment]
Thanks for the request @xdjuj !

**Comment by leits** [comment]
@Itaybre, do you have any ideas on how to make an alert instead of a banner.
We already request alert style here: https://github.com/leits/MeetingBar/blob/master/MeetingBar/Notifications.swift#L15
And I can't find any other configuration for that.

**Comment by Itaybre** [comment]
@leits I think it is possible to change the default alert style in with the key `NSUserNotificationAlertStyle ` inside Info.plist

**Comment by Itaybre** [comment]
There are some issued in Debug, but should work in release: [see](https://stackoverflow.com/a/55320805/964212)

**Comment by jgoldhammer** [comment]
I have tried with the repo https://github.com/lukakerr/Swift-NSUserNotificationPrivate.
At start of the application, macos asks me if the app can send notifications. After clicking on allow, following entry was created in the notification settings.

![image](https://user-images.githubusercontent.com/3872101/103815483-b692f200-5063-11eb-9894-3c8e29153960.png)

The difference is that the code in the other repo uses the old notification framework and does not request authorisation!!

![image](https://user-images.githubusercontent.com/3872101/103816032-a0d1fc80-5064-11eb-9fb6-9863be3ae6f1.png)

Interesting is following code to allow showing up the notifications even when the app is in focus...
![image](https://user-images.githubusercontent.com/3872101/103815809-34ef9400-5064-11eb-9670-44650b99415b.png)

I think we should add this, too.

**Comment by jgoldhammer** [comment]
I have played a little bit with it. I think, the old, deprecated api was more reliable to set the correct settings for a new app. 
As an app cannot change its own notificationsettings, but reading them, we can display a warning for the user, when the user will enable notifications and the settings are not as expected.

There are two situations which will be detected:
- the user has completely switched off the notifications for meetingbar- the authorisationstatus will be declined than.
- the original setting is banner only- we will recommend to set to alert for the user.

@leits - what do you think?

**Comment by jgoldhammer** [comment]
The notifications are correctly set- a little hint for the user that everything is ok...
![image](https://user-images.githubusercontent.com/3872101/103952598-fb408b00-5140-11eb-9fee-5e1e9ce295de.png)

The user has deactivated the notifications
![image](https://user-images.githubusercontent.com/3872101/103952675-17442c80-5141-11eb-86e2-dcec3b5e6920.png)

The user has not set the alert style
![image](https://user-images.githubusercontent.com/3872101/103952715-275c0c00-5141-11eb-9222-bcbf9d3b823c.png)
