### ISSUE TITLE
Bug: 12hr Time Format not working

### ISSUE THREAD

**Issue by krabf** [leits/MeetingBar#98]
App Version 1.6.2

I'm on macOS 10.15.7 and the 12-hour AM/PM time format is not working. Menu bar only shows the 24 hr.
https://ibb.co/jhm1B4K

**Comment by leits** [comment]
![image](https://user-images.githubusercontent.com/12017826/100073756-93f7a180-2e46-11eb-957f-2e70fec121d0.png)

**Comment by leits** [comment]
Hi, @krabf.
The status bar displays the time period before the meeting.
Time format applies only for a time moment, not time period.
