### ISSUE TITLE
Wrong margins in appearance tab

### ISSUE THREAD

**Issue by denizongar** [leits/MeetingBar#99]
**App version**
2.0.1

**Describe the bug**
Top and bottom margins for the appearance tab in the preferences window are off, resulting in top of the tabs being cut.

**To Reproduce**
1. Open preferences window.
2. Go to the appearance tab.

**Expected behavior**
Margins would be the same as the other tabs.

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/8755305/100388181-2c01b080-302a-11eb-9302-0f7fce06fab7.png)

**Desktop (please complete the following information):**
 - macOS version: 11.0.1

**Comment by jgoldhammer** [comment]
@denizongar - can you check that on version 2.0.5 and report back if this version fixes it? If not, we will check that for release 3.0

**Comment by denizongar** [comment]
@jgoldhammer Currently on version 2.0.5 and problem still persists.

**Comment by leits** [comment]
@jgoldhammer, I guess, and saw confirmation of this on Twitter, that SwiftUI has bugs with rendering in Catalina.
It's possible that there will be no such problems after the SwiftUI update.

**Comment by jgoldhammer** [comment]
But is not catalina, it is Big Sur. In the original issue the macos version is 11.x

**Comment by leits** [comment]
Sorry, I mean Big Sure, not Catalina.)

**Comment by leits** [comment]
@denizongar, please, check it for the new 3.0.

**Comment by leits** [comment]
![зображення](https://user-images.githubusercontent.com/12017826/107680565-aeebec00-6ca6-11eb-8663-2a0e030757a9.png)
